In [1]:
%run static_forms.py
%config Completer.use_jedi = False

2025-03-06 07:40:57,162 - INFO - REZULT_____________________________________________________
2025-03-06 07:40:57,187 - INFO - REZULT_____________________________________________________

In [2]:
%who

DataFrame	 Driver	 Order	 Series	 Settings	 alt	 count_graph	 cr	 data_sql
date_of_request	 datetime	 db_lock	 df_driver	 df_for_driver_glob	 df_orders	 exp	 forecast_driver	 get_list_construction_driver
get_list_construction_place	 get_newest_list_beton_or_lista	 inf	 inspect	 io	 lg	 logging	 np	 pd
pprint	 px	 re	 rng	 rozklad_curs	 text_sql_request	 threading

In [3]:
df_orders

[{'name': 'Park Skandynawia, etap E10, E1...',
  'meter': 180.0,
  'time': datetime.time(8, 0),
  'start_time': datetime.datetime(2025, 3, 7, 7, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 16, 18),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 7, 30),
   datetime.datetime(2025, 3, 7, 7, 54),
   datetime.datetime(2025, 3, 7, 8, 18),
   datetime.datetime(2025, 3, 7, 8, 42),
   datetime.datetime(2025, 3, 7, 9, 6),
   datetime.datetime(2025, 3, 7, 9, 30),
   datetime.datetime(2025, 3, 7, 9, 54),
   datetime.datetime(2025, 3, 7, 10, 18),
   datetime.datetime(2025, 3, 7, 10, 42),
   datetime.datetime(2025, 3, 7, 11, 6),
   datetime.datetime(2025, 3, 7, 11, 30),
   datetime.datetime(2025, 3, 7, 11, 54),
   datetime.datetime(2025, 3, 7, 12, 18),
   datetime.datetime(2025, 3, 7, 12, 42),
   datetime.datetime(2025, 3, 7, 13, 6),
   datetime.datetime(2025, 3, 7, 13, 30),
   datetime.datetime(2025, 3, 7, 13, 54),
   datetime.datetime(2025, 3, 7, 14, 18),
   datetime.datetime(2025, 3, 7, 14, 42),
   datetime.datetime(2025, 3, 7, 15, 6),
   datetime.datetime(2025, 3, 7, 15, 30),
   datetime.datetime(2025, 3, 7, 15, 54),
   datetime.datetime(2025, 3, 7, 16, 18)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   4.0],
  'pompa_dzwig': True,
  'reszta': [172.0,
   164.0,
   156.0,
   148.0,
   140.0,
   132.0,
   124.0,
   116.0,
   108.0,
   100.0,
   92.0,
   84.0,
   76.0,
   68.0,
   60.0,
   52.0,
   44.0,
   36.0,
   28.0,
   20.0,
   12.0,
   4.0,
   0.0],
  'date_order': '07.03.2025'},
 {'name': 'ESY , ul. Cybernetyki 7...',
  'meter': 100.0,
  'time': datetime.time(9, 0),
  'start_time': datetime.datetime(2025, 3, 7, 8, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 13, 18),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 8, 30),
   datetime.datetime(2025, 3, 7, 8, 54),
   datetime.datetime(2025, 3, 7, 9, 18),
   datetime.datetime(2025, 3, 7, 9, 42),
   datetime.datetime(2025, 3, 7, 10, 6),
   datetime.datetime(2025, 3, 7, 10, 30),
   datetime.datetime(2025, 3, 7, 10, 54),
   datetime.datetime(2025, 3, 7, 11, 18),
   datetime.datetime(2025, 3, 7, 11, 42),
   datetime.datetime(2025, 3, 7, 12, 6),
   datetime.datetime(2025, 3, 7, 12, 30),
   datetime.datetime(2025, 3, 7, 12, 54),
   datetime.datetime(2025, 3, 7, 13, 18)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   4.0],
  'pompa_dzwig': True,
  'reszta': [92.0,
   84.0,
   76.0,
   68.0,
   60.0,
   52.0,
   44.0,
   36.0,
   28.0,
   20.0,
   12.0,
   4.0,
   0.0],
  'date_order': '07.03.2025'},
 {'name': 'Mangalia 2 Warszawa...',
  'meter': 72.0,
  'time': datetime.time(13, 30),
  'start_time': datetime.datetime(2025, 3, 7, 13, 0),
  'finish_time': datetime.datetime(2025, 3, 7, 16, 12),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 13, 0),
   datetime.datetime(2025, 3, 7, 13, 24),
   datetime.datetime(2025, 3, 7, 13, 48),
   datetime.datetime(2025, 3, 7, 14, 12),
   datetime.datetime(2025, 3, 7, 14, 36),
   datetime.datetime(2025, 3, 7, 15, 0),
   datetime.datetime(2025, 3, 7, 15, 24),
   datetime.datetime(2025, 3, 7, 15, 48),
   datetime.datetime(2025, 3, 7, 16, 12)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0],
  'pompa_dzwig': True,
  'reszta': [64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'ESY , ul. Cybernetyki 7...',
  'meter': 16.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 15, 34),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Mangalia 2 Warszawa...',
  'meter': 16.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 15, 34),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'FLORESY , ul. Cybernetyki 7...',
  'meter': 24.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 16, 38),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34),
   datetime.datetime(2025, 3, 7, 16, 38)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [16.0, 8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Vena Prymasa Tysiąclecia 83...',
  'meter': 32.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 17, 42),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34),
   datetime.datetime(2025, 3, 7, 16, 38),
   datetime.datetime(2025, 3, 7, 17, 42)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [24.0, 16.0, 8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Warszawa ul.Siennicka...',
  'meter': 32.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 17, 42),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34),
   datetime.datetime(2025, 3, 7, 16, 38),
   datetime.datetime(2025, 3, 7, 17, 42)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [24.0, 16.0, 8.0, 0.0],
  'date_order': '07.03.2025'}]

In [4]:
bud = DataFrame(df_orders)
bud

,name,meter,time,start_time,finish_time,list_of_loads,wenz,it_is_zaprawa,it_is_concret,list_of_courses,pompa_dzwig,reszta,date_order
0,"Park Skandynawia, etap E10, E1...",180.0,08:00:00,2025-03-07 07:30:00,2025-03-07 16:18:00,"[2025-03-07 07:30:00, 2025-03-07 07:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[172.0, 164.0, 156.0, 148.0, 140.0, 132.0, 124...",07.03.2025
1,"ESY , ul. Cybernetyki 7...",100.0,09:00:00,2025-03-07 08:30:00,2025-03-07 13:18:00,"[2025-03-07 08:30:00, 2025-03-07 08:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[92.0, 84.0, 76.0, 68.0, 60.0, 52.0, 44.0, 36....",07.03.2025
2,Mangalia 2 Warszawa...,72.0,13:30:00,2025-03-07 13:00:00,2025-03-07 16:12:00,"[2025-03-07 13:00:00, 2025-03-07 13:24:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]",True,"[64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0...",07.03.2025
3,"ESY , ul. Cybernetyki 7...",16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
4,Mangalia 2 Warszawa...,16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
5,"FLORESY , ul. Cybernetyki 7...",24.0,15:00:00,2025-03-07 14:30:00,2025-03-07 16:38:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0]",False,"[16.0, 8.0, 0.0]",07.03.2025
6,Vena Prymasa Tysiąclecia 83...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025
7,Warszawa ul.Siennicka...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025

In [5]:
bud_without_dry = bud[bud["it_is_zaprawa"] | bud["it_is_concret"]]
bud_without_dry

,name,meter,time,start_time,finish_time,list_of_loads,wenz,it_is_zaprawa,it_is_concret,list_of_courses,pompa_dzwig,reszta,date_order
0,"Park Skandynawia, etap E10, E1...",180.0,08:00:00,2025-03-07 07:30:00,2025-03-07 16:18:00,"[2025-03-07 07:30:00, 2025-03-07 07:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[172.0, 164.0, 156.0, 148.0, 140.0, 132.0, 124...",07.03.2025
1,"ESY , ul. Cybernetyki 7...",100.0,09:00:00,2025-03-07 08:30:00,2025-03-07 13:18:00,"[2025-03-07 08:30:00, 2025-03-07 08:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[92.0, 84.0, 76.0, 68.0, 60.0, 52.0, 44.0, 36....",07.03.2025
2,Mangalia 2 Warszawa...,72.0,13:30:00,2025-03-07 13:00:00,2025-03-07 16:12:00,"[2025-03-07 13:00:00, 2025-03-07 13:24:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]",True,"[64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0...",07.03.2025
3,"ESY , ul. Cybernetyki 7...",16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
4,Mangalia 2 Warszawa...,16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
5,"FLORESY , ul. Cybernetyki 7...",24.0,15:00:00,2025-03-07 14:30:00,2025-03-07 16:38:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0]",False,"[16.0, 8.0, 0.0]",07.03.2025
6,Vena Prymasa Tysiąclecia 83...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025
7,Warszawa ul.Siennicka...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025

In [6]:
bud_without_dry["list_of_courses"].apply(lambda x: list(range(1, len(x) + 1)))

0    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
1          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
2                          [1, 2, 3, 4, 5, 6, 7, 8, 9]
3                                               [1, 2]
4                                               [1, 2]
5                                            [1, 2, 3]
6                                         [1, 2, 3, 4]
7                                         [1, 2, 3, 4]
Name: list_of_courses, dtype: object

In [7]:
bud_without_dry["namber_cours"] = bud_without_dry["list_of_courses"].apply(lambda x: list(range(1, len(x) + 1))).values
bud_without_dry

,name,meter,time,start_time,finish_time,list_of_loads,wenz,it_is_zaprawa,it_is_concret,list_of_courses,pompa_dzwig,reszta,date_order,namber_cours
0,"Park Skandynawia, etap E10, E1...",180.0,08:00:00,2025-03-07 07:30:00,2025-03-07 16:18:00,"[2025-03-07 07:30:00, 2025-03-07 07:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[172.0, 164.0, 156.0, 148.0, 140.0, 132.0, 124...",07.03.2025,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,"ESY , ul. Cybernetyki 7...",100.0,09:00:00,2025-03-07 08:30:00,2025-03-07 13:18:00,"[2025-03-07 08:30:00, 2025-03-07 08:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[92.0, 84.0, 76.0, 68.0, 60.0, 52.0, 44.0, 36....",07.03.2025,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]"
2,Mangalia 2 Warszawa...,72.0,13:30:00,2025-03-07 13:00:00,2025-03-07 16:12:00,"[2025-03-07 13:00:00, 2025-03-07 13:24:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]",True,"[64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0...",07.03.2025,"[1, 2, 3, 4, 5, 6, 7, 8, 9]"
3,"ESY , ul. Cybernetyki 7...",16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025,"[1, 2]"
4,Mangalia 2 Warszawa...,16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025,"[1, 2]"
5,"FLORESY , ul. Cybernetyki 7...",24.0,15:00:00,2025-03-07 14:30:00,2025-03-07 16:38:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0]",False,"[16.0, 8.0, 0.0]",07.03.2025,"[1, 2, 3]"
6,Vena Prymasa Tysiąclecia 83...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025,"[1, 2, 3, 4]"
7,Warszawa ul.Siennicka...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025,"[1, 2, 3, 4]"

In [8]:
# rozklad_curs = bud_without_dry[['list_of_loads', 'list_of_courses', 'name','reszta', 'it_is_zaprawa','pompa_dzwig']]\
# .explode(['list_of_loads','list_of_courses','reszta']).sort_values('list_of_loads')
rozklad_curs = bud_without_dry[['list_of_loads', 'list_of_courses', 'name','reszta', 'wenz', 'it_is_zaprawa','pompa_dzwig', 'namber_cours']]\
.explode(['list_of_loads','list_of_courses','reszta', 'namber_cours'])
rozklad_curs
# список отгрузок отсортированых по

,list_of_loads,list_of_courses,name,reszta,wenz,it_is_zaprawa,pompa_dzwig,namber_cours
0,2025-03-07 07:30:00,8.0,"Park Skandynawia, etap E10, E1...",172.0,1,False,True,1
0,2025-03-07 07:54:00,8.0,"Park Skandynawia, etap E10, E1...",164.0,1,False,True,2
0,2025-03-07 08:18:00,8.0,"Park Skandynawia, etap E10, E1...",156.0,1,False,True,3
0,2025-03-07 08:42:00,8.0,"Park Skandynawia, etap E10, E1...",148.0,1,False,True,4
0,2025-03-07 09:06:00,8.0,"Park Skandynawia, etap E10, E1...",140.0,1,False,True,5
0,2025-03-07 09:30:00,8.0,"Park Skandynawia, etap E10, E1...",132.0,1,False,True,6
0,2025-03-07 09:54:00,8.0,"Park Skandynawia, etap E10, E1...",124.0,1,False,True,7
0,2025-03-07 10:18:00,8.0,"Park Skandynawia, etap E10, E1...",116.0,1,False,True,8
0,2025-03-07 10:42:00,8.0,"Park Skandynawia, etap E10, E1...",108.0,1,False,True,9
0,2025-03-07 11:06:00,8.0,"Park Skandynawia, etap E10, E1...",100.0,1,False,True,10
0,2025-03-07 11:30:00,8.0,"Park Skandynawia, etap E10, E1...",92.0,1,False,True,11
0,2025-03-07 11:54:00,8.0,"Park Skandynawia, etap E10, E1...",84.0,1,False,True,12
0,2025-03-07 12:18:00,8.0,"Park Skandynawia, etap E10, E1...",76.0,1,False,True,13
0,2025-03-07 12:42:00,8.0,"Park Skandynawia, etap E10, E1...",68.0,1,False,True,14
0,2025-03-07 13:06:00,8.0,"Park Skandynawia, etap E10, E1...",60.0,1,False,True,15
0,2025-03-07 13:30:00,8.0,"Park Skandynawia, etap E10, E1...",52.0,1,False,True,16
0,2025-03-07 13:54:00,8.0,"Park Skandynawia, etap E10, E1...",44.0,1,False,True,17
0,2025-03-07 14:18:00,8.0,"Park Skandynawia, etap E10, E1...",36.0,1,False,True,18
0,2025-03-07 14:42:00,8.0,"Park Skandynawia, etap E10, E1...",28.0,1,False,True,19
0,2025-03-07 15:06:00,8.0,"Park Skandynawia, etap E10, E1...",20.0,1,False,True,20
0,2025-03-07 15:30:00,8.0,"Park Skandynawia, etap E10, E1...",12.0,1,False,True,21
0,2025-03-07 15:54:00,8.0,"Park Skandynawia, etap E10, E1...",4.0,1,False,True,22
0,2025-03-07 16:18:00,4.0,"Park Skandynawia, etap E10, E1...",0.0,1,False,True,23
1,2025-03-07 08:30:00,8.0,"ESY , ul. Cybernetyki 7...",92.0,1,False,True,1
1,2025-03-07 08:54:00,8.0,"ESY , ul. Cybernetyki 7...",84.0,1,False,True,2
1,2025-03-07 09:18:00,8.0,"ESY , ul. Cybernetyki 7...",76.0,1,False,True,3
1,2025-03-07 09:42:00,8.0,"ESY , ul. Cybernetyki 7...",68.0,1,False,True,4
1,2025-03-07 10:06:00,8.0,"ESY , ul. Cybernetyki 7...",60.0,1,False,True,5
1,2025-03-07 10:30:00,8.0,"ESY , ul. Cybernetyki 7...",52.0,1,False,True,6
1,2025-03-07 10:54:00,8.0,"ESY , ul. Cybernetyki 7...",44.0,1,False,True,7
1,2025-03-07 11:18:00,8.0,"ESY , ul. Cybernetyki 7...",36.0,1,False,True,8
1,2025-03-07 11:42:00,8.0,"ESY , ul. Cybernetyki 7...",28.0,1,False,True,9
1,2025-03-07 12:06:00,8.0,"ESY , ul. Cybernetyki 7...",20.0,1,False,True,10
1,2025-03-07 12:30:00,8.0,"ESY , ul. Cybernetyki 7...",12.0,1,False,True,11
1,2025-03-07 12:54:00,8.0,"ESY , ul. Cybernetyki 7...",4.0,1,False,True,12
1,2025-03-07 13:18:00,4.0,"ESY , ul. Cybernetyki 7...",0.0,1,False,True,13
2,2025-03-07 13:00:00,8.0,Mangalia 2 Warszawa...,64.0,1,False,True,1
2,2025-03-07 13:24:00,8.0,Mangalia 2 Warszawa...,56.0,1,False,True,2
2,2025-03-07 13:48:00,8.0,Mangalia 2 Warszawa...,48.0,1,False,True,3
2,2025-03-07 14:12:00,8.0,Mangalia 2 Warszawa...,40.0,1,False,True,4
2,2025-03-07 14:36:00,8.0,Mangalia 2 Warszawa...,32.0,1,False,True,5
2,2025-03-07 15:00:00,8.0,Mangalia 2 Warszawa...,24.0,1,False,True,6
2,2025-03-07 15:24:00,8.0,Mangalia 2 Warszawa...,16.0,1,False,True,7
2,2025-03-07 15:48:00,8.0,Mangalia 2 Warszawa...,8.0,1,False,True,8
2,2025-03-07 16:12:00,8.0,Mangalia 2 Warszawa...,0.0,1,False,True,9
3,2025-03-07 14:30:00,8.0,"ESY , ul. Cybernetyki 7...",8.0,1,False,False,1
3,2025-03-07 15:34:00,8.0,"ESY , ul. Cybernetyki 7...",0.0,1,False,False,2
4,2025-03-07 14:30:00,8.0,Mangalia 2 Warszawa...,8.0,1,False,False,1
4,2025-03-07 15:34:00,8.0,Mangalia 2 Warszawa...,0.0,1,False,False,2
5,2025-03-07 14:30:00,8.0,"FLORESY , ul. Cybernetyki 7...",16.0,1,False,False,1
5,2025-03-07 15:34:00,8.0,"FLORESY , ul. Cybernetyki 7...",8.0,1,False,False,2
5,2025-03-07 16:38:00,8.0,"FLORESY , ul. Cybernetyki 7...",0.0,1,False,False,3
6,2025-03-07 14:30:00,8.0,Vena Prymasa Tysiąclecia 83...,24.0,1,False,False,1
6,2025-03-07 15:34:00,8.0,Vena Prymasa Tysiąclecia 83...,16.0,1,False,False,2
6,2025-03-07 16:38:00,8.0,Vena Prymasa Tysiąclecia 83...,8.0,1,False,False,3
6,2025-03-07 17:42:00,8.0,Vena Prymasa Tysiąclecia 83...,0.0,1,False,False,4
7,2025-03-07 14:30:00,8.0,Warszawa ul.Siennicka...,24.0,1,False,False,1
7,2025-03-07 15:34:00,8.0,Warszawa ul.Siennicka...,16.0,1,False,False,2
7,2025-03-07 16:38:00,8.0,Warszawa ul.Siennicka...,8.0,1,False,False,3
7,2025-03-07 17:42:00,8.0,Warszawa ul.Siennicka...,0.0,1,False,False,4

In [9]:
rozklad_curs["it_is_zaprawa"] = rozklad_curs["it_is_zaprawa"].replace({True:'z', False:'b'})
rozklad_curs["pompa_dzwig"] = rozklad_curs["pompa_dzwig"].replace({True:'p', False:'d'})
rozklad_curs

,list_of_loads,list_of_courses,name,reszta,wenz,it_is_zaprawa,pompa_dzwig,namber_cours
0,2025-03-07 07:30:00,8.0,"Park Skandynawia, etap E10, E1...",172.0,1,b,p,1
0,2025-03-07 07:54:00,8.0,"Park Skandynawia, etap E10, E1...",164.0,1,b,p,2
0,2025-03-07 08:18:00,8.0,"Park Skandynawia, etap E10, E1...",156.0,1,b,p,3
0,2025-03-07 08:42:00,8.0,"Park Skandynawia, etap E10, E1...",148.0,1,b,p,4
0,2025-03-07 09:06:00,8.0,"Park Skandynawia, etap E10, E1...",140.0,1,b,p,5
0,2025-03-07 09:30:00,8.0,"Park Skandynawia, etap E10, E1...",132.0,1,b,p,6
0,2025-03-07 09:54:00,8.0,"Park Skandynawia, etap E10, E1...",124.0,1,b,p,7
0,2025-03-07 10:18:00,8.0,"Park Skandynawia, etap E10, E1...",116.0,1,b,p,8
0,2025-03-07 10:42:00,8.0,"Park Skandynawia, etap E10, E1...",108.0,1,b,p,9
0,2025-03-07 11:06:00,8.0,"Park Skandynawia, etap E10, E1...",100.0,1,b,p,10
0,2025-03-07 11:30:00,8.0,"Park Skandynawia, etap E10, E1...",92.0,1,b,p,11
0,2025-03-07 11:54:00,8.0,"Park Skandynawia, etap E10, E1...",84.0,1,b,p,12
0,2025-03-07 12:18:00,8.0,"Park Skandynawia, etap E10, E1...",76.0,1,b,p,13
0,2025-03-07 12:42:00,8.0,"Park Skandynawia, etap E10, E1...",68.0,1,b,p,14
0,2025-03-07 13:06:00,8.0,"Park Skandynawia, etap E10, E1...",60.0,1,b,p,15
0,2025-03-07 13:30:00,8.0,"Park Skandynawia, etap E10, E1...",52.0,1,b,p,16
0,2025-03-07 13:54:00,8.0,"Park Skandynawia, etap E10, E1...",44.0,1,b,p,17
0,2025-03-07 14:18:00,8.0,"Park Skandynawia, etap E10, E1...",36.0,1,b,p,18
0,2025-03-07 14:42:00,8.0,"Park Skandynawia, etap E10, E1...",28.0,1,b,p,19
0,2025-03-07 15:06:00,8.0,"Park Skandynawia, etap E10, E1...",20.0,1,b,p,20
0,2025-03-07 15:30:00,8.0,"Park Skandynawia, etap E10, E1...",12.0,1,b,p,21
0,2025-03-07 15:54:00,8.0,"Park Skandynawia, etap E10, E1...",4.0,1,b,p,22
0,2025-03-07 16:18:00,4.0,"Park Skandynawia, etap E10, E1...",0.0,1,b,p,23
1,2025-03-07 08:30:00,8.0,"ESY , ul. Cybernetyki 7...",92.0,1,b,p,1
1,2025-03-07 08:54:00,8.0,"ESY , ul. Cybernetyki 7...",84.0,1,b,p,2
1,2025-03-07 09:18:00,8.0,"ESY , ul. Cybernetyki 7...",76.0,1,b,p,3
1,2025-03-07 09:42:00,8.0,"ESY , ul. Cybernetyki 7...",68.0,1,b,p,4
1,2025-03-07 10:06:00,8.0,"ESY , ul. Cybernetyki 7...",60.0,1,b,p,5
1,2025-03-07 10:30:00,8.0,"ESY , ul. Cybernetyki 7...",52.0,1,b,p,6
1,2025-03-07 10:54:00,8.0,"ESY , ul. Cybernetyki 7...",44.0,1,b,p,7
1,2025-03-07 11:18:00,8.0,"ESY , ul. Cybernetyki 7...",36.0,1,b,p,8
1,2025-03-07 11:42:00,8.0,"ESY , ul. Cybernetyki 7...",28.0,1,b,p,9
1,2025-03-07 12:06:00,8.0,"ESY , ul. Cybernetyki 7...",20.0,1,b,p,10
1,2025-03-07 12:30:00,8.0,"ESY , ul. Cybernetyki 7...",12.0,1,b,p,11
1,2025-03-07 12:54:00,8.0,"ESY , ul. Cybernetyki 7...",4.0,1,b,p,12
1,2025-03-07 13:18:00,4.0,"ESY , ul. Cybernetyki 7...",0.0,1,b,p,13
2,2025-03-07 13:00:00,8.0,Mangalia 2 Warszawa...,64.0,1,b,p,1
2,2025-03-07 13:24:00,8.0,Mangalia 2 Warszawa...,56.0,1,b,p,2
2,2025-03-07 13:48:00,8.0,Mangalia 2 Warszawa...,48.0,1,b,p,3
2,2025-03-07 14:12:00,8.0,Mangalia 2 Warszawa...,40.0,1,b,p,4
2,2025-03-07 14:36:00,8.0,Mangalia 2 Warszawa...,32.0,1,b,p,5
2,2025-03-07 15:00:00,8.0,Mangalia 2 Warszawa...,24.0,1,b,p,6
2,2025-03-07 15:24:00,8.0,Mangalia 2 Warszawa...,16.0,1,b,p,7
2,2025-03-07 15:48:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,p,8
2,2025-03-07 16:12:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,p,9
3,2025-03-07 14:30:00,8.0,"ESY , ul. Cybernetyki 7...",8.0,1,b,d,1
3,2025-03-07 15:34:00,8.0,"ESY , ul. Cybernetyki 7...",0.0,1,b,d,2
4,2025-03-07 14:30:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,d,1
4,2025-03-07 15:34:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,d,2
5,2025-03-07 14:30:00,8.0,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d,1
5,2025-03-07 15:34:00,8.0,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d,2
5,2025-03-07 16:38:00,8.0,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d,3
6,2025-03-07 14:30:00,8.0,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d,1
6,2025-03-07 15:34:00,8.0,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d,2
6,2025-03-07 16:38:00,8.0,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d,3
6,2025-03-07 17:42:00,8.0,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d,4
7,2025-03-07 14:30:00,8.0,Warszawa ul.Siennicka...,24.0,1,b,d,1
7,2025-03-07 15:34:00,8.0,Warszawa ul.Siennicka...,16.0,1,b,d,2
7,2025-03-07 16:38:00,8.0,Warszawa ul.Siennicka...,8.0,1,b,d,3
7,2025-03-07 17:42:00,8.0,Warszawa ul.Siennicka...,0.0,1,b,d,4

In [10]:
rozklad_curs= rozklad_curs.reset_index()

In [11]:
rozklad_curs

,index,list_of_loads,list_of_courses,name,reszta,wenz,it_is_zaprawa,pompa_dzwig,namber_cours
0,0,2025-03-07 07:30:00,8.0,"Park Skandynawia, etap E10, E1...",172.0,1,b,p,1
1,0,2025-03-07 07:54:00,8.0,"Park Skandynawia, etap E10, E1...",164.0,1,b,p,2
2,0,2025-03-07 08:18:00,8.0,"Park Skandynawia, etap E10, E1...",156.0,1,b,p,3
3,0,2025-03-07 08:42:00,8.0,"Park Skandynawia, etap E10, E1...",148.0,1,b,p,4
4,0,2025-03-07 09:06:00,8.0,"Park Skandynawia, etap E10, E1...",140.0,1,b,p,5
5,0,2025-03-07 09:30:00,8.0,"Park Skandynawia, etap E10, E1...",132.0,1,b,p,6
6,0,2025-03-07 09:54:00,8.0,"Park Skandynawia, etap E10, E1...",124.0,1,b,p,7
7,0,2025-03-07 10:18:00,8.0,"Park Skandynawia, etap E10, E1...",116.0,1,b,p,8
8,0,2025-03-07 10:42:00,8.0,"Park Skandynawia, etap E10, E1...",108.0,1,b,p,9
9,0,2025-03-07 11:06:00,8.0,"Park Skandynawia, etap E10, E1...",100.0,1,b,p,10
10,0,2025-03-07 11:30:00,8.0,"Park Skandynawia, etap E10, E1...",92.0,1,b,p,11
11,0,2025-03-07 11:54:00,8.0,"Park Skandynawia, etap E10, E1...",84.0,1,b,p,12
12,0,2025-03-07 12:18:00,8.0,"Park Skandynawia, etap E10, E1...",76.0,1,b,p,13
13,0,2025-03-07 12:42:00,8.0,"Park Skandynawia, etap E10, E1...",68.0,1,b,p,14
14,0,2025-03-07 13:06:00,8.0,"Park Skandynawia, etap E10, E1...",60.0,1,b,p,15
15,0,2025-03-07 13:30:00,8.0,"Park Skandynawia, etap E10, E1...",52.0,1,b,p,16
16,0,2025-03-07 13:54:00,8.0,"Park Skandynawia, etap E10, E1...",44.0,1,b,p,17
17,0,2025-03-07 14:18:00,8.0,"Park Skandynawia, etap E10, E1...",36.0,1,b,p,18
18,0,2025-03-07 14:42:00,8.0,"Park Skandynawia, etap E10, E1...",28.0,1,b,p,19
19,0,2025-03-07 15:06:00,8.0,"Park Skandynawia, etap E10, E1...",20.0,1,b,p,20
20,0,2025-03-07 15:30:00,8.0,"Park Skandynawia, etap E10, E1...",12.0,1,b,p,21
21,0,2025-03-07 15:54:00,8.0,"Park Skandynawia, etap E10, E1...",4.0,1,b,p,22
22,0,2025-03-07 16:18:00,4.0,"Park Skandynawia, etap E10, E1...",0.0,1,b,p,23
23,1,2025-03-07 08:30:00,8.0,"ESY , ul. Cybernetyki 7...",92.0,1,b,p,1
24,1,2025-03-07 08:54:00,8.0,"ESY , ul. Cybernetyki 7...",84.0,1,b,p,2
25,1,2025-03-07 09:18:00,8.0,"ESY , ul. Cybernetyki 7...",76.0,1,b,p,3
26,1,2025-03-07 09:42:00,8.0,"ESY , ul. Cybernetyki 7...",68.0,1,b,p,4
27,1,2025-03-07 10:06:00,8.0,"ESY , ul. Cybernetyki 7...",60.0,1,b,p,5
28,1,2025-03-07 10:30:00,8.0,"ESY , ul. Cybernetyki 7...",52.0,1,b,p,6
29,1,2025-03-07 10:54:00,8.0,"ESY , ul. Cybernetyki 7...",44.0,1,b,p,7
30,1,2025-03-07 11:18:00,8.0,"ESY , ul. Cybernetyki 7...",36.0,1,b,p,8
31,1,2025-03-07 11:42:00,8.0,"ESY , ul. Cybernetyki 7...",28.0,1,b,p,9
32,1,2025-03-07 12:06:00,8.0,"ESY , ul. Cybernetyki 7...",20.0,1,b,p,10
33,1,2025-03-07 12:30:00,8.0,"ESY , ul. Cybernetyki 7...",12.0,1,b,p,11
34,1,2025-03-07 12:54:00,8.0,"ESY , ul. Cybernetyki 7...",4.0,1,b,p,12
35,1,2025-03-07 13:18:00,4.0,"ESY , ul. Cybernetyki 7...",0.0,1,b,p,13
36,2,2025-03-07 13:00:00,8.0,Mangalia 2 Warszawa...,64.0,1,b,p,1
37,2,2025-03-07 13:24:00,8.0,Mangalia 2 Warszawa...,56.0,1,b,p,2
38,2,2025-03-07 13:48:00,8.0,Mangalia 2 Warszawa...,48.0,1,b,p,3
39,2,2025-03-07 14:12:00,8.0,Mangalia 2 Warszawa...,40.0,1,b,p,4
40,2,2025-03-07 14:36:00,8.0,Mangalia 2 Warszawa...,32.0,1,b,p,5
41,2,2025-03-07 15:00:00,8.0,Mangalia 2 Warszawa...,24.0,1,b,p,6
42,2,2025-03-07 15:24:00,8.0,Mangalia 2 Warszawa...,16.0,1,b,p,7
43,2,2025-03-07 15:48:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,p,8
44,2,2025-03-07 16:12:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,p,9
45,3,2025-03-07 14:30:00,8.0,"ESY , ul. Cybernetyki 7...",8.0,1,b,d,1
46,3,2025-03-07 15:34:00,8.0,"ESY , ul. Cybernetyki 7...",0.0,1,b,d,2
47,4,2025-03-07 14:30:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,d,1
48,4,2025-03-07 15:34:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,d,2
49,5,2025-03-07 14:30:00,8.0,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d,1
50,5,2025-03-07 15:34:00,8.0,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d,2
51,5,2025-03-07 16:38:00,8.0,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d,3
52,6,2025-03-07 14:30:00,8.0,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d,1
53,6,2025-03-07 15:34:00,8.0,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d,2
54,6,2025-03-07 16:38:00,8.0,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d,3
55,6,2025-03-07 17:42:00,8.0,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d,4
56,7,2025-03-07 14:30:00,8.0,Warszawa ul.Siennicka...,24.0,1,b,d,1
57,7,2025-03-07 15:34:00,8.0,Warszawa ul.Siennicka...,16.0,1,b,d,2
58,7,2025-03-07 16:38:00,8.0,Warszawa ul.Siennicka...,8.0,1,b,d,3
59,7,2025-03-07 17:42:00,8.0,Warszawa ul.Siennicka...,0.0,1,b,d,4

In [12]:
rozklad_curs.index=rozklad_curs.index+1

In [13]:
rozklad_curs.columns = ['id', 'time', 'm3', 'budowa', 'res','wenz','mat', 'p/d', 'k']
rozklad_curs = rozklad_curs.reindex(['id', 'time', 'm3', 'k','budowa', 'res', 'wenz', 'mat', 'p/d' ], axis=1)
rozklad_curs

,id,time,m3,k,budowa,res,wenz,mat,p/d
1,0,2025-03-07 07:30:00,8.0,1,"Park Skandynawia, etap E10, E1...",172.0,1,b,p
2,0,2025-03-07 07:54:00,8.0,2,"Park Skandynawia, etap E10, E1...",164.0,1,b,p
3,0,2025-03-07 08:18:00,8.0,3,"Park Skandynawia, etap E10, E1...",156.0,1,b,p
4,0,2025-03-07 08:42:00,8.0,4,"Park Skandynawia, etap E10, E1...",148.0,1,b,p
5,0,2025-03-07 09:06:00,8.0,5,"Park Skandynawia, etap E10, E1...",140.0,1,b,p
6,0,2025-03-07 09:30:00,8.0,6,"Park Skandynawia, etap E10, E1...",132.0,1,b,p
7,0,2025-03-07 09:54:00,8.0,7,"Park Skandynawia, etap E10, E1...",124.0,1,b,p
8,0,2025-03-07 10:18:00,8.0,8,"Park Skandynawia, etap E10, E1...",116.0,1,b,p
9,0,2025-03-07 10:42:00,8.0,9,"Park Skandynawia, etap E10, E1...",108.0,1,b,p
10,0,2025-03-07 11:06:00,8.0,10,"Park Skandynawia, etap E10, E1...",100.0,1,b,p
11,0,2025-03-07 11:30:00,8.0,11,"Park Skandynawia, etap E10, E1...",92.0,1,b,p
12,0,2025-03-07 11:54:00,8.0,12,"Park Skandynawia, etap E10, E1...",84.0,1,b,p
13,0,2025-03-07 12:18:00,8.0,13,"Park Skandynawia, etap E10, E1...",76.0,1,b,p
14,0,2025-03-07 12:42:00,8.0,14,"Park Skandynawia, etap E10, E1...",68.0,1,b,p
15,0,2025-03-07 13:06:00,8.0,15,"Park Skandynawia, etap E10, E1...",60.0,1,b,p
16,0,2025-03-07 13:30:00,8.0,16,"Park Skandynawia, etap E10, E1...",52.0,1,b,p
17,0,2025-03-07 13:54:00,8.0,17,"Park Skandynawia, etap E10, E1...",44.0,1,b,p
18,0,2025-03-07 14:18:00,8.0,18,"Park Skandynawia, etap E10, E1...",36.0,1,b,p
19,0,2025-03-07 14:42:00,8.0,19,"Park Skandynawia, etap E10, E1...",28.0,1,b,p
20,0,2025-03-07 15:06:00,8.0,20,"Park Skandynawia, etap E10, E1...",20.0,1,b,p
21,0,2025-03-07 15:30:00,8.0,21,"Park Skandynawia, etap E10, E1...",12.0,1,b,p
22,0,2025-03-07 15:54:00,8.0,22,"Park Skandynawia, etap E10, E1...",4.0,1,b,p
23,0,2025-03-07 16:18:00,4.0,23,"Park Skandynawia, etap E10, E1...",0.0,1,b,p
24,1,2025-03-07 08:30:00,8.0,1,"ESY , ul. Cybernetyki 7...",92.0,1,b,p
25,1,2025-03-07 08:54:00,8.0,2,"ESY , ul. Cybernetyki 7...",84.0,1,b,p
26,1,2025-03-07 09:18:00,8.0,3,"ESY , ul. Cybernetyki 7...",76.0,1,b,p
27,1,2025-03-07 09:42:00,8.0,4,"ESY , ul. Cybernetyki 7...",68.0,1,b,p
28,1,2025-03-07 10:06:00,8.0,5,"ESY , ul. Cybernetyki 7...",60.0,1,b,p
29,1,2025-03-07 10:30:00,8.0,6,"ESY , ul. Cybernetyki 7...",52.0,1,b,p
30,1,2025-03-07 10:54:00,8.0,7,"ESY , ul. Cybernetyki 7...",44.0,1,b,p
31,1,2025-03-07 11:18:00,8.0,8,"ESY , ul. Cybernetyki 7...",36.0,1,b,p
32,1,2025-03-07 11:42:00,8.0,9,"ESY , ul. Cybernetyki 7...",28.0,1,b,p
33,1,2025-03-07 12:06:00,8.0,10,"ESY , ul. Cybernetyki 7...",20.0,1,b,p
34,1,2025-03-07 12:30:00,8.0,11,"ESY , ul. Cybernetyki 7...",12.0,1,b,p
35,1,2025-03-07 12:54:00,8.0,12,"ESY , ul. Cybernetyki 7...",4.0,1,b,p
36,1,2025-03-07 13:18:00,4.0,13,"ESY , ul. Cybernetyki 7...",0.0,1,b,p
37,2,2025-03-07 13:00:00,8.0,1,Mangalia 2 Warszawa...,64.0,1,b,p
38,2,2025-03-07 13:24:00,8.0,2,Mangalia 2 Warszawa...,56.0,1,b,p
39,2,2025-03-07 13:48:00,8.0,3,Mangalia 2 Warszawa...,48.0,1,b,p
40,2,2025-03-07 14:12:00,8.0,4,Mangalia 2 Warszawa...,40.0,1,b,p
41,2,2025-03-07 14:36:00,8.0,5,Mangalia 2 Warszawa...,32.0,1,b,p
42,2,2025-03-07 15:00:00,8.0,6,Mangalia 2 Warszawa...,24.0,1,b,p
43,2,2025-03-07 15:24:00,8.0,7,Mangalia 2 Warszawa...,16.0,1,b,p
44,2,2025-03-07 15:48:00,8.0,8,Mangalia 2 Warszawa...,8.0,1,b,p
45,2,2025-03-07 16:12:00,8.0,9,Mangalia 2 Warszawa...,0.0,1,b,p
46,3,2025-03-07 14:30:00,8.0,1,"ESY , ul. Cybernetyki 7...",8.0,1,b,d
47,3,2025-03-07 15:34:00,8.0,2,"ESY , ul. Cybernetyki 7...",0.0,1,b,d
48,4,2025-03-07 14:30:00,8.0,1,Mangalia 2 Warszawa...,8.0,1,b,d
49,4,2025-03-07 15:34:00,8.0,2,Mangalia 2 Warszawa...,0.0,1,b,d
50,5,2025-03-07 14:30:00,8.0,1,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d
51,5,2025-03-07 15:34:00,8.0,2,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d
52,5,2025-03-07 16:38:00,8.0,3,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d
53,6,2025-03-07 14:30:00,8.0,1,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d
54,6,2025-03-07 15:34:00,8.0,2,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d
55,6,2025-03-07 16:38:00,8.0,3,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d
56,6,2025-03-07 17:42:00,8.0,4,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d
57,7,2025-03-07 14:30:00,8.0,1,Warszawa ul.Siennicka...,24.0,1,b,d
58,7,2025-03-07 15:34:00,8.0,2,Warszawa ul.Siennicka...,16.0,1,b,d
59,7,2025-03-07 16:38:00,8.0,3,Warszawa ul.Siennicka...,8.0,1,b,d
60,7,2025-03-07 17:42:00,8.0,4,Warszawa ul.Siennicka...,0.0,1,b,d

In [14]:
# вставка для драйвер
rozklad_curs.sort_values("time", inplace=True)
rozklad_curs.reset_index(drop=True, inplace=True)
rozklad_curs.index=rozklad_curs.index+1
df_for_driver= rozklad_curs.copy()

In [15]:
# start make df for diver

df_for_driver

,id,time,m3,k,budowa,res,wenz,mat,p/d
1,0,2025-03-07 07:30:00,8.0,1,"Park Skandynawia, etap E10, E1...",172.0,1,b,p
2,0,2025-03-07 07:54:00,8.0,2,"Park Skandynawia, etap E10, E1...",164.0,1,b,p
3,0,2025-03-07 08:18:00,8.0,3,"Park Skandynawia, etap E10, E1...",156.0,1,b,p
4,1,2025-03-07 08:30:00,8.0,1,"ESY , ul. Cybernetyki 7...",92.0,1,b,p
5,0,2025-03-07 08:42:00,8.0,4,"Park Skandynawia, etap E10, E1...",148.0,1,b,p
6,1,2025-03-07 08:54:00,8.0,2,"ESY , ul. Cybernetyki 7...",84.0,1,b,p
7,0,2025-03-07 09:06:00,8.0,5,"Park Skandynawia, etap E10, E1...",140.0,1,b,p
8,1,2025-03-07 09:18:00,8.0,3,"ESY , ul. Cybernetyki 7...",76.0,1,b,p
9,0,2025-03-07 09:30:00,8.0,6,"Park Skandynawia, etap E10, E1...",132.0,1,b,p
10,1,2025-03-07 09:42:00,8.0,4,"ESY , ul. Cybernetyki 7...",68.0,1,b,p
11,0,2025-03-07 09:54:00,8.0,7,"Park Skandynawia, etap E10, E1...",124.0,1,b,p
12,1,2025-03-07 10:06:00,8.0,5,"ESY , ul. Cybernetyki 7...",60.0,1,b,p
13,0,2025-03-07 10:18:00,8.0,8,"Park Skandynawia, etap E10, E1...",116.0,1,b,p
14,1,2025-03-07 10:30:00,8.0,6,"ESY , ul. Cybernetyki 7...",52.0,1,b,p
15,0,2025-03-07 10:42:00,8.0,9,"Park Skandynawia, etap E10, E1...",108.0,1,b,p
16,1,2025-03-07 10:54:00,8.0,7,"ESY , ul. Cybernetyki 7...",44.0,1,b,p
17,0,2025-03-07 11:06:00,8.0,10,"Park Skandynawia, etap E10, E1...",100.0,1,b,p
18,1,2025-03-07 11:18:00,8.0,8,"ESY , ul. Cybernetyki 7...",36.0,1,b,p
19,0,2025-03-07 11:30:00,8.0,11,"Park Skandynawia, etap E10, E1...",92.0,1,b,p
20,1,2025-03-07 11:42:00,8.0,9,"ESY , ul. Cybernetyki 7...",28.0,1,b,p
21,0,2025-03-07 11:54:00,8.0,12,"Park Skandynawia, etap E10, E1...",84.0,1,b,p
22,1,2025-03-07 12:06:00,8.0,10,"ESY , ul. Cybernetyki 7...",20.0,1,b,p
23,0,2025-03-07 12:18:00,8.0,13,"Park Skandynawia, etap E10, E1...",76.0,1,b,p
24,1,2025-03-07 12:30:00,8.0,11,"ESY , ul. Cybernetyki 7...",12.0,1,b,p
25,0,2025-03-07 12:42:00,8.0,14,"Park Skandynawia, etap E10, E1...",68.0,1,b,p
26,1,2025-03-07 12:54:00,8.0,12,"ESY , ul. Cybernetyki 7...",4.0,1,b,p
27,2,2025-03-07 13:00:00,8.0,1,Mangalia 2 Warszawa...,64.0,1,b,p
28,0,2025-03-07 13:06:00,8.0,15,"Park Skandynawia, etap E10, E1...",60.0,1,b,p
29,1,2025-03-07 13:18:00,4.0,13,"ESY , ul. Cybernetyki 7...",0.0,1,b,p
30,2,2025-03-07 13:24:00,8.0,2,Mangalia 2 Warszawa...,56.0,1,b,p
31,0,2025-03-07 13:30:00,8.0,16,"Park Skandynawia, etap E10, E1...",52.0,1,b,p
32,2,2025-03-07 13:48:00,8.0,3,Mangalia 2 Warszawa...,48.0,1,b,p
33,0,2025-03-07 13:54:00,8.0,17,"Park Skandynawia, etap E10, E1...",44.0,1,b,p
34,2,2025-03-07 14:12:00,8.0,4,Mangalia 2 Warszawa...,40.0,1,b,p
35,0,2025-03-07 14:18:00,8.0,18,"Park Skandynawia, etap E10, E1...",36.0,1,b,p
36,7,2025-03-07 14:30:00,8.0,1,Warszawa ul.Siennicka...,24.0,1,b,d
37,6,2025-03-07 14:30:00,8.0,1,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d
38,3,2025-03-07 14:30:00,8.0,1,"ESY , ul. Cybernetyki 7...",8.0,1,b,d
39,5,2025-03-07 14:30:00,8.0,1,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d
40,4,2025-03-07 14:30:00,8.0,1,Mangalia 2 Warszawa...,8.0,1,b,d
41,2,2025-03-07 14:36:00,8.0,5,Mangalia 2 Warszawa...,32.0,1,b,p
42,0,2025-03-07 14:42:00,8.0,19,"Park Skandynawia, etap E10, E1...",28.0,1,b,p
43,2,2025-03-07 15:00:00,8.0,6,Mangalia 2 Warszawa...,24.0,1,b,p
44,0,2025-03-07 15:06:00,8.0,20,"Park Skandynawia, etap E10, E1...",20.0,1,b,p
45,2,2025-03-07 15:24:00,8.0,7,Mangalia 2 Warszawa...,16.0,1,b,p
46,0,2025-03-07 15:30:00,8.0,21,"Park Skandynawia, etap E10, E1...",12.0,1,b,p
47,3,2025-03-07 15:34:00,8.0,2,"ESY , ul. Cybernetyki 7...",0.0,1,b,d
48,5,2025-03-07 15:34:00,8.0,2,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d
49,6,2025-03-07 15:34:00,8.0,2,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d
50,7,2025-03-07 15:34:00,8.0,2,Warszawa ul.Siennicka...,16.0,1,b,d
51,4,2025-03-07 15:34:00,8.0,2,Mangalia 2 Warszawa...,0.0,1,b,d
52,2,2025-03-07 15:48:00,8.0,8,Mangalia 2 Warszawa...,8.0,1,b,p
53,0,2025-03-07 15:54:00,8.0,22,"Park Skandynawia, etap E10, E1...",4.0,1,b,p
54,2,2025-03-07 16:12:00,8.0,9,Mangalia 2 Warszawa...,0.0,1,b,p
55,0,2025-03-07 16:18:00,4.0,23,"Park Skandynawia, etap E10, E1...",0.0,1,b,p
56,5,2025-03-07 16:38:00,8.0,3,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d
57,7,2025-03-07 16:38:00,8.0,3,Warszawa ul.Siennicka...,8.0,1,b,d
58,6,2025-03-07 16:38:00,8.0,3,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d
59,6,2025-03-07 17:42:00,8.0,4,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d
60,7,2025-03-07 17:42:00,8.0,4,Warszawa ul.Siennicka...,0.0,1,b,d

In [16]:
df_for_driver = df_for_driver[["time","m3","mat","p/d"]]
df_for_driver

                  time   m3 mat p/d
1  2025-03-07 07:30:00  8.0   b   p
2  2025-03-07 07:54:00  8.0   b   p
3  2025-03-07 08:18:00  8.0   b   p
4  2025-03-07 08:30:00  8.0   b   p
5  2025-03-07 08:42:00  8.0   b   p
6  2025-03-07 08:54:00  8.0   b   p
7  2025-03-07 09:06:00  8.0   b   p
8  2025-03-07 09:18:00  8.0   b   p
9  2025-03-07 09:30:00  8.0   b   p
10 2025-03-07 09:42:00  8.0   b   p
11 2025-03-07 09:54:00  8.0   b   p
12 2025-03-07 10:06:00  8.0   b   p
13 2025-03-07 10:18:00  8.0   b   p
14 2025-03-07 10:30:00  8.0   b   p
15 2025-03-07 10:42:00  8.0   b   p
16 2025-03-07 10:54:00  8.0   b   p
17 2025-03-07 11:06:00  8.0   b   p
18 2025-03-07 11:18:00  8.0   b   p
19 2025-03-07 11:30:00  8.0   b   p
20 2025-03-07 11:42:00  8.0   b   p
21 2025-03-07 11:54:00  8.0   b   p
22 2025-03-07 12:06:00  8.0   b   p
23 2025-03-07 12:18:00  8.0   b   p
24 2025-03-07 12:30:00  8.0   b   p
25 2025-03-07 12:42:00  8.0   b   p
26 2025-03-07 12:54:00  8.0   b   p
27 2025-03-07 13:00:00  8.0   b   p
28 2025-03-07 13:06:00  8.0   b   p
29 2025-03-07 13:18:00  4.0   b   p
30 2025-03-07 13:24:00  8.0   b   p
31 2025-03-07 13:30:00  8.0   b   p
32 2025-03-07 13:48:00  8.0   b   p
33 2025-03-07 13:54:00  8.0   b   p
34 2025-03-07 14:12:00  8.0   b   p
35 2025-03-07 14:18:00  8.0   b   p
36 2025-03-07 14:30:00  8.0   b   d
37 2025-03-07 14:30:00  8.0   b   d
38 2025-03-07 14:30:00  8.0   b   d
39 2025-03-07 14:30:00  8.0   b   d
40 2025-03-07 14:30:00  8.0   b   d
41 2025-03-07 14:36:00  8.0   b   p
42 2025-03-07 14:42:00  8.0   b   p
43 2025-03-07 15:00:00  8.0   b   p
44 2025-03-07 15:06:00  8.0   b   p
45 2025-03-07 15:24:00  8.0   b   p
46 2025-03-07 15:30:00  8.0   b   p
47 2025-03-07 15:34:00  8.0   b   d
48 2025-03-07 15:34:00  8.0   b   d
49 2025-03-07 15:34:00  8.0   b   d
50 2025-03-07 15:34:00  8.0   b   d
51 2025-03-07 15:34:00  8.0   b   d
52 2025-03-07 15:48:00  8.0   b   p
53 2025-03-07 15:54:00  8.0   b   p
54 2025-03-07 16:12:00  8.0   b   p
55 2025-03-07 16:18:00  4.0   b   p
56 2025-03-07 16:38:00  8.0   b   d
57 2025-03-07 16:38:00  8.0   b   d
58 2025-03-07 16:38:00  8.0   b   d
59 2025-03-07 17:42:00  8.0   b   d
60 2025-03-07 17:42:00  8.0   b   d

In [17]:
df_for_driver

                  time   m3 mat p/d
1  2025-03-07 07:30:00  8.0   b   p
2  2025-03-07 07:54:00  8.0   b   p
3  2025-03-07 08:18:00  8.0   b   p
4  2025-03-07 08:30:00  8.0   b   p
5  2025-03-07 08:42:00  8.0   b   p
6  2025-03-07 08:54:00  8.0   b   p
7  2025-03-07 09:06:00  8.0   b   p
8  2025-03-07 09:18:00  8.0   b   p
9  2025-03-07 09:30:00  8.0   b   p
10 2025-03-07 09:42:00  8.0   b   p
11 2025-03-07 09:54:00  8.0   b   p
12 2025-03-07 10:06:00  8.0   b   p
13 2025-03-07 10:18:00  8.0   b   p
14 2025-03-07 10:30:00  8.0   b   p
15 2025-03-07 10:42:00  8.0   b   p
16 2025-03-07 10:54:00  8.0   b   p
17 2025-03-07 11:06:00  8.0   b   p
18 2025-03-07 11:18:00  8.0   b   p
19 2025-03-07 11:30:00  8.0   b   p
20 2025-03-07 11:42:00  8.0   b   p
21 2025-03-07 11:54:00  8.0   b   p
22 2025-03-07 12:06:00  8.0   b   p
23 2025-03-07 12:18:00  8.0   b   p
24 2025-03-07 12:30:00  8.0   b   p
25 2025-03-07 12:42:00  8.0   b   p
26 2025-03-07 12:54:00  8.0   b   p
27 2025-03-07 13:00:00  8.0   b   p
28 2025-03-07 13:06:00  8.0   b   p
29 2025-03-07 13:18:00  4.0   b   p
30 2025-03-07 13:24:00  8.0   b   p
31 2025-03-07 13:30:00  8.0   b   p
32 2025-03-07 13:48:00  8.0   b   p
33 2025-03-07 13:54:00  8.0   b   p
34 2025-03-07 14:12:00  8.0   b   p
35 2025-03-07 14:18:00  8.0   b   p
36 2025-03-07 14:30:00  8.0   b   d
37 2025-03-07 14:30:00  8.0   b   d
38 2025-03-07 14:30:00  8.0   b   d
39 2025-03-07 14:30:00  8.0   b   d
40 2025-03-07 14:30:00  8.0   b   d
41 2025-03-07 14:36:00  8.0   b   p
42 2025-03-07 14:42:00  8.0   b   p
43 2025-03-07 15:00:00  8.0   b   p
44 2025-03-07 15:06:00  8.0   b   p
45 2025-03-07 15:24:00  8.0   b   p
46 2025-03-07 15:30:00  8.0   b   p
47 2025-03-07 15:34:00  8.0   b   d
48 2025-03-07 15:34:00  8.0   b   d
49 2025-03-07 15:34:00  8.0   b   d
50 2025-03-07 15:34:00  8.0   b   d
51 2025-03-07 15:34:00  8.0   b   d
52 2025-03-07 15:48:00  8.0   b   p
53 2025-03-07 15:54:00  8.0   b   p
54 2025-03-07 16:12:00  8.0   b   p
55 2025-03-07 16:18:00  4.0   b   p
56 2025-03-07 16:38:00  8.0   b   d
57 2025-03-07 16:38:00  8.0   b   d
58 2025-03-07 16:38:00  8.0   b   d
59 2025-03-07 17:42:00  8.0   b   d
60 2025-03-07 17:42:00  8.0   b   d

In [18]:
df_for_driver = df_for_driver.copy()
df_for_driver['m3'] = df_for_driver['m3'].astype(float)
df_for_driver.dtypes

time    datetime64[ns]
m3             float64
mat             object
p/d             object
dtype: object

In [19]:
def get_end_time(row):
    additional_hour = pd.Timedelta(hours=1)
    if row['p/d'] == 'p':
        time_in_minutes = pd.to_timedelta(row['m3']*3, unit='m')
    else:
        time_in_minutes = pd.to_timedelta(row['m3']*8, unit='m')
    return row['time'] + time_in_minutes + additional_hour

In [20]:
df_for_driver.loc[:,'end_time'] = df_for_driver.apply(get_end_time, axis=1)

In [21]:
df_for_driver

                  time   m3 mat p/d            end_time
1  2025-03-07 07:30:00  8.0   b   p 2025-03-07 08:54:00
2  2025-03-07 07:54:00  8.0   b   p 2025-03-07 09:18:00
3  2025-03-07 08:18:00  8.0   b   p 2025-03-07 09:42:00
4  2025-03-07 08:30:00  8.0   b   p 2025-03-07 09:54:00
5  2025-03-07 08:42:00  8.0   b   p 2025-03-07 10:06:00
6  2025-03-07 08:54:00  8.0   b   p 2025-03-07 10:18:00
7  2025-03-07 09:06:00  8.0   b   p 2025-03-07 10:30:00
8  2025-03-07 09:18:00  8.0   b   p 2025-03-07 10:42:00
9  2025-03-07 09:30:00  8.0   b   p 2025-03-07 10:54:00
10 2025-03-07 09:42:00  8.0   b   p 2025-03-07 11:06:00
11 2025-03-07 09:54:00  8.0   b   p 2025-03-07 11:18:00
12 2025-03-07 10:06:00  8.0   b   p 2025-03-07 11:30:00
13 2025-03-07 10:18:00  8.0   b   p 2025-03-07 11:42:00
14 2025-03-07 10:30:00  8.0   b   p 2025-03-07 11:54:00
15 2025-03-07 10:42:00  8.0   b   p 2025-03-07 12:06:00
16 2025-03-07 10:54:00  8.0   b   p 2025-03-07 12:18:00
17 2025-03-07 11:06:00  8.0   b   p 2025-03-07 12:30:00
18 2025-03-07 11:18:00  8.0   b   p 2025-03-07 12:42:00
19 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
20 2025-03-07 11:42:00  8.0   b   p 2025-03-07 13:06:00
21 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
22 2025-03-07 12:06:00  8.0   b   p 2025-03-07 13:30:00
23 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
24 2025-03-07 12:30:00  8.0   b   p 2025-03-07 13:54:00
25 2025-03-07 12:42:00  8.0   b   p 2025-03-07 14:06:00
26 2025-03-07 12:54:00  8.0   b   p 2025-03-07 14:18:00
27 2025-03-07 13:00:00  8.0   b   p 2025-03-07 14:24:00
28 2025-03-07 13:06:00  8.0   b   p 2025-03-07 14:30:00
29 2025-03-07 13:18:00  4.0   b   p 2025-03-07 14:30:00
30 2025-03-07 13:24:00  8.0   b   p 2025-03-07 14:48:00
31 2025-03-07 13:30:00  8.0   b   p 2025-03-07 14:54:00
32 2025-03-07 13:48:00  8.0   b   p 2025-03-07 15:12:00
33 2025-03-07 13:54:00  8.0   b   p 2025-03-07 15:18:00
34 2025-03-07 14:12:00  8.0   b   p 2025-03-07 15:36:00
35 2025-03-07 14:18:00  8.0   b   p 2025-03-07 15:42:00
36 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
37 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
38 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
39 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
40 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
41 2025-03-07 14:36:00  8.0   b   p 2025-03-07 16:00:00
42 2025-03-07 14:42:00  8.0   b   p 2025-03-07 16:06:00
43 2025-03-07 15:00:00  8.0   b   p 2025-03-07 16:24:00
44 2025-03-07 15:06:00  8.0   b   p 2025-03-07 16:30:00
45 2025-03-07 15:24:00  8.0   b   p 2025-03-07 16:48:00
46 2025-03-07 15:30:00  8.0   b   p 2025-03-07 16:54:00
47 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
48 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
49 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
50 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
51 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
52 2025-03-07 15:48:00  8.0   b   p 2025-03-07 17:12:00
53 2025-03-07 15:54:00  8.0   b   p 2025-03-07 17:18:00
54 2025-03-07 16:12:00  8.0   b   p 2025-03-07 17:36:00
55 2025-03-07 16:18:00  4.0   b   p 2025-03-07 17:30:00
56 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
57 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
58 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
59 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00
60 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00

In [22]:
df_for_driver.dtypes

time        datetime64[ns]
m3                 float64
mat                 object
p/d                 object
end_time    datetime64[ns]
dtype: object

In [23]:
# Преобразование строки в формате 'dd.mm.yyyy' в 'yyyy-mm-dd'
formatted_date_start = pd.to_datetime(date_of_request, format='%d.%m.%Y').strftime('%Y-%m-%d') + ' 04:00:00'
formatted_date_finish = pd.to_datetime(date_of_request, format='%d.%m.%Y').strftime('%Y-%m-%d') + ' 23:00:00'

In [24]:
formatted_date_finish

'2025-03-07 23:00:00'

In [25]:
time_index = pd.date_range(start=formatted_date_start, end=formatted_date_finish, freq='min')

In [26]:
time_index

DatetimeIndex(['2025-03-07 04:00:00', '2025-03-07 04:01:00',
               '2025-03-07 04:02:00', '2025-03-07 04:03:00',
               '2025-03-07 04:04:00', '2025-03-07 04:05:00',
               '2025-03-07 04:06:00', '2025-03-07 04:07:00',
               '2025-03-07 04:08:00', '2025-03-07 04:09:00',
               ...
               '2025-03-07 22:51:00', '2025-03-07 22:52:00',
               '2025-03-07 22:53:00', '2025-03-07 22:54:00',
               '2025-03-07 22:55:00', '2025-03-07 22:56:00',
               '2025-03-07 22:57:00', '2025-03-07 22:58:00',
               '2025-03-07 22:59:00', '2025-03-07 23:00:00'],
              dtype='datetime64[ns]', length=1141, freq='min')

In [27]:
df_full_day =  pd.DataFrame(index=time_index)

In [28]:
len(df_for_driver)

60

In [29]:
df_for_driver

                  time   m3 mat p/d            end_time
1  2025-03-07 07:30:00  8.0   b   p 2025-03-07 08:54:00
2  2025-03-07 07:54:00  8.0   b   p 2025-03-07 09:18:00
3  2025-03-07 08:18:00  8.0   b   p 2025-03-07 09:42:00
4  2025-03-07 08:30:00  8.0   b   p 2025-03-07 09:54:00
5  2025-03-07 08:42:00  8.0   b   p 2025-03-07 10:06:00
6  2025-03-07 08:54:00  8.0   b   p 2025-03-07 10:18:00
7  2025-03-07 09:06:00  8.0   b   p 2025-03-07 10:30:00
8  2025-03-07 09:18:00  8.0   b   p 2025-03-07 10:42:00
9  2025-03-07 09:30:00  8.0   b   p 2025-03-07 10:54:00
10 2025-03-07 09:42:00  8.0   b   p 2025-03-07 11:06:00
11 2025-03-07 09:54:00  8.0   b   p 2025-03-07 11:18:00
12 2025-03-07 10:06:00  8.0   b   p 2025-03-07 11:30:00
13 2025-03-07 10:18:00  8.0   b   p 2025-03-07 11:42:00
14 2025-03-07 10:30:00  8.0   b   p 2025-03-07 11:54:00
15 2025-03-07 10:42:00  8.0   b   p 2025-03-07 12:06:00
16 2025-03-07 10:54:00  8.0   b   p 2025-03-07 12:18:00
17 2025-03-07 11:06:00  8.0   b   p 2025-03-07 12:30:00
18 2025-03-07 11:18:00  8.0   b   p 2025-03-07 12:42:00
19 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
20 2025-03-07 11:42:00  8.0   b   p 2025-03-07 13:06:00
21 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
22 2025-03-07 12:06:00  8.0   b   p 2025-03-07 13:30:00
23 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
24 2025-03-07 12:30:00  8.0   b   p 2025-03-07 13:54:00
25 2025-03-07 12:42:00  8.0   b   p 2025-03-07 14:06:00
26 2025-03-07 12:54:00  8.0   b   p 2025-03-07 14:18:00
27 2025-03-07 13:00:00  8.0   b   p 2025-03-07 14:24:00
28 2025-03-07 13:06:00  8.0   b   p 2025-03-07 14:30:00
29 2025-03-07 13:18:00  4.0   b   p 2025-03-07 14:30:00
30 2025-03-07 13:24:00  8.0   b   p 2025-03-07 14:48:00
31 2025-03-07 13:30:00  8.0   b   p 2025-03-07 14:54:00
32 2025-03-07 13:48:00  8.0   b   p 2025-03-07 15:12:00
33 2025-03-07 13:54:00  8.0   b   p 2025-03-07 15:18:00
34 2025-03-07 14:12:00  8.0   b   p 2025-03-07 15:36:00
35 2025-03-07 14:18:00  8.0   b   p 2025-03-07 15:42:00
36 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
37 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
38 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
39 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
40 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
41 2025-03-07 14:36:00  8.0   b   p 2025-03-07 16:00:00
42 2025-03-07 14:42:00  8.0   b   p 2025-03-07 16:06:00
43 2025-03-07 15:00:00  8.0   b   p 2025-03-07 16:24:00
44 2025-03-07 15:06:00  8.0   b   p 2025-03-07 16:30:00
45 2025-03-07 15:24:00  8.0   b   p 2025-03-07 16:48:00
46 2025-03-07 15:30:00  8.0   b   p 2025-03-07 16:54:00
47 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
48 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
49 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
50 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
51 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
52 2025-03-07 15:48:00  8.0   b   p 2025-03-07 17:12:00
53 2025-03-07 15:54:00  8.0   b   p 2025-03-07 17:18:00
54 2025-03-07 16:12:00  8.0   b   p 2025-03-07 17:36:00
55 2025-03-07 16:18:00  4.0   b   p 2025-03-07 17:30:00
56 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
57 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
58 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
59 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00
60 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00

In [30]:
df_full_day

Empty DataFrame
Columns: []
Index: [2025-03-07 04:00:00, 2025-03-07 04:01:00, 2025-03-07 04:02:00, 2025-03-07 04:03:00, 2025-03-07 04:04:00, 2025-03-07 04:05:00, 2025-03-07 04:06:00, 2025-03-07 04:07:00, 2025-03-07 04:08:00, 2025-03-07 04:09:00, 2025-03-07 04:10:00, 2025-03-07 04:11:00, 2025-03-07 04:12:00, 2025-03-07 04:13:00, 2025-03-07 04:14:00, 2025-03-07 04:15:00, 2025-03-07 04:16:00, 2025-03-07 04:17:00, 2025-03-07 04:18:00, 2025-03-07 04:19:00, 2025-03-07 04:20:00, 2025-03-07 04:21:00, 2025-03-07 04:22:00, 2025-03-07 04:23:00, 2025-03-07 04:24:00, 2025-03-07 04:25:00, 2025-03-07 04:26:00, 2025-03-07 04:27:00, 2025-03-07 04:28:00, 2025-03-07 04:29:00, 2025-03-07 04:30:00, 2025-03-07 04:31:00, 2025-03-07 04:32:00, 2025-03-07 04:33:00, 2025-03-07 04:34:00, 2025-03-07 04:35:00, 2025-03-07 04:36:00, 2025-03-07 04:37:00, 2025-03-07 04:38:00, 2025-03-07 04:39:00, 2025-03-07 04:40:00, 2025-03-07 04:41:00, 2025-03-07 04:42:00, 2025-03-07 04:43:00, 2025-03-07 04:44:00, 2025-03-07 04:45:00, 2025-03-07 04:46:00, 2025-03-07 04:47:00, 2025-03-07 04:48:00, 2025-03-07 04:49:00, 2025-03-07 04:50:00, 2025-03-07 04:51:00, 2025-03-07 04:52:00, 2025-03-07 04:53:00, 2025-03-07 04:54:00, 2025-03-07 04:55:00, 2025-03-07 04:56:00, 2025-03-07 04:57:00, 2025-03-07 04:58:00, 2025-03-07 04:59:00, 2025-03-07 05:00:00, 2025-03-07 05:01:00, 2025-03-07 05:02:00, 2025-03-07 05:03:00, 2025-03-07 05:04:00, 2025-03-07 05:05:00, 2025-03-07 05:06:00, 2025-03-07 05:07:00, 2025-03-07 05:08:00, 2025-03-07 05:09:00, 2025-03-07 05:10:00, 2025-03-07 05:11:00, 2025-03-07 05:12:00, 2025-03-07 05:13:00, 2025-03-07 05:14:00, 2025-03-07 05:15:00, 2025-03-07 05:16:00, 2025-03-07 05:17:00, 2025-03-07 05:18:00, 2025-03-07 05:19:00, 2025-03-07 05:20:00, 2025-03-07 05:21:00, 2025-03-07 05:22:00, 2025-03-07 05:23:00, 2025-03-07 05:24:00, 2025-03-07 05:25:00, 2025-03-07 05:26:00, 2025-03-07 05:27:00, 2025-03-07 05:28:00, 2025-03-07 05:29:00, 2025-03-07 05:30:00, 2025-03-07 05:31:00, 2025-03-07 05:32:00, 2025-03-07 05:33:00, 2025-03-07 05:34:00, 2025-03-07 05:35:00, 2025-03-07 05:36:00, 2025-03-07 05:37:00, 2025-03-07 05:38:00, 2025-03-07 05:39:00, ...]

[1141 rows x 0 columns]

In [31]:
for i in range(1,len(df_for_driver)+1):
    mask = (df_full_day.index >= df_for_driver.loc[i, 'time']) & (df_full_day.index <= df_for_driver.loc[i, 'end_time'])
    # df_full_day[i] = np.where(mask, df_for_driver.loc[i, 'mat'], '')
    df_full_day.loc[mask, i] = df_for_driver.loc[i, 'mat']

In [32]:
# for i, row in df_for_driver.iterrows():
#     # Создаем маску интервала времени
#     mask = (time_index.time >= row['time']) & (time_index.time < row['end_time'])
#     # Копируем столбец же 'value' с условием
#     df_full_day.loc[mask, i] = row['mat']

In [33]:
# df_full_day.replace('',0, inplace=True)
df_full_day = df_full_day.fillna(0)

In [34]:
df_full_day[df_full_day[1]=='b']

,1,2,3,4,5,6,7,8,9,10,...,51,52,53,54,55,56,57,58,59,60
2025-03-07 07:30:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:31:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:32:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:33:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:34:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-07 08:50:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:51:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:52:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:53:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:54:00,b,b,b,b,b,b,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df_for_driver

                  time   m3 mat p/d            end_time
1  2025-03-07 07:30:00  8.0   b   p 2025-03-07 08:54:00
2  2025-03-07 07:54:00  8.0   b   p 2025-03-07 09:18:00
3  2025-03-07 08:18:00  8.0   b   p 2025-03-07 09:42:00
4  2025-03-07 08:30:00  8.0   b   p 2025-03-07 09:54:00
5  2025-03-07 08:42:00  8.0   b   p 2025-03-07 10:06:00
6  2025-03-07 08:54:00  8.0   b   p 2025-03-07 10:18:00
7  2025-03-07 09:06:00  8.0   b   p 2025-03-07 10:30:00
8  2025-03-07 09:18:00  8.0   b   p 2025-03-07 10:42:00
9  2025-03-07 09:30:00  8.0   b   p 2025-03-07 10:54:00
10 2025-03-07 09:42:00  8.0   b   p 2025-03-07 11:06:00
11 2025-03-07 09:54:00  8.0   b   p 2025-03-07 11:18:00
12 2025-03-07 10:06:00  8.0   b   p 2025-03-07 11:30:00
13 2025-03-07 10:18:00  8.0   b   p 2025-03-07 11:42:00
14 2025-03-07 10:30:00  8.0   b   p 2025-03-07 11:54:00
15 2025-03-07 10:42:00  8.0   b   p 2025-03-07 12:06:00
16 2025-03-07 10:54:00  8.0   b   p 2025-03-07 12:18:00
17 2025-03-07 11:06:00  8.0   b   p 2025-03-07 12:30:00
18 2025-03-07 11:18:00  8.0   b   p 2025-03-07 12:42:00
19 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
20 2025-03-07 11:42:00  8.0   b   p 2025-03-07 13:06:00
21 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
22 2025-03-07 12:06:00  8.0   b   p 2025-03-07 13:30:00
23 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
24 2025-03-07 12:30:00  8.0   b   p 2025-03-07 13:54:00
25 2025-03-07 12:42:00  8.0   b   p 2025-03-07 14:06:00
26 2025-03-07 12:54:00  8.0   b   p 2025-03-07 14:18:00
27 2025-03-07 13:00:00  8.0   b   p 2025-03-07 14:24:00
28 2025-03-07 13:06:00  8.0   b   p 2025-03-07 14:30:00
29 2025-03-07 13:18:00  4.0   b   p 2025-03-07 14:30:00
30 2025-03-07 13:24:00  8.0   b   p 2025-03-07 14:48:00
31 2025-03-07 13:30:00  8.0   b   p 2025-03-07 14:54:00
32 2025-03-07 13:48:00  8.0   b   p 2025-03-07 15:12:00
33 2025-03-07 13:54:00  8.0   b   p 2025-03-07 15:18:00
34 2025-03-07 14:12:00  8.0   b   p 2025-03-07 15:36:00
35 2025-03-07 14:18:00  8.0   b   p 2025-03-07 15:42:00
36 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
37 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
38 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
39 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
40 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
41 2025-03-07 14:36:00  8.0   b   p 2025-03-07 16:00:00
42 2025-03-07 14:42:00  8.0   b   p 2025-03-07 16:06:00
43 2025-03-07 15:00:00  8.0   b   p 2025-03-07 16:24:00
44 2025-03-07 15:06:00  8.0   b   p 2025-03-07 16:30:00
45 2025-03-07 15:24:00  8.0   b   p 2025-03-07 16:48:00
46 2025-03-07 15:30:00  8.0   b   p 2025-03-07 16:54:00
47 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
48 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
49 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
50 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
51 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
52 2025-03-07 15:48:00  8.0   b   p 2025-03-07 17:12:00
53 2025-03-07 15:54:00  8.0   b   p 2025-03-07 17:18:00
54 2025-03-07 16:12:00  8.0   b   p 2025-03-07 17:36:00
55 2025-03-07 16:18:00  4.0   b   p 2025-03-07 17:30:00
56 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
57 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
58 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
59 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00
60 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00

In [36]:
df_driver_list =DataFrame(df_driver)

In [37]:
if df_driver_list.empty:
    driver_dict = {}
    free_exict_list =  [f'kerowec_{i}' for i in range(1, 26)]
else:
    date_as_datetime = pd.to_datetime(date_of_request, format='%d.%m.%Y')
    df_driver_list.loc[:,'time'] = df_driver_list.loc[:,'time'].apply(lambda t: datetime.combine(date_as_datetime.date(), t))
    driver_dict = df_driver_list.set_index('person')['time'].to_dict()
    free_exict_list = []

In [38]:
driver_dict

{'MAN WJ2931G   Rusłan Skubi': Timestamp('2025-03-07 06:00:00'),
 'Marcin Zapora WD4163T': Timestamp('2025-03-07 06:10:00'),
 'WZ3193X - Kobiałka Zenon': Timestamp('2025-03-07 09:20:00'),
 'Piotr  Świeczka WZ568JA': Timestamp('2025-03-07 09:30:00'),
 'Tadeusz Malinowski WT5728E 719': Timestamp('2025-03-07 09:40:00'),
 'WG3122L Roman Gołędowski': Timestamp('2025-03-07 09:50:00'),
 'Tadeusz Podłog WT86086': Timestamp('2025-03-07 10:00:00'),
 'Oleksii Storchak WR835GX': Timestamp('2025-03-07 10:10:00'),
 'WG4986J kierowca Igor Isak': Timestamp('2025-03-07 10:20:00'),
 'ES TRANS Olek Przeniczny WPI 4444F': Timestamp('2025-03-07 10:30:00'),
 'Konrad Chomiuk WG4625L': Timestamp('2025-03-07 10:40:00'),
 'Erwin Pilarski WJ1281H': Timestamp('2025-03-07 10:50:00'),
 'Wojtek Rosiński   Man WGM 8XF3': Timestamp('2025-03-07 11:00:00'),
 'Olech Ivasenko     WG6635L': Timestamp('2025-03-07 11:10:00'),
 'Ilin Maksim Mercedes WD 1727U': Timestamp('2025-03-07 11:20:00'),
 'Mibet WWL 2800P Rusłan Hlotov': Timestamp('2025-03-07 11:30:00'),
 'Robert Henczel Mercedes WD4163T': Timestamp('2025-03-07 11:40:00'),
 'Mateusz Kobierski MAN TGS 35.260 WG1824L': Timestamp('2025-03-07 11:50:00'),
 'Vitalii Ushakou MAN CWL00829': Timestamp('2025-03-07 12:00:00'),
 'Grzegorz Skowron WU8890H': Timestamp('2025-03-07 12:10:00'),
 'Igor Hovorukha MAN TGS 32.400 WG8255K': Timestamp('2025-03-07 12:20:00'),
 'Kosior': Timestamp('2025-03-07 12:30:00')}

In [39]:
# list(df_driver_list['person'])

In [166]:
df=df_full_day.copy()

In [167]:
# executor_availability = {executor str: timestep d.Timedelta, ...}
# executor_availability = driver_dict
executor_availability = {}
# Добавление столбцов для исполнителей
df['Executors'] = None
df['Free Executors'] = None
df['Missing Executors'] = None

# Отслеживание свободных исполнителей
# free_executors = free_exict_list
free_executors = []
# free_executors = list(df_driver_list['person'])

# Текущие назначения исполнителей к заказам в виде словаря {order: (executor, order)}
current_assignments = {}

# Словарь для отслеживания периодов работы BRAK исполнителей
brak_intervals = {}

# Счетчик для недостатка исполнителей
brak_counter = 1

used_executors=[]
df['First'] = ''

In [168]:
# Для каждого временного шага
for current_time in df.index:
    start_executers = []
    # Обновляем список доступных исполнителей, учитывая начальное время готовности
    for executor, available_time in executor_availability.items():
        if available_time <= current_time and executor not in free_executors:
            if all(executor != assigned_exec for assigned_exec, _ in current_assignments.values()):
                    # free_executors.insert(0, executor)
                    # free_executors.append(executor)
                    start_executers.append(executor)
                
    
    
    # Сначала освобождаем исполнителей от завершенных заданий
    completed_orders = [order for order, (executor, _) in current_assignments.items() if df[order].loc[current_time] == 0]
    for order in completed_orders:
        free_executor, _ = current_assignments.pop(order)
        # if not free_executor.startswith('BRAK_KEROWCA'):
        if df[order].shift(1).loc[current_time] == 'z':
            free_executors.insert(0, free_executor)
            while free_executor in used_executors:
                used_executors.remove(free_executor)
        else:
            free_executors.append(free_executor)
        # else:
        #     # Заканчиваем интервал работы текущего BRAK исполнителя
        #     brak_intervals[free_executor]['end'] = current_time


    # # сортировка исполнителей 
    # inserted = False

    # if free_executors:
    #     for i, execu in enumerate(free_executors):
    #         if execu in used_executors:
    #             free_executors = free_executors[:i]+ start_executers + free_executors[i:]
    #             inserted = True
    #             break
    #     if not inserted:
    #         free_executors = free_executors + start_executers
    # else:             
    #     free_executors = start_executers + free_executors  
    
    # Обрабатываем существующие заказы с исполнителями BRAKx
    # for order, (executor, assigned_order) in current_assignments.items():
    #     if executor.startswith('BRAK_KEROWCA') and free_executors:
    #         new_executor = free_executors.pop(0)
    #         current_assignments[order] = (new_executor, assigned_order)
    #         df.at[current_time, 'First'] = new_executor + f"::{str(df.at[current_time, 'First'])}"
    #         # Заканчиваем интервал работы текущего BRAK исполнителя
    #         brak_intervals[executor]['end'] = current_time

    
    # Назначение исполнителей на начинающиеся заказы
    missing_executors = []
    for order in df.columns[:-4]:  # исключаем столбцы 'Executors', 'Free Executors' и 'Missing Executors'
        if df[order].loc[current_time] != 0 and order not in current_assignments:
            if free_executors:
                current_executor = free_executors.pop(0)
            else:
                # Если нет свободных исполнителей, создаем нового с именем BRAKx
                current_executor = f'BRAK_KEROWCA{brak_counter}'
                brak_counter += 1
                missing_executors.append((current_executor, order))
                # Начинаем интервал работы нового BRAK исполнителя
                brak_intervals[current_executor] = {'start': current_time, 'end': None}

            if current_executor not in used_executors:
                df.at[current_time, 'First'] = current_executor + f"::{str(df.at[current_time, 'First'])}"
            used_executors.append(current_executor)
            
            current_assignments[order] = (current_executor, order)

    # Обновляем недостающих исполнителей в столбце Missing Executors
    missing_executors = [
        (executor, order) for order, (executor, _) in current_assignments.items()
        if executor.startswith('BRAK_KEROWCA')
    ]
    
    # Запись исполнителей и выполняемых заказов в формате (Executor, Order)
    # executor_assignments = ', '.join(f"({executor}, {assigned_order})" for assigned_order, (executor, order) in current_assignments.items())
    str_current_assignment = str([(executor, assigned_order) for assigned_order, (executor, order) in current_assignments.items()])
    df.at[current_time, 'Executors'] = str_current_assignment

    # Запись списка свободных исполнителей
    str_free_executors = str(free_executors)
    df.at[current_time, 'Free Executors'] = str_free_executors
    
    # Запись списка недостающих исполнителей в новый столбец
    # missing_assignments = ', '.join(f"({executor}, {assigned_order})" for executor, assigned_order in missing_executors)
    missing_executors = str(missing_executors)
    df.at[current_time, 'Missing Executors'] = missing_executors

# Завершаем все интервалы, где end остался None
for brak_key, interval in brak_intervals.items():
    if interval['end'] is None:
        brak_intervals[brak_key]['end'] = df.index[-1]

# Просмотр результата
print("Intervалы недостающих исполнителей:")
for brak, interval in brak_intervals.items():
    print(f"{brak}: {interval['start']} - {interval['end']}")

Intervалы недостающих исполнителей:
BRAK_KEROWCA1: 2025-03-07 07:30:00 - 2025-03-07 23:00:00
BRAK_KEROWCA2: 2025-03-07 07:54:00 - 2025-03-07 23:00:00
BRAK_KEROWCA3: 2025-03-07 08:18:00 - 2025-03-07 23:00:00
BRAK_KEROWCA4: 2025-03-07 08:30:00 - 2025-03-07 23:00:00
BRAK_KEROWCA5: 2025-03-07 08:42:00 - 2025-03-07 23:00:00
BRAK_KEROWCA6: 2025-03-07 08:54:00 - 2025-03-07 23:00:00
BRAK_KEROWCA7: 2025-03-07 09:18:00 - 2025-03-07 23:00:00
BRAK_KEROWCA8: 2025-03-07 09:42:00 - 2025-03-07 23:00:00
BRAK_KEROWCA9: 2025-03-07 13:06:00 - 2025-03-07 23:00:00
BRAK_KEROWCA10: 2025-03-07 13:30:00 - 2025-03-07 23:00:00
BRAK_KEROWCA11: 2025-03-07 14:30:00 - 2025-03-07 23:00:00
BRAK_KEROWCA12: 2025-03-07 14:30:00 - 2025-03-07 23:00:00
BRAK_KEROWCA13: 2025-03-07 14:30:00 - 2025-03-07 23:00:00
BRAK_KEROWCA14: 2025-03-07 15:34:00 - 2025-03-07 23:00:00
BRAK_KEROWCA15: 2025-03-07 15:34:00 - 2025-03-07 23:00:00
BRAK_KEROWCA16: 2025-03-07 15:34:00 - 2025-03-07 23:00:00
BRAK_KEROWCA17: 2025-03-07 15:34:00 - 2025-03-07 23:00:00
BRAK_KEROWCA18: 2025-03-07 15:34:00 - 2025-03-07 23:00:00

In [169]:
df[df[1]!=0]

,1,2,3,4,5,6,7,8,9,10,...,55,56,57,58,59,60,Executors,Free Executors,Missing Executors,First
2025-03-07 07:30:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1)]",[],"[('BRAK_KEROWCA1', 1)]",BRAK_KEROWCA1::
2025-03-07 07:31:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1)]",[],"[('BRAK_KEROWCA1', 1)]",
2025-03-07 07:32:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1)]",[],"[('BRAK_KEROWCA1', 1)]",
2025-03-07 07:33:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1)]",[],"[('BRAK_KEROWCA1', 1)]",
2025-03-07 07:34:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1)]",[],"[('BRAK_KEROWCA1', 1)]",
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-07 08:50:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",[],"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",
2025-03-07 08:51:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",[],"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",
2025-03-07 08:52:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",[],"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",
2025-03-07 08:53:00,b,b,b,b,b,0,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",[],"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",
2025-03-07 08:54:00,b,b,b,b,b,b,0,0,0,0,...,0,0,0,0,0,0,"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",[],"[('BRAK_KEROWCA1', 1), ('BRAK_KEROWCA2', 2), (...",BRAK_KEROWCA6::

In [170]:
df.iloc[150:200]

,1,2,3,4,5,6,7,8,9,10,...,55,56,57,58,59,60,Executors,Free Executors,Missing Executors,First
2025-03-07 06:30:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:31:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:32:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:33:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:34:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:35:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:36:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:37:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:38:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:39:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:40:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:41:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:42:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:43:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:44:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:45:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:46:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:47:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:48:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:49:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:50:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:51:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:52:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:53:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:54:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:55:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:01:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:02:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:03:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:04:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:05:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:06:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:07:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:08:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:09:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:10:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:11:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:12:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:13:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:14:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:16:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:17:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:18:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 07:19:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],

In [171]:
df.iloc[100:150]

,1,2,3,4,5,6,7,8,9,10,...,55,56,57,58,59,60,Executors,Free Executors,Missing Executors,First
2025-03-07 05:40:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:41:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:42:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:43:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:44:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:45:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:46:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:47:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:48:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:49:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:50:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:51:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:52:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:53:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:54:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:55:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:01:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:02:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:03:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:04:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:05:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:06:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:07:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:08:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:09:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:10:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:11:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:12:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:13:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:14:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:16:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:17:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:18:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:19:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:20:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:21:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:22:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:23:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:24:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:25:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:26:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:27:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:28:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:29:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],

In [172]:
df.replace('[]',np.nan, inplace=True)

In [173]:
df.replace('',np.nan, inplace=True)

In [174]:
list_starts = df["First"][df["First"].notna()]
list_starts

2025-03-07 07:30:00                                      BRAK_KEROWCA1::
2025-03-07 07:54:00                                      BRAK_KEROWCA2::
2025-03-07 08:18:00                                      BRAK_KEROWCA3::
2025-03-07 08:30:00                                      BRAK_KEROWCA4::
2025-03-07 08:42:00                                      BRAK_KEROWCA5::
2025-03-07 08:54:00                                      BRAK_KEROWCA6::
2025-03-07 09:18:00                                      BRAK_KEROWCA7::
2025-03-07 09:42:00                                      BRAK_KEROWCA8::
2025-03-07 13:06:00                                      BRAK_KEROWCA9::
2025-03-07 13:30:00                                     BRAK_KEROWCA10::
2025-03-07 14:30:00     BRAK_KEROWCA13::BRAK_KEROWCA12::BRAK_KEROWCA11::
2025-03-07 15:34:00    BRAK_KEROWCA18::BRAK_KEROWCA17::BRAK_KEROWCA16...
Name: First, dtype: object

In [175]:
list_starts = list_starts.str.split("::")

In [176]:
list_starts

2025-03-07 07:30:00                                    [BRAK_KEROWCA1, ]
2025-03-07 07:54:00                                    [BRAK_KEROWCA2, ]
2025-03-07 08:18:00                                    [BRAK_KEROWCA3, ]
2025-03-07 08:30:00                                    [BRAK_KEROWCA4, ]
2025-03-07 08:42:00                                    [BRAK_KEROWCA5, ]
2025-03-07 08:54:00                                    [BRAK_KEROWCA6, ]
2025-03-07 09:18:00                                    [BRAK_KEROWCA7, ]
2025-03-07 09:42:00                                    [BRAK_KEROWCA8, ]
2025-03-07 13:06:00                                    [BRAK_KEROWCA9, ]
2025-03-07 13:30:00                                   [BRAK_KEROWCA10, ]
2025-03-07 14:30:00    [BRAK_KEROWCA13, BRAK_KEROWCA12, BRAK_KEROWCA1...
2025-03-07 15:34:00    [BRAK_KEROWCA18, BRAK_KEROWCA17, BRAK_KEROWCA1...
Name: First, dtype: object

In [177]:
list_starts = list_starts.explode()

In [178]:
list_starts

2025-03-07 07:30:00     BRAK_KEROWCA1
2025-03-07 07:30:00
2025-03-07 07:54:00     BRAK_KEROWCA2
2025-03-07 07:54:00
2025-03-07 08:18:00     BRAK_KEROWCA3
2025-03-07 08:18:00
2025-03-07 08:30:00     BRAK_KEROWCA4
2025-03-07 08:30:00
2025-03-07 08:42:00     BRAK_KEROWCA5
2025-03-07 08:42:00
2025-03-07 08:54:00     BRAK_KEROWCA6
2025-03-07 08:54:00
2025-03-07 09:18:00     BRAK_KEROWCA7
2025-03-07 09:18:00
2025-03-07 09:42:00     BRAK_KEROWCA8
2025-03-07 09:42:00
2025-03-07 13:06:00     BRAK_KEROWCA9
2025-03-07 13:06:00
2025-03-07 13:30:00    BRAK_KEROWCA10
2025-03-07 13:30:00
2025-03-07 14:30:00    BRAK_KEROWCA13
2025-03-07 14:30:00    BRAK_KEROWCA12
2025-03-07 14:30:00    BRAK_KEROWCA11
2025-03-07 14:30:00
2025-03-07 15:34:00    BRAK_KEROWCA18
2025-03-07 15:34:00    BRAK_KEROWCA17
2025-03-07 15:34:00    BRAK_KEROWCA16
2025-03-07 15:34:00    BRAK_KEROWCA15
2025-03-07 15:34:00    BRAK_KEROWCA14
2025-03-07 15:34:00
Name: First, dtype: object

In [179]:
list_starts.replace('',np.nan, inplace=True)

In [180]:
list_starts = list_starts.dropna()

In [181]:
list_starts

2025-03-07 07:30:00     BRAK_KEROWCA1
2025-03-07 07:54:00     BRAK_KEROWCA2
2025-03-07 08:18:00     BRAK_KEROWCA3
2025-03-07 08:30:00     BRAK_KEROWCA4
2025-03-07 08:42:00     BRAK_KEROWCA5
2025-03-07 08:54:00     BRAK_KEROWCA6
2025-03-07 09:18:00     BRAK_KEROWCA7
2025-03-07 09:42:00     BRAK_KEROWCA8
2025-03-07 13:06:00     BRAK_KEROWCA9
2025-03-07 13:30:00    BRAK_KEROWCA10
2025-03-07 14:30:00    BRAK_KEROWCA13
2025-03-07 14:30:00    BRAK_KEROWCA12
2025-03-07 14:30:00    BRAK_KEROWCA11
2025-03-07 15:34:00    BRAK_KEROWCA18
2025-03-07 15:34:00    BRAK_KEROWCA17
2025-03-07 15:34:00    BRAK_KEROWCA16
2025-03-07 15:34:00    BRAK_KEROWCA15
2025-03-07 15:34:00    BRAK_KEROWCA14
Name: First, dtype: object

In [182]:
list_starts= list_starts.reset_index()

In [183]:
list_starts

                 index           First
0  2025-03-07 07:30:00   BRAK_KEROWCA1
1  2025-03-07 07:54:00   BRAK_KEROWCA2
2  2025-03-07 08:18:00   BRAK_KEROWCA3
3  2025-03-07 08:30:00   BRAK_KEROWCA4
4  2025-03-07 08:42:00   BRAK_KEROWCA5
5  2025-03-07 08:54:00   BRAK_KEROWCA6
6  2025-03-07 09:18:00   BRAK_KEROWCA7
7  2025-03-07 09:42:00   BRAK_KEROWCA8
8  2025-03-07 13:06:00   BRAK_KEROWCA9
9  2025-03-07 13:30:00  BRAK_KEROWCA10
10 2025-03-07 14:30:00  BRAK_KEROWCA13
11 2025-03-07 14:30:00  BRAK_KEROWCA12
12 2025-03-07 14:30:00  BRAK_KEROWCA11
13 2025-03-07 15:34:00  BRAK_KEROWCA18
14 2025-03-07 15:34:00  BRAK_KEROWCA17
15 2025-03-07 15:34:00  BRAK_KEROWCA16
16 2025-03-07 15:34:00  BRAK_KEROWCA15
17 2025-03-07 15:34:00  BRAK_KEROWCA14

In [184]:
list_starts.rename(columns={'index':'time', 'First':'person'}, inplace=True)

In [185]:
list_starts

                  time          person
0  2025-03-07 07:30:00   BRAK_KEROWCA1
1  2025-03-07 07:54:00   BRAK_KEROWCA2
2  2025-03-07 08:18:00   BRAK_KEROWCA3
3  2025-03-07 08:30:00   BRAK_KEROWCA4
4  2025-03-07 08:42:00   BRAK_KEROWCA5
5  2025-03-07 08:54:00   BRAK_KEROWCA6
6  2025-03-07 09:18:00   BRAK_KEROWCA7
7  2025-03-07 09:42:00   BRAK_KEROWCA8
8  2025-03-07 13:06:00   BRAK_KEROWCA9
9  2025-03-07 13:30:00  BRAK_KEROWCA10
10 2025-03-07 14:30:00  BRAK_KEROWCA13
11 2025-03-07 14:30:00  BRAK_KEROWCA12
12 2025-03-07 14:30:00  BRAK_KEROWCA11
13 2025-03-07 15:34:00  BRAK_KEROWCA18
14 2025-03-07 15:34:00  BRAK_KEROWCA17
15 2025-03-07 15:34:00  BRAK_KEROWCA16
16 2025-03-07 15:34:00  BRAK_KEROWCA15
17 2025-03-07 15:34:00  BRAK_KEROWCA14

In [186]:
def str_to_list(s):
    return eval(s)

In [187]:
df_executors =  df['Executors'].dropna()

In [188]:
df_executors  = df_executors.apply(str_to_list)

In [189]:
expanded_rows = df_executors.explode()

In [190]:
expanded_rows = expanded_rows.drop_duplicates()

In [191]:
expanded_df = pd.DataFrame(expanded_rows.tolist(), columns=['person', 'N% kursów'])

In [192]:
expanded_df

            person  N% kursów
0    BRAK_KEROWCA1          1
1    BRAK_KEROWCA2          2
2    BRAK_KEROWCA3          3
3    BRAK_KEROWCA4          4
4    BRAK_KEROWCA5          5
5    BRAK_KEROWCA6          6
6    BRAK_KEROWCA1          7
7    BRAK_KEROWCA7          8
8    BRAK_KEROWCA2          9
9    BRAK_KEROWCA8         10
10   BRAK_KEROWCA3         11
11   BRAK_KEROWCA4         12
12   BRAK_KEROWCA5         13
13   BRAK_KEROWCA6         14
14   BRAK_KEROWCA1         15
15   BRAK_KEROWCA7         16
16   BRAK_KEROWCA2         17
17   BRAK_KEROWCA8         18
18   BRAK_KEROWCA3         19
19   BRAK_KEROWCA4         20
20   BRAK_KEROWCA5         21
21   BRAK_KEROWCA6         22
22   BRAK_KEROWCA1         23
23   BRAK_KEROWCA7         24
24   BRAK_KEROWCA2         25
25   BRAK_KEROWCA8         26
26   BRAK_KEROWCA3         27
27   BRAK_KEROWCA9         28
28   BRAK_KEROWCA4         29
29   BRAK_KEROWCA5         30
30  BRAK_KEROWCA10         31
31   BRAK_KEROWCA6         32
32   BRAK_KEROWCA1         33
33   BRAK_KEROWCA7         34
34   BRAK_KEROWCA2         35
35   BRAK_KEROWCA8         36
36   BRAK_KEROWCA3         37
37  BRAK_KEROWCA11         38
38  BRAK_KEROWCA12         39
39  BRAK_KEROWCA13         40
40   BRAK_KEROWCA9         41
41   BRAK_KEROWCA4         42
42   BRAK_KEROWCA5         43
43  BRAK_KEROWCA10         44
44   BRAK_KEROWCA6         45
45   BRAK_KEROWCA1         46
46  BRAK_KEROWCA14         47
47  BRAK_KEROWCA15         48
48  BRAK_KEROWCA16         49
49  BRAK_KEROWCA17         50
50  BRAK_KEROWCA18         51
51   BRAK_KEROWCA7         52
52   BRAK_KEROWCA2         53
53   BRAK_KEROWCA9         54
54   BRAK_KEROWCA4         55
55   BRAK_KEROWCA5         56
56  BRAK_KEROWCA10         57
57   BRAK_KEROWCA8         58
58   BRAK_KEROWCA3         59
59  BRAK_KEROWCA11         60

In [193]:
expanded_df_rezult = expanded_df.groupby('person')['N% kursów'].apply(list).reset_index()

In [194]:
expanded_df_rezult

            person                N% kursów
0    BRAK_KEROWCA1   [1, 7, 15, 23, 33, 46]
1   BRAK_KEROWCA10             [31, 44, 57]
2   BRAK_KEROWCA11                 [38, 60]
3   BRAK_KEROWCA12                     [39]
4   BRAK_KEROWCA13                     [40]
5   BRAK_KEROWCA14                     [47]
6   BRAK_KEROWCA15                     [48]
7   BRAK_KEROWCA16                     [49]
8   BRAK_KEROWCA17                     [50]
9   BRAK_KEROWCA18                     [51]
10   BRAK_KEROWCA2   [2, 9, 17, 25, 35, 53]
11   BRAK_KEROWCA3  [3, 11, 19, 27, 37, 59]
12   BRAK_KEROWCA4  [4, 12, 20, 29, 42, 55]
13   BRAK_KEROWCA5  [5, 13, 21, 30, 43, 56]
14   BRAK_KEROWCA6      [6, 14, 22, 32, 45]
15   BRAK_KEROWCA7      [8, 16, 24, 34, 52]
16   BRAK_KEROWCA8     [10, 18, 26, 36, 58]
17   BRAK_KEROWCA9             [28, 41, 54]

In [195]:
result_df_end = pd.merge(list_starts, expanded_df_rezult, on='person', how='left')

In [196]:
result_df_end = result_df_end.drop_duplicates(subset='person')

In [197]:
result_df_end['N% kursów_first'] = result_df_end["N% kursów"].apply(lambda x: x[0])

In [198]:
# Сортировка
result_df_end.sort_values(by=["time", "N% kursów_first"], inplace=True)

In [199]:
result_df_end.drop(columns='N% kursów_first', inplace=True)

In [200]:
result_df_end

                  time          person                N% kursów
0  2025-03-07 07:30:00   BRAK_KEROWCA1   [1, 7, 15, 23, 33, 46]
1  2025-03-07 07:54:00   BRAK_KEROWCA2   [2, 9, 17, 25, 35, 53]
2  2025-03-07 08:18:00   BRAK_KEROWCA3  [3, 11, 19, 27, 37, 59]
3  2025-03-07 08:30:00   BRAK_KEROWCA4  [4, 12, 20, 29, 42, 55]
4  2025-03-07 08:42:00   BRAK_KEROWCA5  [5, 13, 21, 30, 43, 56]
5  2025-03-07 08:54:00   BRAK_KEROWCA6      [6, 14, 22, 32, 45]
6  2025-03-07 09:18:00   BRAK_KEROWCA7      [8, 16, 24, 34, 52]
7  2025-03-07 09:42:00   BRAK_KEROWCA8     [10, 18, 26, 36, 58]
8  2025-03-07 13:06:00   BRAK_KEROWCA9             [28, 41, 54]
9  2025-03-07 13:30:00  BRAK_KEROWCA10             [31, 44, 57]
12 2025-03-07 14:30:00  BRAK_KEROWCA11                 [38, 60]
11 2025-03-07 14:30:00  BRAK_KEROWCA12                     [39]
10 2025-03-07 14:30:00  BRAK_KEROWCA13                     [40]
17 2025-03-07 15:34:00  BRAK_KEROWCA14                     [47]
16 2025-03-07 15:34:00  BRAK_KEROWCA15                     [48]
15 2025-03-07 15:34:00  BRAK_KEROWCA16                     [49]
14 2025-03-07 15:34:00  BRAK_KEROWCA17                     [50]
13 2025-03-07 15:34:00  BRAK_KEROWCA18                     [51]

In [161]:
result_df_end['time'] = result_df_end['time'].apply(lambda x: x.strftime('%H:%M'))

In [162]:
result_df_end.rename({'person':'Kerowca','N% kursów':'kursy'}, axis=1, inplace=True)

In [163]:
result_df_end.reset_index(drop=True, inplace=True)

In [164]:
result_df_end.index=result_df_end.index+1

In [165]:
result_df_end

     time         Kerowca                                              kursy
1   07:30   BRAK_KEROWCA1  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
2   07:54   BRAK_KEROWCA2                                                [2]
3   08:18   BRAK_KEROWCA3                                                [3]
4   08:30   BRAK_KEROWCA4                                                [4]
5   08:42   BRAK_KEROWCA5                                                [5]
6   08:54   BRAK_KEROWCA6                                                [6]
7   09:06   BRAK_KEROWCA7                                                [7]
8   09:18   BRAK_KEROWCA8                                                [8]
9   09:30   BRAK_KEROWCA9                                                [9]
10  09:42  BRAK_KEROWCA10                                               [10]
11  09:54  BRAK_KEROWCA11                                               [11]
12  10:06  BRAK_KEROWCA12                                               [12]
13  10:18  BRAK_KEROWCA13                                               [13]
14  10:30  BRAK_KEROWCA14                                               [14]
15  10:42  BRAK_KEROWCA15                                               [15]
16  10:54  BRAK_KEROWCA16                                               [16]
17  11:06  BRAK_KEROWCA17                                               [17]
18  11:18  BRAK_KEROWCA18                                               [18]
19  11:30  BRAK_KEROWCA19                                               [19]
20  11:42  BRAK_KEROWCA20                                               [20]
21  11:54  BRAK_KEROWCA21                                               [21]
22  12:06  BRAK_KEROWCA22                                               [22]
23  12:18  BRAK_KEROWCA23                                               [23]
24  12:30  BRAK_KEROWCA24                                               [24]
25  12:42  BRAK_KEROWCA25                                               [25]
26  12:54  BRAK_KEROWCA26                                               [26]
27  13:00  BRAK_KEROWCA27                                               [27]
28  13:06  BRAK_KEROWCA28                                               [28]
29  13:18  BRAK_KEROWCA29                                           [29, 31]
30  13:24  BRAK_KEROWCA30                                               [30]
31  13:30  BRAK_KEROWCA31                                               [31]
32  13:48  BRAK_KEROWCA32                                               [32]
33  13:54  BRAK_KEROWCA33                                               [33]
34  14:12  BRAK_KEROWCA34                                               [34]
35  14:18  BRAK_KEROWCA35                                               [35]
36  14:30  BRAK_KEROWCA36                                               [36]
37  14:30  BRAK_KEROWCA37                                           [37, 46]
38  14:30  BRAK_KEROWCA38                                           [38, 47]
39  14:30  BRAK_KEROWCA39                                       [39, 48, 57]
40  14:30  BRAK_KEROWCA40                                   [40, 49, 58, 59]
41  14:36  BRAK_KEROWCA41                                           [41, 36]
42  14:42  BRAK_KEROWCA42                                           [42, 36]
43  15:00  BRAK_KEROWCA43                                           [43, 36]
44  15:06  BRAK_KEROWCA44                               [44, 36, 45, 46, 47]
45  15:24  BRAK_KEROWCA45                                               [45]
46  15:30  BRAK_KEROWCA46                                               [46]
47  15:34  BRAK_KEROWCA47                                               [47]
48  15:34  BRAK_KEROWCA48                                               [48]
49  15:34  BRAK_KEROWCA49                                               [49]
50  15:34  BRAK_KEROWCA50                                       [50, 56, 59]
51  15:34  BRAK_KEROWCA51                                       [51, 57, 60]
52  15:48  BRAK_KEROWCA52                                           [52, 47]
53  15:54  BRAK_KEROWCA53                                           [53, 47]
54  16:12  BRAK_KEROWCA54                                       [54, 47, 56]
55  16:18  BRAK_KEROWCA55                                           [55, 47]
56  16:38  BRAK_KEROWCA56                                               [56]
57  16:38  BRAK_KEROWCA57                                               [57]
58  16:38  BRAK_KEROWCA58                                               [58]
59  17:42  BRAK_KEROWCA59                                               [59]
60  17:42  BRAK_KEROWCA60                                               [60]

In [124]:
result_df_end['Kerowca'] = result_df_end['Kerowca'].apply(lambda x: f'<span style="font-weight: bold; color:rgb(255, 0, 0);">{str(x)}</span>' if x.startswith('BRAK_KIEROWCA') else x)

In [125]:
result_df_end

     time         Kerowca                                              kursy
1   07:30   BRAK_KEROWCA1  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
2   07:54   BRAK_KEROWCA2                                                [2]
3   08:18   BRAK_KEROWCA3                                                [3]
4   08:30   BRAK_KEROWCA4                                                [4]
5   08:42   BRAK_KEROWCA5                                                [5]
6   08:54   BRAK_KEROWCA6                                                [6]
7   09:06   BRAK_KEROWCA7                                                [7]
8   09:18   BRAK_KEROWCA8                                                [8]
9   09:30   BRAK_KEROWCA9                                                [9]
10  09:42  BRAK_KEROWCA10                                               [10]
11  09:54  BRAK_KEROWCA11                                               [11]
12  10:06  BRAK_KEROWCA12                                               [12]
13  10:18  BRAK_KEROWCA13                                               [13]
14  10:30  BRAK_KEROWCA14                                               [14]
15  10:42  BRAK_KEROWCA15                                               [15]
16  10:54  BRAK_KEROWCA16                                               [16]
17  11:06  BRAK_KEROWCA17                                               [17]
18  11:18  BRAK_KEROWCA18                                               [18]
19  11:30  BRAK_KEROWCA19                                               [19]
20  11:42  BRAK_KEROWCA20                                               [20]
21  11:54  BRAK_KEROWCA21                                               [21]
22  12:06  BRAK_KEROWCA22                                               [22]
23  12:18  BRAK_KEROWCA23                                               [23]
24  12:30  BRAK_KEROWCA24                                               [24]
25  12:42  BRAK_KEROWCA25                                               [25]
26  12:54  BRAK_KEROWCA26                                               [26]
27  13:00  BRAK_KEROWCA27                                               [27]
28  13:06  BRAK_KEROWCA28                                               [28]
29  13:18  BRAK_KEROWCA29                                           [29, 31]
30  13:24  BRAK_KEROWCA30                                               [30]
31  13:30  BRAK_KEROWCA31                                               [31]
32  13:48  BRAK_KEROWCA32                                               [32]
33  13:54  BRAK_KEROWCA33                                               [33]
34  14:12  BRAK_KEROWCA34                                               [34]
35  14:18  BRAK_KEROWCA35                                               [35]
36  14:30  BRAK_KEROWCA36                                               [36]
37  14:30  BRAK_KEROWCA37                                           [37, 46]
38  14:30  BRAK_KEROWCA38                                           [38, 47]
39  14:30  BRAK_KEROWCA39                                       [39, 48, 57]
40  14:30  BRAK_KEROWCA40                                   [40, 49, 58, 59]
41  14:36  BRAK_KEROWCA41                                           [41, 36]
42  14:42  BRAK_KEROWCA42                                           [42, 36]
43  15:00  BRAK_KEROWCA43                                           [43, 36]
44  15:06  BRAK_KEROWCA44                               [44, 36, 45, 46, 47]
45  15:24  BRAK_KEROWCA45                                               [45]
46  15:30  BRAK_KEROWCA46                                               [46]
47  15:34  BRAK_KEROWCA47                                               [47]
48  15:34  BRAK_KEROWCA48                                               [48]
49  15:34  BRAK_KEROWCA49                                               [49]
50  15:34  BRAK_KEROWCA50                                       [50, 56, 59]
51  15:34  BRAK_KEROWCA51                                       [51, 57, 60]
52  15:48  BRAK_KEROWCA52                                           [52, 47]
53  15:54  BRAK_KEROWCA53                                           [53, 47]
54  16:12  BRAK_KEROWCA54                                       [54, 47, 56]
55  16:18  BRAK_KEROWCA55                                           [55, 47]
56  16:38  BRAK_KEROWCA56                                               [56]
57  16:38  BRAK_KEROWCA57                                               [57]
58  16:38  BRAK_KEROWCA58                                               [58]
59  17:42  BRAK_KEROWCA59                                               [59]
60  17:42  BRAK_KEROWCA60                                               [60]

In [82]:
html_table = result_df_end.to_html(index=True,table_id="rozklad_kerowca",classes='rozklad_kerowca_tab', border=0, justify='center')

In [84]:
html_table

'<table class="dataframe rozklad_kerowca_tab" id="rozklad_kerowca">\n  <thead>\n    <tr style="text-align: center;">\n      <th></th>\n      <th>time</th>\n      <th>person</th>\n      <th>N% kursów</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>06:30</td>\n      <td>Kosior</td>\n      <td>[2, 3, 26]</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>06:30</td>\n      <td>MAN WJ2931G   Rusłan Skubi</td>\n      <td>[1, 4, 27]</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>07:00</td>\n      <td>BRAK1</td>\n      <td>[3]</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>07:24</td>\n      <td>BRAK2</td>\n      <td>[4]</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>10:30</td>\n      <td>Marcin Zapora WD4163T</td>\n      <td>[5, 28]</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>10:54</td>\n      <td>Piotr  Świeczka WZ568JA</td>\n      <td>[6, 29]</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>11:18</td>\n      <td>WG3122L Roman Gołędowski</td>\n      <td>[7, 30]</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>11:30</td>\n      <td>Tadeusz Malinowski WT5728E 719</td>\n      <td>[10, 32]</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>11:30</td>\n      <td>Tadeusz Podłog WT86086</td>\n      <td>[9, 36]</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>11:30</td>\n      <td>Oleksii Storchak WR835GX</td>\n      <td>[8, 31]</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>11:42</td>\n      <td>WG4986J kierowca Igor Isak</td>\n      <td>[11, 33]</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>11:54</td>\n      <td>Tomasz Kryszak WT1926G do godz. 16:00</td>\n      <td>[12, 34]</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>12:06</td>\n      <td>ES TRANS Olek Przeniczny WPI 4444F</td>\n      <td>[13, 35]</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>12:30</td>\n      <td>Konrad Chomiuk WG4625L</td>\n      <td>[16]</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>12:30</td>\n      <td>Erwin Pilarski WJ1281H</td>\n      <td>[15]</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>12:30</td>\n      <td>Wojtek Rosiński   Man WGM 8XF3</td>\n      <td>[14, 37]</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>12:54</td>\n      <td>Olech Ivasenko     WG6635L</td>\n      <td>[18]</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>12:54</td>\n      <td>Ilin Maksim Mercedes WD 1727U</td>\n      <td>[17]</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>13:00</td>\n      <td>Mibet WWL 2800P Rusłan Hlotov</td>\n      <td>[19]</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>13:34</td>\n      <td>Vitalii Ushakou MAN CWL00829</td>\n      <td>[20]</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>14:30</td>\n      <td>WZ3193X - Kobiałka Zenon</td>\n      <td>[25]</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>14:30</td>\n      <td>Robert Henczel Mercedes WD4163T</td>\n      <td>[24]</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>14:30</td>\n      <td>Mateusz Kobierski MAN TGS 35.260 WG1824L</td>\n      <td>[23]</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>14:30</td>\n      <td>Grzegorz Skowron WU8890H</td>\n      <td>[22]</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>14:30</td>\n      <td>Igor Hovorukha MAN TGS 32.400 WG8255K</td>\n      <td>[21]</td>\n    </tr>\n  </tbody>\n</table>'

In [76]:
# free_executors = []
free_executors = list(df_driver_list['person'])
current_assignments = {}
used_executors=[]
brak_counter = 1
df['First'] = ''

In [77]:
for current_time in df.index:
    # Сначала освобождаем исполнителей от завершенных заданий
    completed_orders = [order for order, (executor, assigned_order) in current_assignments.items() if df[order].loc[current_time] == 0]
    for order in completed_orders:
        free_executor, _ = current_assignments.pop(order)
        if df[order].shift(1).loc[current_time] == 'z':
            free_executors.insert(0, free_executor)
        else:
            free_executors.append(free_executor)
    
    # Назначение исполнителей на начинающиеся заказы
    missing_executors = []
    for order in df.columns[:-4]:  # исключаем столбцы 'Executors', 'Free Executors' и 'Missing Executors'
        if df[order].loc[current_time] != 0 and order not in current_assignments:
            if free_executors:
                current_executor = free_executors.pop(0)
            else:
                # Если нет свободных исполнителей, создаем нового с именем BRAKx
                current_executor = f'BRAK{brak_counter}'
                brak_counter += 1
                missing_executors.append((current_executor, order))
                
            if current_executor not in used_executors:
                df.at[current_time, 'First'] = current_executor + f":: {str(df.at[current_time, 'First'])}"
            used_executors.append(current_executor)

            current_assignments[order] = (current_executor, order)
    
    # Запись исполнителей и выполняемых заказов в формате (Executor, Order)
    # executor_assignments = ', '.join(f"({executor}, {assigned_order})" for assigned_order, (executor, order) in current_assignments.items())
    str_current_assignment = str([(executor, assigned_order) for assigned_order, (executor, order) in current_assignments.items()])
    df.at[current_time, 'Executors'] = str_current_assignment

    # Запись списка свободных исполнителей
    str_free_executors = str(free_executors)
    df.at[current_time, 'Free Executors'] = str_free_executors
    
    # Запись списка недостающих исполнителей в новый столбец
    # missing_assignments = ', '.join(f"({executor}, {assigned_order})" for executor, assigned_order in missing_executors)
    missing_executors = str(missing_executors)
    df.at[current_time, 'Missing Executors'] = missing_executors

In [78]:
used_executors

['Kosior',
 'MAN WJ2931G   Rusłan Skubi',
 'Marcin Zapora WD4163T',
 'WZ3193X - Kobiałka Zenon',
 'Kosior',
 'MAN WJ2931G   Rusłan Skubi',
 'Piotr  Świeczka WZ568JA',
 'Tadeusz Malinowski WT5728E 719',
 'WG3122L Roman Gołędowski',
 'Tadeusz Podłog WT86086',
 'Oleksii Storchak WR835GX',
 'WG4986J kierowca Igor Isak',
 'Tomasz Kryszak WT1926G do godz. 16:00',
 'ES TRANS Olek Przeniczny WPI 4444F',
 'Konrad Chomiuk WG4625L',
 'Erwin Pilarski WJ1281H',
 'Wojtek Rosiński   Man WGM 8XF3',
 'Olech Ivasenko     WG6635L',
 'Ilin Maksim Mercedes WD 1727U',
 'Mibet WWL 2800P Rusłan Hlotov',
 'Robert Henczel Mercedes WD4163T',
 'Mateusz Kobierski MAN TGS 35.260 WG1824L',
 'Vitalii Ushakou MAN CWL00829',
 'Grzegorz Skowron WU8890H',
 'Igor Hovorukha MAN TGS 32.400 WG8255K',
 'Marcin Zapora WD4163T',
 'WZ3193X - Kobiałka Zenon',
 'Kosior',
 'MAN WJ2931G   Rusłan Skubi',
 'Piotr  Świeczka WZ568JA',
 'Tadeusz Malinowski WT5728E 719',
 'Tadeusz Podłog WT86086',
 'Oleksii Storchak WR835GX',
 'WG4986J kierowca Igor Isak',
 'Tomasz Kryszak WT1926G do godz. 16:00',
 'WG3122L Roman Gołędowski',
 'ES TRANS Olek Przeniczny WPI 4444F']

In [79]:
df.replace('[]',np.nan, inplace=True)

/tmp/ipykernel_26418/3044711181.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('[]',np.nan, inplace=True)

In [80]:
# df['Executors'] = df['Executors'].drop_duplicates()

In [81]:
df.replace('',np.nan, inplace=True)

In [82]:
df

,1,2,3,4,5,6,7,8,9,10,...,32,33,34,35,36,37,Executors,Free Executors,Missing Executors,First
2025-03-04 04:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:01:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:02:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:03:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:04:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-04 22:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 22:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 22:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 22:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 23:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN

In [83]:
list_starts = df["First"][df["First"].notna()]
list_starts

2025-03-04 06:30:00               MAN WJ2931G   Rusłan Skubi:: Kosior::
2025-03-04 07:00:00                             Marcin Zapora WD4163T::
2025-03-04 07:24:00                          WZ3193X - Kobiałka Zenon::
2025-03-04 11:18:00                           Piotr  Świeczka WZ568JA::
2025-03-04 11:30:00    Tadeusz Podłog WT86086:: WG3122L Roman Gołędow...
2025-03-04 11:42:00                          Oleksii Storchak WR835GX::
2025-03-04 11:54:00                        WG4986J kierowca Igor Isak::
2025-03-04 12:06:00             Tomasz Kryszak WT1926G do godz. 16:00::
2025-03-04 12:30:00    Erwin Pilarski WJ1281H:: Konrad Chomiuk WG4625...
2025-03-04 12:54:00    Olech Ivasenko     WG6635L:: Wojtek Rosiński  ...
2025-03-04 13:00:00                     Ilin Maksim Mercedes WD 1727U::
2025-03-04 13:34:00                     Mibet WWL 2800P Rusłan Hlotov::
2025-03-04 14:30:00    Igor Hovorukha MAN TGS 32.400 WG8255K:: Grzego...
Name: First, dtype: object

In [84]:
list_starts = list_starts.str.split("::")

In [85]:
list_starts = list_starts.explode()

In [86]:
list_starts.replace(' ',np.nan, inplace=True)

In [87]:
list_starts = list_starts.dropna()

In [88]:
list_starts

2025-03-04 06:30:00                   MAN WJ2931G   Rusłan Skubi
2025-03-04 06:30:00                                       Kosior
2025-03-04 07:00:00                        Marcin Zapora WD4163T
2025-03-04 07:24:00                     WZ3193X - Kobiałka Zenon
2025-03-04 11:18:00                      Piotr  Świeczka WZ568JA
2025-03-04 11:30:00                       Tadeusz Podłog WT86086
2025-03-04 11:30:00                     WG3122L Roman Gołędowski
2025-03-04 11:30:00               Tadeusz Malinowski WT5728E 719
2025-03-04 11:42:00                     Oleksii Storchak WR835GX
2025-03-04 11:54:00                   WG4986J kierowca Igor Isak
2025-03-04 12:06:00        Tomasz Kryszak WT1926G do godz. 16:00
2025-03-04 12:30:00                       Erwin Pilarski WJ1281H
2025-03-04 12:30:00                       Konrad Chomiuk WG4625L
2025-03-04 12:30:00           ES TRANS Olek Przeniczny WPI 4444F
2025-03-04 12:54:00                   Olech Ivasenko     WG6635L
2025-03-04 12:54:00               Wojtek Rosiński   Man WGM 8XF3
2025-03-04 13:00:00                Ilin Maksim Mercedes WD 1727U
2025-03-04 13:34:00                Mibet WWL 2800P Rusłan Hlotov
2025-03-04 14:30:00        Igor Hovorukha MAN TGS 32.400 WG8255K
2025-03-04 14:30:00                     Grzegorz Skowron WU8890H
2025-03-04 14:30:00                 Vitalii Ushakou MAN CWL00829
2025-03-04 14:30:00     Mateusz Kobierski MAN TGS 35.260 WG1824L
2025-03-04 14:30:00              Robert Henczel Mercedes WD4163T
Name: First, dtype: object