In [1]:
%run static_forms.py
%config Completer.use_jedi = False

2025-03-06 08:17:58,479 - INFO - REZULT_____________________________________________________
2025-03-06 08:17:58,489 - INFO - REZULT_____________________________________________________

In [2]:
%who

DataFrame	 Driver	 Order	 Series	 Settings	 alt	 count_graph	 cr	 data_sql
date_of_request	 datetime	 db_lock	 df_driver	 df_for_driver_glob	 df_orders	 exp	 forecast_driver	 get_list_construction_driver
get_list_construction_place	 get_newest_list_beton_or_lista	 inf	 inspect	 io	 lg	 logging	 np	 pd
pprint	 px	 re	 rng	 rozklad_curs	 text_sql_request	 threading

In [3]:
df_orders

[{'name': 'Park Skandynawia, etap E10, E1...',
  'meter': 180.0,
  'time': datetime.time(8, 0),
  'start_time': datetime.datetime(2025, 3, 7, 7, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 16, 18),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 7, 30),
   datetime.datetime(2025, 3, 7, 7, 54),
   datetime.datetime(2025, 3, 7, 8, 18),
   datetime.datetime(2025, 3, 7, 8, 42),
   datetime.datetime(2025, 3, 7, 9, 6),
   datetime.datetime(2025, 3, 7, 9, 30),
   datetime.datetime(2025, 3, 7, 9, 54),
   datetime.datetime(2025, 3, 7, 10, 18),
   datetime.datetime(2025, 3, 7, 10, 42),
   datetime.datetime(2025, 3, 7, 11, 6),
   datetime.datetime(2025, 3, 7, 11, 30),
   datetime.datetime(2025, 3, 7, 11, 54),
   datetime.datetime(2025, 3, 7, 12, 18),
   datetime.datetime(2025, 3, 7, 12, 42),
   datetime.datetime(2025, 3, 7, 13, 6),
   datetime.datetime(2025, 3, 7, 13, 30),
   datetime.datetime(2025, 3, 7, 13, 54),
   datetime.datetime(2025, 3, 7, 14, 18),
   datetime.datetime(2025, 3, 7, 14, 42),
   datetime.datetime(2025, 3, 7, 15, 6),
   datetime.datetime(2025, 3, 7, 15, 30),
   datetime.datetime(2025, 3, 7, 15, 54),
   datetime.datetime(2025, 3, 7, 16, 18)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   8.0,
   4.0],
  'pompa_dzwig': True,
  'reszta': [172.0,
   164.0,
   156.0,
   148.0,
   140.0,
   132.0,
   124.0,
   116.0,
   108.0,
   100.0,
   92.0,
   84.0,
   76.0,
   68.0,
   60.0,
   52.0,
   44.0,
   36.0,
   28.0,
   20.0,
   12.0,
   4.0,
   0.0],
  'date_order': '07.03.2025'},
 {'name': 'Rosy 41lb...',
  'meter': 27.0,
  'time': datetime.time(12, 0),
  'start_time': datetime.datetime(2025, 3, 7, 11, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 12, 42),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 11, 30),
   datetime.datetime(2025, 3, 7, 11, 54),
   datetime.datetime(2025, 3, 7, 12, 18),
   datetime.datetime(2025, 3, 7, 12, 42)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 3.0],
  'pompa_dzwig': True,
  'reszta': [19.0, 11.0, 3.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Mangalia 2 Warszawa...',
  'meter': 72.0,
  'time': datetime.time(13, 30),
  'start_time': datetime.datetime(2025, 3, 7, 13, 0),
  'finish_time': datetime.datetime(2025, 3, 7, 16, 12),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 13, 0),
   datetime.datetime(2025, 3, 7, 13, 24),
   datetime.datetime(2025, 3, 7, 13, 48),
   datetime.datetime(2025, 3, 7, 14, 12),
   datetime.datetime(2025, 3, 7, 14, 36),
   datetime.datetime(2025, 3, 7, 15, 0),
   datetime.datetime(2025, 3, 7, 15, 24),
   datetime.datetime(2025, 3, 7, 15, 48),
   datetime.datetime(2025, 3, 7, 16, 12)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0],
  'pompa_dzwig': True,
  'reszta': [64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'ESY , ul. Cybernetyki 7...',
  'meter': 16.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 15, 34),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Mangalia 2 Warszawa...',
  'meter': 16.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 15, 34),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'FLORESY , ul. Cybernetyki 7...',
  'meter': 24.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 16, 38),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34),
   datetime.datetime(2025, 3, 7, 16, 38)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [16.0, 8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Vena Prymasa Tysiąclecia 83...',
  'meter': 32.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 17, 42),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34),
   datetime.datetime(2025, 3, 7, 16, 38),
   datetime.datetime(2025, 3, 7, 17, 42)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [24.0, 16.0, 8.0, 0.0],
  'date_order': '07.03.2025'},
 {'name': 'Warszawa ul.Siennicka...',
  'meter': 32.0,
  'time': datetime.time(15, 0),
  'start_time': datetime.datetime(2025, 3, 7, 14, 30),
  'finish_time': datetime.datetime(2025, 3, 7, 17, 42),
  'list_of_loads': [datetime.datetime(2025, 3, 7, 14, 30),
   datetime.datetime(2025, 3, 7, 15, 34),
   datetime.datetime(2025, 3, 7, 16, 38),
   datetime.datetime(2025, 3, 7, 17, 42)],
  'wenz': '1',
  'it_is_zaprawa': False,
  'it_is_concret': True,
  'list_of_courses': [8.0, 8.0, 8.0, 8.0],
  'pompa_dzwig': False,
  'reszta': [24.0, 16.0, 8.0, 0.0],
  'date_order': '07.03.2025'}]

In [4]:
bud = DataFrame(df_orders)
bud

,name,meter,time,start_time,finish_time,list_of_loads,wenz,it_is_zaprawa,it_is_concret,list_of_courses,pompa_dzwig,reszta,date_order
0,"Park Skandynawia, etap E10, E1...",180.0,08:00:00,2025-03-07 07:30:00,2025-03-07 16:18:00,"[2025-03-07 07:30:00, 2025-03-07 07:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[172.0, 164.0, 156.0, 148.0, 140.0, 132.0, 124...",07.03.2025
1,Rosy 41lb...,27.0,12:00:00,2025-03-07 11:30:00,2025-03-07 12:42:00,"[2025-03-07 11:30:00, 2025-03-07 11:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 3.0]",True,"[19.0, 11.0, 3.0, 0.0]",07.03.2025
2,Mangalia 2 Warszawa...,72.0,13:30:00,2025-03-07 13:00:00,2025-03-07 16:12:00,"[2025-03-07 13:00:00, 2025-03-07 13:24:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]",True,"[64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0...",07.03.2025
3,"ESY , ul. Cybernetyki 7...",16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
4,Mangalia 2 Warszawa...,16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
5,"FLORESY , ul. Cybernetyki 7...",24.0,15:00:00,2025-03-07 14:30:00,2025-03-07 16:38:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0]",False,"[16.0, 8.0, 0.0]",07.03.2025
6,Vena Prymasa Tysiąclecia 83...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025
7,Warszawa ul.Siennicka...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025

In [5]:
bud_without_dry = bud[bud["it_is_zaprawa"] | bud["it_is_concret"]]
bud_without_dry

,name,meter,time,start_time,finish_time,list_of_loads,wenz,it_is_zaprawa,it_is_concret,list_of_courses,pompa_dzwig,reszta,date_order
0,"Park Skandynawia, etap E10, E1...",180.0,08:00:00,2025-03-07 07:30:00,2025-03-07 16:18:00,"[2025-03-07 07:30:00, 2025-03-07 07:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[172.0, 164.0, 156.0, 148.0, 140.0, 132.0, 124...",07.03.2025
1,Rosy 41lb...,27.0,12:00:00,2025-03-07 11:30:00,2025-03-07 12:42:00,"[2025-03-07 11:30:00, 2025-03-07 11:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 3.0]",True,"[19.0, 11.0, 3.0, 0.0]",07.03.2025
2,Mangalia 2 Warszawa...,72.0,13:30:00,2025-03-07 13:00:00,2025-03-07 16:12:00,"[2025-03-07 13:00:00, 2025-03-07 13:24:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]",True,"[64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0...",07.03.2025
3,"ESY , ul. Cybernetyki 7...",16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
4,Mangalia 2 Warszawa...,16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025
5,"FLORESY , ul. Cybernetyki 7...",24.0,15:00:00,2025-03-07 14:30:00,2025-03-07 16:38:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0]",False,"[16.0, 8.0, 0.0]",07.03.2025
6,Vena Prymasa Tysiąclecia 83...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025
7,Warszawa ul.Siennicka...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025

In [6]:
bud_without_dry["list_of_courses"].apply(lambda x: list(range(1, len(x) + 1)))

0    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
1                                         [1, 2, 3, 4]
2                          [1, 2, 3, 4, 5, 6, 7, 8, 9]
3                                               [1, 2]
4                                               [1, 2]
5                                            [1, 2, 3]
6                                         [1, 2, 3, 4]
7                                         [1, 2, 3, 4]
Name: list_of_courses, dtype: object

In [7]:
bud_without_dry["namber_cours"] = bud_without_dry["list_of_courses"].apply(lambda x: list(range(1, len(x) + 1))).values
bud_without_dry

,name,meter,time,start_time,finish_time,list_of_loads,wenz,it_is_zaprawa,it_is_concret,list_of_courses,pompa_dzwig,reszta,date_order,namber_cours
0,"Park Skandynawia, etap E10, E1...",180.0,08:00:00,2025-03-07 07:30:00,2025-03-07 16:18:00,"[2025-03-07 07:30:00, 2025-03-07 07:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, ...",True,"[172.0, 164.0, 156.0, 148.0, 140.0, 132.0, 124...",07.03.2025,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,Rosy 41lb...,27.0,12:00:00,2025-03-07 11:30:00,2025-03-07 12:42:00,"[2025-03-07 11:30:00, 2025-03-07 11:54:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 3.0]",True,"[19.0, 11.0, 3.0, 0.0]",07.03.2025,"[1, 2, 3, 4]"
2,Mangalia 2 Warszawa...,72.0,13:30:00,2025-03-07 13:00:00,2025-03-07 16:12:00,"[2025-03-07 13:00:00, 2025-03-07 13:24:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]",True,"[64.0, 56.0, 48.0, 40.0, 32.0, 24.0, 16.0, 8.0...",07.03.2025,"[1, 2, 3, 4, 5, 6, 7, 8, 9]"
3,"ESY , ul. Cybernetyki 7...",16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025,"[1, 2]"
4,Mangalia 2 Warszawa...,16.0,15:00:00,2025-03-07 14:30:00,2025-03-07 15:34:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00]",1,False,True,"[8.0, 8.0]",False,"[8.0, 0.0]",07.03.2025,"[1, 2]"
5,"FLORESY , ul. Cybernetyki 7...",24.0,15:00:00,2025-03-07 14:30:00,2025-03-07 16:38:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0]",False,"[16.0, 8.0, 0.0]",07.03.2025,"[1, 2, 3]"
6,Vena Prymasa Tysiąclecia 83...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025,"[1, 2, 3, 4]"
7,Warszawa ul.Siennicka...,32.0,15:00:00,2025-03-07 14:30:00,2025-03-07 17:42:00,"[2025-03-07 14:30:00, 2025-03-07 15:34:00, 202...",1,False,True,"[8.0, 8.0, 8.0, 8.0]",False,"[24.0, 16.0, 8.0, 0.0]",07.03.2025,"[1, 2, 3, 4]"

In [8]:
# rozklad_curs = bud_without_dry[['list_of_loads', 'list_of_courses', 'name','reszta', 'it_is_zaprawa','pompa_dzwig']]\
# .explode(['list_of_loads','list_of_courses','reszta']).sort_values('list_of_loads')
rozklad_curs = bud_without_dry[['list_of_loads', 'list_of_courses', 'name','reszta', 'wenz', 'it_is_zaprawa','pompa_dzwig', 'namber_cours']]\
.explode(['list_of_loads','list_of_courses','reszta', 'namber_cours'])
rozklad_curs
# список отгрузок отсортированых по

,list_of_loads,list_of_courses,name,reszta,wenz,it_is_zaprawa,pompa_dzwig,namber_cours
0,2025-03-07 07:30:00,8.0,"Park Skandynawia, etap E10, E1...",172.0,1,False,True,1
0,2025-03-07 07:54:00,8.0,"Park Skandynawia, etap E10, E1...",164.0,1,False,True,2
0,2025-03-07 08:18:00,8.0,"Park Skandynawia, etap E10, E1...",156.0,1,False,True,3
0,2025-03-07 08:42:00,8.0,"Park Skandynawia, etap E10, E1...",148.0,1,False,True,4
0,2025-03-07 09:06:00,8.0,"Park Skandynawia, etap E10, E1...",140.0,1,False,True,5
0,2025-03-07 09:30:00,8.0,"Park Skandynawia, etap E10, E1...",132.0,1,False,True,6
0,2025-03-07 09:54:00,8.0,"Park Skandynawia, etap E10, E1...",124.0,1,False,True,7
0,2025-03-07 10:18:00,8.0,"Park Skandynawia, etap E10, E1...",116.0,1,False,True,8
0,2025-03-07 10:42:00,8.0,"Park Skandynawia, etap E10, E1...",108.0,1,False,True,9
0,2025-03-07 11:06:00,8.0,"Park Skandynawia, etap E10, E1...",100.0,1,False,True,10
0,2025-03-07 11:30:00,8.0,"Park Skandynawia, etap E10, E1...",92.0,1,False,True,11
0,2025-03-07 11:54:00,8.0,"Park Skandynawia, etap E10, E1...",84.0,1,False,True,12
0,2025-03-07 12:18:00,8.0,"Park Skandynawia, etap E10, E1...",76.0,1,False,True,13
0,2025-03-07 12:42:00,8.0,"Park Skandynawia, etap E10, E1...",68.0,1,False,True,14
0,2025-03-07 13:06:00,8.0,"Park Skandynawia, etap E10, E1...",60.0,1,False,True,15
0,2025-03-07 13:30:00,8.0,"Park Skandynawia, etap E10, E1...",52.0,1,False,True,16
0,2025-03-07 13:54:00,8.0,"Park Skandynawia, etap E10, E1...",44.0,1,False,True,17
0,2025-03-07 14:18:00,8.0,"Park Skandynawia, etap E10, E1...",36.0,1,False,True,18
0,2025-03-07 14:42:00,8.0,"Park Skandynawia, etap E10, E1...",28.0,1,False,True,19
0,2025-03-07 15:06:00,8.0,"Park Skandynawia, etap E10, E1...",20.0,1,False,True,20
0,2025-03-07 15:30:00,8.0,"Park Skandynawia, etap E10, E1...",12.0,1,False,True,21
0,2025-03-07 15:54:00,8.0,"Park Skandynawia, etap E10, E1...",4.0,1,False,True,22
0,2025-03-07 16:18:00,4.0,"Park Skandynawia, etap E10, E1...",0.0,1,False,True,23
1,2025-03-07 11:30:00,8.0,Rosy 41lb...,19.0,1,False,True,1
1,2025-03-07 11:54:00,8.0,Rosy 41lb...,11.0,1,False,True,2
1,2025-03-07 12:18:00,8.0,Rosy 41lb...,3.0,1,False,True,3
1,2025-03-07 12:42:00,3.0,Rosy 41lb...,0.0,1,False,True,4
2,2025-03-07 13:00:00,8.0,Mangalia 2 Warszawa...,64.0,1,False,True,1
2,2025-03-07 13:24:00,8.0,Mangalia 2 Warszawa...,56.0,1,False,True,2
2,2025-03-07 13:48:00,8.0,Mangalia 2 Warszawa...,48.0,1,False,True,3
2,2025-03-07 14:12:00,8.0,Mangalia 2 Warszawa...,40.0,1,False,True,4
2,2025-03-07 14:36:00,8.0,Mangalia 2 Warszawa...,32.0,1,False,True,5
2,2025-03-07 15:00:00,8.0,Mangalia 2 Warszawa...,24.0,1,False,True,6
2,2025-03-07 15:24:00,8.0,Mangalia 2 Warszawa...,16.0,1,False,True,7
2,2025-03-07 15:48:00,8.0,Mangalia 2 Warszawa...,8.0,1,False,True,8
2,2025-03-07 16:12:00,8.0,Mangalia 2 Warszawa...,0.0,1,False,True,9
3,2025-03-07 14:30:00,8.0,"ESY , ul. Cybernetyki 7...",8.0,1,False,False,1
3,2025-03-07 15:34:00,8.0,"ESY , ul. Cybernetyki 7...",0.0,1,False,False,2
4,2025-03-07 14:30:00,8.0,Mangalia 2 Warszawa...,8.0,1,False,False,1
4,2025-03-07 15:34:00,8.0,Mangalia 2 Warszawa...,0.0,1,False,False,2
5,2025-03-07 14:30:00,8.0,"FLORESY , ul. Cybernetyki 7...",16.0,1,False,False,1
5,2025-03-07 15:34:00,8.0,"FLORESY , ul. Cybernetyki 7...",8.0,1,False,False,2
5,2025-03-07 16:38:00,8.0,"FLORESY , ul. Cybernetyki 7...",0.0,1,False,False,3
6,2025-03-07 14:30:00,8.0,Vena Prymasa Tysiąclecia 83...,24.0,1,False,False,1
6,2025-03-07 15:34:00,8.0,Vena Prymasa Tysiąclecia 83...,16.0,1,False,False,2
6,2025-03-07 16:38:00,8.0,Vena Prymasa Tysiąclecia 83...,8.0,1,False,False,3
6,2025-03-07 17:42:00,8.0,Vena Prymasa Tysiąclecia 83...,0.0,1,False,False,4
7,2025-03-07 14:30:00,8.0,Warszawa ul.Siennicka...,24.0,1,False,False,1
7,2025-03-07 15:34:00,8.0,Warszawa ul.Siennicka...,16.0,1,False,False,2
7,2025-03-07 16:38:00,8.0,Warszawa ul.Siennicka...,8.0,1,False,False,3
7,2025-03-07 17:42:00,8.0,Warszawa ul.Siennicka...,0.0,1,False,False,4

In [9]:
rozklad_curs["it_is_zaprawa"] = rozklad_curs["it_is_zaprawa"].replace({True:'z', False:'b'})
rozklad_curs["pompa_dzwig"] = rozklad_curs["pompa_dzwig"].replace({True:'p', False:'d'})
rozklad_curs

,list_of_loads,list_of_courses,name,reszta,wenz,it_is_zaprawa,pompa_dzwig,namber_cours
0,2025-03-07 07:30:00,8.0,"Park Skandynawia, etap E10, E1...",172.0,1,b,p,1
0,2025-03-07 07:54:00,8.0,"Park Skandynawia, etap E10, E1...",164.0,1,b,p,2
0,2025-03-07 08:18:00,8.0,"Park Skandynawia, etap E10, E1...",156.0,1,b,p,3
0,2025-03-07 08:42:00,8.0,"Park Skandynawia, etap E10, E1...",148.0,1,b,p,4
0,2025-03-07 09:06:00,8.0,"Park Skandynawia, etap E10, E1...",140.0,1,b,p,5
0,2025-03-07 09:30:00,8.0,"Park Skandynawia, etap E10, E1...",132.0,1,b,p,6
0,2025-03-07 09:54:00,8.0,"Park Skandynawia, etap E10, E1...",124.0,1,b,p,7
0,2025-03-07 10:18:00,8.0,"Park Skandynawia, etap E10, E1...",116.0,1,b,p,8
0,2025-03-07 10:42:00,8.0,"Park Skandynawia, etap E10, E1...",108.0,1,b,p,9
0,2025-03-07 11:06:00,8.0,"Park Skandynawia, etap E10, E1...",100.0,1,b,p,10
0,2025-03-07 11:30:00,8.0,"Park Skandynawia, etap E10, E1...",92.0,1,b,p,11
0,2025-03-07 11:54:00,8.0,"Park Skandynawia, etap E10, E1...",84.0,1,b,p,12
0,2025-03-07 12:18:00,8.0,"Park Skandynawia, etap E10, E1...",76.0,1,b,p,13
0,2025-03-07 12:42:00,8.0,"Park Skandynawia, etap E10, E1...",68.0,1,b,p,14
0,2025-03-07 13:06:00,8.0,"Park Skandynawia, etap E10, E1...",60.0,1,b,p,15
0,2025-03-07 13:30:00,8.0,"Park Skandynawia, etap E10, E1...",52.0,1,b,p,16
0,2025-03-07 13:54:00,8.0,"Park Skandynawia, etap E10, E1...",44.0,1,b,p,17
0,2025-03-07 14:18:00,8.0,"Park Skandynawia, etap E10, E1...",36.0,1,b,p,18
0,2025-03-07 14:42:00,8.0,"Park Skandynawia, etap E10, E1...",28.0,1,b,p,19
0,2025-03-07 15:06:00,8.0,"Park Skandynawia, etap E10, E1...",20.0,1,b,p,20
0,2025-03-07 15:30:00,8.0,"Park Skandynawia, etap E10, E1...",12.0,1,b,p,21
0,2025-03-07 15:54:00,8.0,"Park Skandynawia, etap E10, E1...",4.0,1,b,p,22
0,2025-03-07 16:18:00,4.0,"Park Skandynawia, etap E10, E1...",0.0,1,b,p,23
1,2025-03-07 11:30:00,8.0,Rosy 41lb...,19.0,1,b,p,1
1,2025-03-07 11:54:00,8.0,Rosy 41lb...,11.0,1,b,p,2
1,2025-03-07 12:18:00,8.0,Rosy 41lb...,3.0,1,b,p,3
1,2025-03-07 12:42:00,3.0,Rosy 41lb...,0.0,1,b,p,4
2,2025-03-07 13:00:00,8.0,Mangalia 2 Warszawa...,64.0,1,b,p,1
2,2025-03-07 13:24:00,8.0,Mangalia 2 Warszawa...,56.0,1,b,p,2
2,2025-03-07 13:48:00,8.0,Mangalia 2 Warszawa...,48.0,1,b,p,3
2,2025-03-07 14:12:00,8.0,Mangalia 2 Warszawa...,40.0,1,b,p,4
2,2025-03-07 14:36:00,8.0,Mangalia 2 Warszawa...,32.0,1,b,p,5
2,2025-03-07 15:00:00,8.0,Mangalia 2 Warszawa...,24.0,1,b,p,6
2,2025-03-07 15:24:00,8.0,Mangalia 2 Warszawa...,16.0,1,b,p,7
2,2025-03-07 15:48:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,p,8
2,2025-03-07 16:12:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,p,9
3,2025-03-07 14:30:00,8.0,"ESY , ul. Cybernetyki 7...",8.0,1,b,d,1
3,2025-03-07 15:34:00,8.0,"ESY , ul. Cybernetyki 7...",0.0,1,b,d,2
4,2025-03-07 14:30:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,d,1
4,2025-03-07 15:34:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,d,2
5,2025-03-07 14:30:00,8.0,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d,1
5,2025-03-07 15:34:00,8.0,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d,2
5,2025-03-07 16:38:00,8.0,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d,3
6,2025-03-07 14:30:00,8.0,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d,1
6,2025-03-07 15:34:00,8.0,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d,2
6,2025-03-07 16:38:00,8.0,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d,3
6,2025-03-07 17:42:00,8.0,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d,4
7,2025-03-07 14:30:00,8.0,Warszawa ul.Siennicka...,24.0,1,b,d,1
7,2025-03-07 15:34:00,8.0,Warszawa ul.Siennicka...,16.0,1,b,d,2
7,2025-03-07 16:38:00,8.0,Warszawa ul.Siennicka...,8.0,1,b,d,3
7,2025-03-07 17:42:00,8.0,Warszawa ul.Siennicka...,0.0,1,b,d,4

In [10]:
rozklad_curs= rozklad_curs.reset_index()

In [11]:
rozklad_curs

,index,list_of_loads,list_of_courses,name,reszta,wenz,it_is_zaprawa,pompa_dzwig,namber_cours
0,0,2025-03-07 07:30:00,8.0,"Park Skandynawia, etap E10, E1...",172.0,1,b,p,1
1,0,2025-03-07 07:54:00,8.0,"Park Skandynawia, etap E10, E1...",164.0,1,b,p,2
2,0,2025-03-07 08:18:00,8.0,"Park Skandynawia, etap E10, E1...",156.0,1,b,p,3
3,0,2025-03-07 08:42:00,8.0,"Park Skandynawia, etap E10, E1...",148.0,1,b,p,4
4,0,2025-03-07 09:06:00,8.0,"Park Skandynawia, etap E10, E1...",140.0,1,b,p,5
5,0,2025-03-07 09:30:00,8.0,"Park Skandynawia, etap E10, E1...",132.0,1,b,p,6
6,0,2025-03-07 09:54:00,8.0,"Park Skandynawia, etap E10, E1...",124.0,1,b,p,7
7,0,2025-03-07 10:18:00,8.0,"Park Skandynawia, etap E10, E1...",116.0,1,b,p,8
8,0,2025-03-07 10:42:00,8.0,"Park Skandynawia, etap E10, E1...",108.0,1,b,p,9
9,0,2025-03-07 11:06:00,8.0,"Park Skandynawia, etap E10, E1...",100.0,1,b,p,10
10,0,2025-03-07 11:30:00,8.0,"Park Skandynawia, etap E10, E1...",92.0,1,b,p,11
11,0,2025-03-07 11:54:00,8.0,"Park Skandynawia, etap E10, E1...",84.0,1,b,p,12
12,0,2025-03-07 12:18:00,8.0,"Park Skandynawia, etap E10, E1...",76.0,1,b,p,13
13,0,2025-03-07 12:42:00,8.0,"Park Skandynawia, etap E10, E1...",68.0,1,b,p,14
14,0,2025-03-07 13:06:00,8.0,"Park Skandynawia, etap E10, E1...",60.0,1,b,p,15
15,0,2025-03-07 13:30:00,8.0,"Park Skandynawia, etap E10, E1...",52.0,1,b,p,16
16,0,2025-03-07 13:54:00,8.0,"Park Skandynawia, etap E10, E1...",44.0,1,b,p,17
17,0,2025-03-07 14:18:00,8.0,"Park Skandynawia, etap E10, E1...",36.0,1,b,p,18
18,0,2025-03-07 14:42:00,8.0,"Park Skandynawia, etap E10, E1...",28.0,1,b,p,19
19,0,2025-03-07 15:06:00,8.0,"Park Skandynawia, etap E10, E1...",20.0,1,b,p,20
20,0,2025-03-07 15:30:00,8.0,"Park Skandynawia, etap E10, E1...",12.0,1,b,p,21
21,0,2025-03-07 15:54:00,8.0,"Park Skandynawia, etap E10, E1...",4.0,1,b,p,22
22,0,2025-03-07 16:18:00,4.0,"Park Skandynawia, etap E10, E1...",0.0,1,b,p,23
23,1,2025-03-07 11:30:00,8.0,Rosy 41lb...,19.0,1,b,p,1
24,1,2025-03-07 11:54:00,8.0,Rosy 41lb...,11.0,1,b,p,2
25,1,2025-03-07 12:18:00,8.0,Rosy 41lb...,3.0,1,b,p,3
26,1,2025-03-07 12:42:00,3.0,Rosy 41lb...,0.0,1,b,p,4
27,2,2025-03-07 13:00:00,8.0,Mangalia 2 Warszawa...,64.0,1,b,p,1
28,2,2025-03-07 13:24:00,8.0,Mangalia 2 Warszawa...,56.0,1,b,p,2
29,2,2025-03-07 13:48:00,8.0,Mangalia 2 Warszawa...,48.0,1,b,p,3
30,2,2025-03-07 14:12:00,8.0,Mangalia 2 Warszawa...,40.0,1,b,p,4
31,2,2025-03-07 14:36:00,8.0,Mangalia 2 Warszawa...,32.0,1,b,p,5
32,2,2025-03-07 15:00:00,8.0,Mangalia 2 Warszawa...,24.0,1,b,p,6
33,2,2025-03-07 15:24:00,8.0,Mangalia 2 Warszawa...,16.0,1,b,p,7
34,2,2025-03-07 15:48:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,p,8
35,2,2025-03-07 16:12:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,p,9
36,3,2025-03-07 14:30:00,8.0,"ESY , ul. Cybernetyki 7...",8.0,1,b,d,1
37,3,2025-03-07 15:34:00,8.0,"ESY , ul. Cybernetyki 7...",0.0,1,b,d,2
38,4,2025-03-07 14:30:00,8.0,Mangalia 2 Warszawa...,8.0,1,b,d,1
39,4,2025-03-07 15:34:00,8.0,Mangalia 2 Warszawa...,0.0,1,b,d,2
40,5,2025-03-07 14:30:00,8.0,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d,1
41,5,2025-03-07 15:34:00,8.0,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d,2
42,5,2025-03-07 16:38:00,8.0,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d,3
43,6,2025-03-07 14:30:00,8.0,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d,1
44,6,2025-03-07 15:34:00,8.0,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d,2
45,6,2025-03-07 16:38:00,8.0,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d,3
46,6,2025-03-07 17:42:00,8.0,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d,4
47,7,2025-03-07 14:30:00,8.0,Warszawa ul.Siennicka...,24.0,1,b,d,1
48,7,2025-03-07 15:34:00,8.0,Warszawa ul.Siennicka...,16.0,1,b,d,2
49,7,2025-03-07 16:38:00,8.0,Warszawa ul.Siennicka...,8.0,1,b,d,3
50,7,2025-03-07 17:42:00,8.0,Warszawa ul.Siennicka...,0.0,1,b,d,4

In [12]:
rozklad_curs.index=rozklad_curs.index+1

In [13]:
rozklad_curs.columns = ['id', 'time', 'm3', 'budowa', 'res','wenz','mat', 'p/d', 'k']
rozklad_curs = rozklad_curs.reindex(['id', 'time', 'm3', 'k','budowa', 'res', 'wenz', 'mat', 'p/d' ], axis=1)
rozklad_curs

,id,time,m3,k,budowa,res,wenz,mat,p/d
1,0,2025-03-07 07:30:00,8.0,1,"Park Skandynawia, etap E10, E1...",172.0,1,b,p
2,0,2025-03-07 07:54:00,8.0,2,"Park Skandynawia, etap E10, E1...",164.0,1,b,p
3,0,2025-03-07 08:18:00,8.0,3,"Park Skandynawia, etap E10, E1...",156.0,1,b,p
4,0,2025-03-07 08:42:00,8.0,4,"Park Skandynawia, etap E10, E1...",148.0,1,b,p
5,0,2025-03-07 09:06:00,8.0,5,"Park Skandynawia, etap E10, E1...",140.0,1,b,p
6,0,2025-03-07 09:30:00,8.0,6,"Park Skandynawia, etap E10, E1...",132.0,1,b,p
7,0,2025-03-07 09:54:00,8.0,7,"Park Skandynawia, etap E10, E1...",124.0,1,b,p
8,0,2025-03-07 10:18:00,8.0,8,"Park Skandynawia, etap E10, E1...",116.0,1,b,p
9,0,2025-03-07 10:42:00,8.0,9,"Park Skandynawia, etap E10, E1...",108.0,1,b,p
10,0,2025-03-07 11:06:00,8.0,10,"Park Skandynawia, etap E10, E1...",100.0,1,b,p
11,0,2025-03-07 11:30:00,8.0,11,"Park Skandynawia, etap E10, E1...",92.0,1,b,p
12,0,2025-03-07 11:54:00,8.0,12,"Park Skandynawia, etap E10, E1...",84.0,1,b,p
13,0,2025-03-07 12:18:00,8.0,13,"Park Skandynawia, etap E10, E1...",76.0,1,b,p
14,0,2025-03-07 12:42:00,8.0,14,"Park Skandynawia, etap E10, E1...",68.0,1,b,p
15,0,2025-03-07 13:06:00,8.0,15,"Park Skandynawia, etap E10, E1...",60.0,1,b,p
16,0,2025-03-07 13:30:00,8.0,16,"Park Skandynawia, etap E10, E1...",52.0,1,b,p
17,0,2025-03-07 13:54:00,8.0,17,"Park Skandynawia, etap E10, E1...",44.0,1,b,p
18,0,2025-03-07 14:18:00,8.0,18,"Park Skandynawia, etap E10, E1...",36.0,1,b,p
19,0,2025-03-07 14:42:00,8.0,19,"Park Skandynawia, etap E10, E1...",28.0,1,b,p
20,0,2025-03-07 15:06:00,8.0,20,"Park Skandynawia, etap E10, E1...",20.0,1,b,p
21,0,2025-03-07 15:30:00,8.0,21,"Park Skandynawia, etap E10, E1...",12.0,1,b,p
22,0,2025-03-07 15:54:00,8.0,22,"Park Skandynawia, etap E10, E1...",4.0,1,b,p
23,0,2025-03-07 16:18:00,4.0,23,"Park Skandynawia, etap E10, E1...",0.0,1,b,p
24,1,2025-03-07 11:30:00,8.0,1,Rosy 41lb...,19.0,1,b,p
25,1,2025-03-07 11:54:00,8.0,2,Rosy 41lb...,11.0,1,b,p
26,1,2025-03-07 12:18:00,8.0,3,Rosy 41lb...,3.0,1,b,p
27,1,2025-03-07 12:42:00,3.0,4,Rosy 41lb...,0.0,1,b,p
28,2,2025-03-07 13:00:00,8.0,1,Mangalia 2 Warszawa...,64.0,1,b,p
29,2,2025-03-07 13:24:00,8.0,2,Mangalia 2 Warszawa...,56.0,1,b,p
30,2,2025-03-07 13:48:00,8.0,3,Mangalia 2 Warszawa...,48.0,1,b,p
31,2,2025-03-07 14:12:00,8.0,4,Mangalia 2 Warszawa...,40.0,1,b,p
32,2,2025-03-07 14:36:00,8.0,5,Mangalia 2 Warszawa...,32.0,1,b,p
33,2,2025-03-07 15:00:00,8.0,6,Mangalia 2 Warszawa...,24.0,1,b,p
34,2,2025-03-07 15:24:00,8.0,7,Mangalia 2 Warszawa...,16.0,1,b,p
35,2,2025-03-07 15:48:00,8.0,8,Mangalia 2 Warszawa...,8.0,1,b,p
36,2,2025-03-07 16:12:00,8.0,9,Mangalia 2 Warszawa...,0.0,1,b,p
37,3,2025-03-07 14:30:00,8.0,1,"ESY , ul. Cybernetyki 7...",8.0,1,b,d
38,3,2025-03-07 15:34:00,8.0,2,"ESY , ul. Cybernetyki 7...",0.0,1,b,d
39,4,2025-03-07 14:30:00,8.0,1,Mangalia 2 Warszawa...,8.0,1,b,d
40,4,2025-03-07 15:34:00,8.0,2,Mangalia 2 Warszawa...,0.0,1,b,d
41,5,2025-03-07 14:30:00,8.0,1,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d
42,5,2025-03-07 15:34:00,8.0,2,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d
43,5,2025-03-07 16:38:00,8.0,3,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d
44,6,2025-03-07 14:30:00,8.0,1,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d
45,6,2025-03-07 15:34:00,8.0,2,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d
46,6,2025-03-07 16:38:00,8.0,3,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d
47,6,2025-03-07 17:42:00,8.0,4,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d
48,7,2025-03-07 14:30:00,8.0,1,Warszawa ul.Siennicka...,24.0,1,b,d
49,7,2025-03-07 15:34:00,8.0,2,Warszawa ul.Siennicka...,16.0,1,b,d
50,7,2025-03-07 16:38:00,8.0,3,Warszawa ul.Siennicka...,8.0,1,b,d
51,7,2025-03-07 17:42:00,8.0,4,Warszawa ul.Siennicka...,0.0,1,b,d

In [14]:
# вставка для драйвер
rozklad_curs.sort_values("time", inplace=True)
rozklad_curs.reset_index(drop=True, inplace=True)
rozklad_curs.index=rozklad_curs.index+1
df_for_driver= rozklad_curs.copy()

In [15]:
# start make df for diver

df_for_driver

,id,time,m3,k,budowa,res,wenz,mat,p/d
1,0,2025-03-07 07:30:00,8.0,1,"Park Skandynawia, etap E10, E1...",172.0,1,b,p
2,0,2025-03-07 07:54:00,8.0,2,"Park Skandynawia, etap E10, E1...",164.0,1,b,p
3,0,2025-03-07 08:18:00,8.0,3,"Park Skandynawia, etap E10, E1...",156.0,1,b,p
4,0,2025-03-07 08:42:00,8.0,4,"Park Skandynawia, etap E10, E1...",148.0,1,b,p
5,0,2025-03-07 09:06:00,8.0,5,"Park Skandynawia, etap E10, E1...",140.0,1,b,p
6,0,2025-03-07 09:30:00,8.0,6,"Park Skandynawia, etap E10, E1...",132.0,1,b,p
7,0,2025-03-07 09:54:00,8.0,7,"Park Skandynawia, etap E10, E1...",124.0,1,b,p
8,0,2025-03-07 10:18:00,8.0,8,"Park Skandynawia, etap E10, E1...",116.0,1,b,p
9,0,2025-03-07 10:42:00,8.0,9,"Park Skandynawia, etap E10, E1...",108.0,1,b,p
10,0,2025-03-07 11:06:00,8.0,10,"Park Skandynawia, etap E10, E1...",100.0,1,b,p
11,0,2025-03-07 11:30:00,8.0,11,"Park Skandynawia, etap E10, E1...",92.0,1,b,p
12,1,2025-03-07 11:30:00,8.0,1,Rosy 41lb...,19.0,1,b,p
13,0,2025-03-07 11:54:00,8.0,12,"Park Skandynawia, etap E10, E1...",84.0,1,b,p
14,1,2025-03-07 11:54:00,8.0,2,Rosy 41lb...,11.0,1,b,p
15,1,2025-03-07 12:18:00,8.0,3,Rosy 41lb...,3.0,1,b,p
16,0,2025-03-07 12:18:00,8.0,13,"Park Skandynawia, etap E10, E1...",76.0,1,b,p
17,0,2025-03-07 12:42:00,8.0,14,"Park Skandynawia, etap E10, E1...",68.0,1,b,p
18,1,2025-03-07 12:42:00,3.0,4,Rosy 41lb...,0.0,1,b,p
19,2,2025-03-07 13:00:00,8.0,1,Mangalia 2 Warszawa...,64.0,1,b,p
20,0,2025-03-07 13:06:00,8.0,15,"Park Skandynawia, etap E10, E1...",60.0,1,b,p
21,2,2025-03-07 13:24:00,8.0,2,Mangalia 2 Warszawa...,56.0,1,b,p
22,0,2025-03-07 13:30:00,8.0,16,"Park Skandynawia, etap E10, E1...",52.0,1,b,p
23,2,2025-03-07 13:48:00,8.0,3,Mangalia 2 Warszawa...,48.0,1,b,p
24,0,2025-03-07 13:54:00,8.0,17,"Park Skandynawia, etap E10, E1...",44.0,1,b,p
25,2,2025-03-07 14:12:00,8.0,4,Mangalia 2 Warszawa...,40.0,1,b,p
26,0,2025-03-07 14:18:00,8.0,18,"Park Skandynawia, etap E10, E1...",36.0,1,b,p
27,6,2025-03-07 14:30:00,8.0,1,Vena Prymasa Tysiąclecia 83...,24.0,1,b,d
28,5,2025-03-07 14:30:00,8.0,1,"FLORESY , ul. Cybernetyki 7...",16.0,1,b,d
29,4,2025-03-07 14:30:00,8.0,1,Mangalia 2 Warszawa...,8.0,1,b,d
30,3,2025-03-07 14:30:00,8.0,1,"ESY , ul. Cybernetyki 7...",8.0,1,b,d
31,7,2025-03-07 14:30:00,8.0,1,Warszawa ul.Siennicka...,24.0,1,b,d
32,2,2025-03-07 14:36:00,8.0,5,Mangalia 2 Warszawa...,32.0,1,b,p
33,0,2025-03-07 14:42:00,8.0,19,"Park Skandynawia, etap E10, E1...",28.0,1,b,p
34,2,2025-03-07 15:00:00,8.0,6,Mangalia 2 Warszawa...,24.0,1,b,p
35,0,2025-03-07 15:06:00,8.0,20,"Park Skandynawia, etap E10, E1...",20.0,1,b,p
36,2,2025-03-07 15:24:00,8.0,7,Mangalia 2 Warszawa...,16.0,1,b,p
37,0,2025-03-07 15:30:00,8.0,21,"Park Skandynawia, etap E10, E1...",12.0,1,b,p
38,7,2025-03-07 15:34:00,8.0,2,Warszawa ul.Siennicka...,16.0,1,b,d
39,3,2025-03-07 15:34:00,8.0,2,"ESY , ul. Cybernetyki 7...",0.0,1,b,d
40,4,2025-03-07 15:34:00,8.0,2,Mangalia 2 Warszawa...,0.0,1,b,d
41,5,2025-03-07 15:34:00,8.0,2,"FLORESY , ul. Cybernetyki 7...",8.0,1,b,d
42,6,2025-03-07 15:34:00,8.0,2,Vena Prymasa Tysiąclecia 83...,16.0,1,b,d
43,2,2025-03-07 15:48:00,8.0,8,Mangalia 2 Warszawa...,8.0,1,b,p
44,0,2025-03-07 15:54:00,8.0,22,"Park Skandynawia, etap E10, E1...",4.0,1,b,p
45,2,2025-03-07 16:12:00,8.0,9,Mangalia 2 Warszawa...,0.0,1,b,p
46,0,2025-03-07 16:18:00,4.0,23,"Park Skandynawia, etap E10, E1...",0.0,1,b,p
47,5,2025-03-07 16:38:00,8.0,3,"FLORESY , ul. Cybernetyki 7...",0.0,1,b,d
48,6,2025-03-07 16:38:00,8.0,3,Vena Prymasa Tysiąclecia 83...,8.0,1,b,d
49,7,2025-03-07 16:38:00,8.0,3,Warszawa ul.Siennicka...,8.0,1,b,d
50,6,2025-03-07 17:42:00,8.0,4,Vena Prymasa Tysiąclecia 83...,0.0,1,b,d
51,7,2025-03-07 17:42:00,8.0,4,Warszawa ul.Siennicka...,0.0,1,b,d

In [16]:
df_for_driver = df_for_driver[["time","m3","mat","p/d"]]
df_for_driver

                  time   m3 mat p/d
1  2025-03-07 07:30:00  8.0   b   p
2  2025-03-07 07:54:00  8.0   b   p
3  2025-03-07 08:18:00  8.0   b   p
4  2025-03-07 08:42:00  8.0   b   p
5  2025-03-07 09:06:00  8.0   b   p
6  2025-03-07 09:30:00  8.0   b   p
7  2025-03-07 09:54:00  8.0   b   p
8  2025-03-07 10:18:00  8.0   b   p
9  2025-03-07 10:42:00  8.0   b   p
10 2025-03-07 11:06:00  8.0   b   p
11 2025-03-07 11:30:00  8.0   b   p
12 2025-03-07 11:30:00  8.0   b   p
13 2025-03-07 11:54:00  8.0   b   p
14 2025-03-07 11:54:00  8.0   b   p
15 2025-03-07 12:18:00  8.0   b   p
16 2025-03-07 12:18:00  8.0   b   p
17 2025-03-07 12:42:00  8.0   b   p
18 2025-03-07 12:42:00  3.0   b   p
19 2025-03-07 13:00:00  8.0   b   p
20 2025-03-07 13:06:00  8.0   b   p
21 2025-03-07 13:24:00  8.0   b   p
22 2025-03-07 13:30:00  8.0   b   p
23 2025-03-07 13:48:00  8.0   b   p
24 2025-03-07 13:54:00  8.0   b   p
25 2025-03-07 14:12:00  8.0   b   p
26 2025-03-07 14:18:00  8.0   b   p
27 2025-03-07 14:30:00  8.0   b   d
28 2025-03-07 14:30:00  8.0   b   d
29 2025-03-07 14:30:00  8.0   b   d
30 2025-03-07 14:30:00  8.0   b   d
31 2025-03-07 14:30:00  8.0   b   d
32 2025-03-07 14:36:00  8.0   b   p
33 2025-03-07 14:42:00  8.0   b   p
34 2025-03-07 15:00:00  8.0   b   p
35 2025-03-07 15:06:00  8.0   b   p
36 2025-03-07 15:24:00  8.0   b   p
37 2025-03-07 15:30:00  8.0   b   p
38 2025-03-07 15:34:00  8.0   b   d
39 2025-03-07 15:34:00  8.0   b   d
40 2025-03-07 15:34:00  8.0   b   d
41 2025-03-07 15:34:00  8.0   b   d
42 2025-03-07 15:34:00  8.0   b   d
43 2025-03-07 15:48:00  8.0   b   p
44 2025-03-07 15:54:00  8.0   b   p
45 2025-03-07 16:12:00  8.0   b   p
46 2025-03-07 16:18:00  4.0   b   p
47 2025-03-07 16:38:00  8.0   b   d
48 2025-03-07 16:38:00  8.0   b   d
49 2025-03-07 16:38:00  8.0   b   d
50 2025-03-07 17:42:00  8.0   b   d
51 2025-03-07 17:42:00  8.0   b   d

In [17]:
df_for_driver

                  time   m3 mat p/d
1  2025-03-07 07:30:00  8.0   b   p
2  2025-03-07 07:54:00  8.0   b   p
3  2025-03-07 08:18:00  8.0   b   p
4  2025-03-07 08:42:00  8.0   b   p
5  2025-03-07 09:06:00  8.0   b   p
6  2025-03-07 09:30:00  8.0   b   p
7  2025-03-07 09:54:00  8.0   b   p
8  2025-03-07 10:18:00  8.0   b   p
9  2025-03-07 10:42:00  8.0   b   p
10 2025-03-07 11:06:00  8.0   b   p
11 2025-03-07 11:30:00  8.0   b   p
12 2025-03-07 11:30:00  8.0   b   p
13 2025-03-07 11:54:00  8.0   b   p
14 2025-03-07 11:54:00  8.0   b   p
15 2025-03-07 12:18:00  8.0   b   p
16 2025-03-07 12:18:00  8.0   b   p
17 2025-03-07 12:42:00  8.0   b   p
18 2025-03-07 12:42:00  3.0   b   p
19 2025-03-07 13:00:00  8.0   b   p
20 2025-03-07 13:06:00  8.0   b   p
21 2025-03-07 13:24:00  8.0   b   p
22 2025-03-07 13:30:00  8.0   b   p
23 2025-03-07 13:48:00  8.0   b   p
24 2025-03-07 13:54:00  8.0   b   p
25 2025-03-07 14:12:00  8.0   b   p
26 2025-03-07 14:18:00  8.0   b   p
27 2025-03-07 14:30:00  8.0   b   d
28 2025-03-07 14:30:00  8.0   b   d
29 2025-03-07 14:30:00  8.0   b   d
30 2025-03-07 14:30:00  8.0   b   d
31 2025-03-07 14:30:00  8.0   b   d
32 2025-03-07 14:36:00  8.0   b   p
33 2025-03-07 14:42:00  8.0   b   p
34 2025-03-07 15:00:00  8.0   b   p
35 2025-03-07 15:06:00  8.0   b   p
36 2025-03-07 15:24:00  8.0   b   p
37 2025-03-07 15:30:00  8.0   b   p
38 2025-03-07 15:34:00  8.0   b   d
39 2025-03-07 15:34:00  8.0   b   d
40 2025-03-07 15:34:00  8.0   b   d
41 2025-03-07 15:34:00  8.0   b   d
42 2025-03-07 15:34:00  8.0   b   d
43 2025-03-07 15:48:00  8.0   b   p
44 2025-03-07 15:54:00  8.0   b   p
45 2025-03-07 16:12:00  8.0   b   p
46 2025-03-07 16:18:00  4.0   b   p
47 2025-03-07 16:38:00  8.0   b   d
48 2025-03-07 16:38:00  8.0   b   d
49 2025-03-07 16:38:00  8.0   b   d
50 2025-03-07 17:42:00  8.0   b   d
51 2025-03-07 17:42:00  8.0   b   d

In [18]:
df_for_driver = df_for_driver.copy()
df_for_driver['m3'] = df_for_driver['m3'].astype(float)
df_for_driver.dtypes

time    datetime64[ns]
m3             float64
mat             object
p/d             object
dtype: object

In [19]:
def get_end_time(row):
    additional_hour = pd.Timedelta(hours=1)
    if row['p/d'] == 'p':
        time_in_minutes = pd.to_timedelta(row['m3']*3, unit='m')
    else:
        time_in_minutes = pd.to_timedelta(row['m3']*8, unit='m')
    return row['time'] + time_in_minutes + additional_hour

In [20]:
df_for_driver.loc[:,'end_time'] = df_for_driver.apply(get_end_time, axis=1)

In [21]:
df_for_driver

                  time   m3 mat p/d            end_time
1  2025-03-07 07:30:00  8.0   b   p 2025-03-07 08:54:00
2  2025-03-07 07:54:00  8.0   b   p 2025-03-07 09:18:00
3  2025-03-07 08:18:00  8.0   b   p 2025-03-07 09:42:00
4  2025-03-07 08:42:00  8.0   b   p 2025-03-07 10:06:00
5  2025-03-07 09:06:00  8.0   b   p 2025-03-07 10:30:00
6  2025-03-07 09:30:00  8.0   b   p 2025-03-07 10:54:00
7  2025-03-07 09:54:00  8.0   b   p 2025-03-07 11:18:00
8  2025-03-07 10:18:00  8.0   b   p 2025-03-07 11:42:00
9  2025-03-07 10:42:00  8.0   b   p 2025-03-07 12:06:00
10 2025-03-07 11:06:00  8.0   b   p 2025-03-07 12:30:00
11 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
12 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
13 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
14 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
15 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
16 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
17 2025-03-07 12:42:00  8.0   b   p 2025-03-07 14:06:00
18 2025-03-07 12:42:00  3.0   b   p 2025-03-07 13:51:00
19 2025-03-07 13:00:00  8.0   b   p 2025-03-07 14:24:00
20 2025-03-07 13:06:00  8.0   b   p 2025-03-07 14:30:00
21 2025-03-07 13:24:00  8.0   b   p 2025-03-07 14:48:00
22 2025-03-07 13:30:00  8.0   b   p 2025-03-07 14:54:00
23 2025-03-07 13:48:00  8.0   b   p 2025-03-07 15:12:00
24 2025-03-07 13:54:00  8.0   b   p 2025-03-07 15:18:00
25 2025-03-07 14:12:00  8.0   b   p 2025-03-07 15:36:00
26 2025-03-07 14:18:00  8.0   b   p 2025-03-07 15:42:00
27 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
28 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
29 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
30 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
31 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
32 2025-03-07 14:36:00  8.0   b   p 2025-03-07 16:00:00
33 2025-03-07 14:42:00  8.0   b   p 2025-03-07 16:06:00
34 2025-03-07 15:00:00  8.0   b   p 2025-03-07 16:24:00
35 2025-03-07 15:06:00  8.0   b   p 2025-03-07 16:30:00
36 2025-03-07 15:24:00  8.0   b   p 2025-03-07 16:48:00
37 2025-03-07 15:30:00  8.0   b   p 2025-03-07 16:54:00
38 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
39 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
40 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
41 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
42 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
43 2025-03-07 15:48:00  8.0   b   p 2025-03-07 17:12:00
44 2025-03-07 15:54:00  8.0   b   p 2025-03-07 17:18:00
45 2025-03-07 16:12:00  8.0   b   p 2025-03-07 17:36:00
46 2025-03-07 16:18:00  4.0   b   p 2025-03-07 17:30:00
47 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
48 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
49 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
50 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00
51 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00

In [22]:
df_for_driver.dtypes

time        datetime64[ns]
m3                 float64
mat                 object
p/d                 object
end_time    datetime64[ns]
dtype: object

In [23]:
# Преобразование строки в формате 'dd.mm.yyyy' в 'yyyy-mm-dd'
formatted_date_start = pd.to_datetime(date_of_request, format='%d.%m.%Y').strftime('%Y-%m-%d') + ' 04:00:00'
formatted_date_finish = pd.to_datetime(date_of_request, format='%d.%m.%Y').strftime('%Y-%m-%d') + ' 23:00:00'

In [24]:
formatted_date_finish

'2025-03-07 23:00:00'

In [25]:
time_index = pd.date_range(start=formatted_date_start, end=formatted_date_finish, freq='min')

In [26]:
time_index

DatetimeIndex(['2025-03-07 04:00:00', '2025-03-07 04:01:00',
               '2025-03-07 04:02:00', '2025-03-07 04:03:00',
               '2025-03-07 04:04:00', '2025-03-07 04:05:00',
               '2025-03-07 04:06:00', '2025-03-07 04:07:00',
               '2025-03-07 04:08:00', '2025-03-07 04:09:00',
               ...
               '2025-03-07 22:51:00', '2025-03-07 22:52:00',
               '2025-03-07 22:53:00', '2025-03-07 22:54:00',
               '2025-03-07 22:55:00', '2025-03-07 22:56:00',
               '2025-03-07 22:57:00', '2025-03-07 22:58:00',
               '2025-03-07 22:59:00', '2025-03-07 23:00:00'],
              dtype='datetime64[ns]', length=1141, freq='min')

In [27]:
df_full_day =  pd.DataFrame(index=time_index)

In [28]:
len(df_for_driver)

51

In [29]:
df_for_driver

                  time   m3 mat p/d            end_time
1  2025-03-07 07:30:00  8.0   b   p 2025-03-07 08:54:00
2  2025-03-07 07:54:00  8.0   b   p 2025-03-07 09:18:00
3  2025-03-07 08:18:00  8.0   b   p 2025-03-07 09:42:00
4  2025-03-07 08:42:00  8.0   b   p 2025-03-07 10:06:00
5  2025-03-07 09:06:00  8.0   b   p 2025-03-07 10:30:00
6  2025-03-07 09:30:00  8.0   b   p 2025-03-07 10:54:00
7  2025-03-07 09:54:00  8.0   b   p 2025-03-07 11:18:00
8  2025-03-07 10:18:00  8.0   b   p 2025-03-07 11:42:00
9  2025-03-07 10:42:00  8.0   b   p 2025-03-07 12:06:00
10 2025-03-07 11:06:00  8.0   b   p 2025-03-07 12:30:00
11 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
12 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
13 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
14 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
15 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
16 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
17 2025-03-07 12:42:00  8.0   b   p 2025-03-07 14:06:00
18 2025-03-07 12:42:00  3.0   b   p 2025-03-07 13:51:00
19 2025-03-07 13:00:00  8.0   b   p 2025-03-07 14:24:00
20 2025-03-07 13:06:00  8.0   b   p 2025-03-07 14:30:00
21 2025-03-07 13:24:00  8.0   b   p 2025-03-07 14:48:00
22 2025-03-07 13:30:00  8.0   b   p 2025-03-07 14:54:00
23 2025-03-07 13:48:00  8.0   b   p 2025-03-07 15:12:00
24 2025-03-07 13:54:00  8.0   b   p 2025-03-07 15:18:00
25 2025-03-07 14:12:00  8.0   b   p 2025-03-07 15:36:00
26 2025-03-07 14:18:00  8.0   b   p 2025-03-07 15:42:00
27 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
28 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
29 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
30 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
31 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
32 2025-03-07 14:36:00  8.0   b   p 2025-03-07 16:00:00
33 2025-03-07 14:42:00  8.0   b   p 2025-03-07 16:06:00
34 2025-03-07 15:00:00  8.0   b   p 2025-03-07 16:24:00
35 2025-03-07 15:06:00  8.0   b   p 2025-03-07 16:30:00
36 2025-03-07 15:24:00  8.0   b   p 2025-03-07 16:48:00
37 2025-03-07 15:30:00  8.0   b   p 2025-03-07 16:54:00
38 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
39 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
40 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
41 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
42 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
43 2025-03-07 15:48:00  8.0   b   p 2025-03-07 17:12:00
44 2025-03-07 15:54:00  8.0   b   p 2025-03-07 17:18:00
45 2025-03-07 16:12:00  8.0   b   p 2025-03-07 17:36:00
46 2025-03-07 16:18:00  4.0   b   p 2025-03-07 17:30:00
47 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
48 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
49 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
50 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00
51 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00

In [30]:
df_full_day

Empty DataFrame
Columns: []
Index: [2025-03-07 04:00:00, 2025-03-07 04:01:00, 2025-03-07 04:02:00, 2025-03-07 04:03:00, 2025-03-07 04:04:00, 2025-03-07 04:05:00, 2025-03-07 04:06:00, 2025-03-07 04:07:00, 2025-03-07 04:08:00, 2025-03-07 04:09:00, 2025-03-07 04:10:00, 2025-03-07 04:11:00, 2025-03-07 04:12:00, 2025-03-07 04:13:00, 2025-03-07 04:14:00, 2025-03-07 04:15:00, 2025-03-07 04:16:00, 2025-03-07 04:17:00, 2025-03-07 04:18:00, 2025-03-07 04:19:00, 2025-03-07 04:20:00, 2025-03-07 04:21:00, 2025-03-07 04:22:00, 2025-03-07 04:23:00, 2025-03-07 04:24:00, 2025-03-07 04:25:00, 2025-03-07 04:26:00, 2025-03-07 04:27:00, 2025-03-07 04:28:00, 2025-03-07 04:29:00, 2025-03-07 04:30:00, 2025-03-07 04:31:00, 2025-03-07 04:32:00, 2025-03-07 04:33:00, 2025-03-07 04:34:00, 2025-03-07 04:35:00, 2025-03-07 04:36:00, 2025-03-07 04:37:00, 2025-03-07 04:38:00, 2025-03-07 04:39:00, 2025-03-07 04:40:00, 2025-03-07 04:41:00, 2025-03-07 04:42:00, 2025-03-07 04:43:00, 2025-03-07 04:44:00, 2025-03-07 04:45:00, 2025-03-07 04:46:00, 2025-03-07 04:47:00, 2025-03-07 04:48:00, 2025-03-07 04:49:00, 2025-03-07 04:50:00, 2025-03-07 04:51:00, 2025-03-07 04:52:00, 2025-03-07 04:53:00, 2025-03-07 04:54:00, 2025-03-07 04:55:00, 2025-03-07 04:56:00, 2025-03-07 04:57:00, 2025-03-07 04:58:00, 2025-03-07 04:59:00, 2025-03-07 05:00:00, 2025-03-07 05:01:00, 2025-03-07 05:02:00, 2025-03-07 05:03:00, 2025-03-07 05:04:00, 2025-03-07 05:05:00, 2025-03-07 05:06:00, 2025-03-07 05:07:00, 2025-03-07 05:08:00, 2025-03-07 05:09:00, 2025-03-07 05:10:00, 2025-03-07 05:11:00, 2025-03-07 05:12:00, 2025-03-07 05:13:00, 2025-03-07 05:14:00, 2025-03-07 05:15:00, 2025-03-07 05:16:00, 2025-03-07 05:17:00, 2025-03-07 05:18:00, 2025-03-07 05:19:00, 2025-03-07 05:20:00, 2025-03-07 05:21:00, 2025-03-07 05:22:00, 2025-03-07 05:23:00, 2025-03-07 05:24:00, 2025-03-07 05:25:00, 2025-03-07 05:26:00, 2025-03-07 05:27:00, 2025-03-07 05:28:00, 2025-03-07 05:29:00, 2025-03-07 05:30:00, 2025-03-07 05:31:00, 2025-03-07 05:32:00, 2025-03-07 05:33:00, 2025-03-07 05:34:00, 2025-03-07 05:35:00, 2025-03-07 05:36:00, 2025-03-07 05:37:00, 2025-03-07 05:38:00, 2025-03-07 05:39:00, ...]

[1141 rows x 0 columns]

In [31]:
for i in range(1,len(df_for_driver)+1):
    mask = (df_full_day.index >= df_for_driver.loc[i, 'time']) & (df_full_day.index <= df_for_driver.loc[i, 'end_time'])
    # df_full_day[i] = np.where(mask, df_for_driver.loc[i, 'mat'], '')
    df_full_day.loc[mask, i] = df_for_driver.loc[i, 'mat']

In [32]:
# for i, row in df_for_driver.iterrows():
#     # Создаем маску интервала времени
#     mask = (time_index.time >= row['time']) & (time_index.time < row['end_time'])
#     # Копируем столбец же 'value' с условием
#     df_full_day.loc[mask, i] = row['mat']

In [33]:
# df_full_day.replace('',0, inplace=True)
df_full_day = df_full_day.fillna(0)

In [34]:
df_full_day[df_full_day[1]=='b']

,1,2,3,4,5,6,7,8,9,10,...,42,43,44,45,46,47,48,49,50,51
2025-03-07 07:30:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:31:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:32:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:33:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 07:34:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-07 08:50:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:51:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:52:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:53:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2025-03-07 08:54:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df_for_driver

                  time   m3 mat p/d            end_time
1  2025-03-07 07:30:00  8.0   b   p 2025-03-07 08:54:00
2  2025-03-07 07:54:00  8.0   b   p 2025-03-07 09:18:00
3  2025-03-07 08:18:00  8.0   b   p 2025-03-07 09:42:00
4  2025-03-07 08:42:00  8.0   b   p 2025-03-07 10:06:00
5  2025-03-07 09:06:00  8.0   b   p 2025-03-07 10:30:00
6  2025-03-07 09:30:00  8.0   b   p 2025-03-07 10:54:00
7  2025-03-07 09:54:00  8.0   b   p 2025-03-07 11:18:00
8  2025-03-07 10:18:00  8.0   b   p 2025-03-07 11:42:00
9  2025-03-07 10:42:00  8.0   b   p 2025-03-07 12:06:00
10 2025-03-07 11:06:00  8.0   b   p 2025-03-07 12:30:00
11 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
12 2025-03-07 11:30:00  8.0   b   p 2025-03-07 12:54:00
13 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
14 2025-03-07 11:54:00  8.0   b   p 2025-03-07 13:18:00
15 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
16 2025-03-07 12:18:00  8.0   b   p 2025-03-07 13:42:00
17 2025-03-07 12:42:00  8.0   b   p 2025-03-07 14:06:00
18 2025-03-07 12:42:00  3.0   b   p 2025-03-07 13:51:00
19 2025-03-07 13:00:00  8.0   b   p 2025-03-07 14:24:00
20 2025-03-07 13:06:00  8.0   b   p 2025-03-07 14:30:00
21 2025-03-07 13:24:00  8.0   b   p 2025-03-07 14:48:00
22 2025-03-07 13:30:00  8.0   b   p 2025-03-07 14:54:00
23 2025-03-07 13:48:00  8.0   b   p 2025-03-07 15:12:00
24 2025-03-07 13:54:00  8.0   b   p 2025-03-07 15:18:00
25 2025-03-07 14:12:00  8.0   b   p 2025-03-07 15:36:00
26 2025-03-07 14:18:00  8.0   b   p 2025-03-07 15:42:00
27 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
28 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
29 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
30 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
31 2025-03-07 14:30:00  8.0   b   d 2025-03-07 16:34:00
32 2025-03-07 14:36:00  8.0   b   p 2025-03-07 16:00:00
33 2025-03-07 14:42:00  8.0   b   p 2025-03-07 16:06:00
34 2025-03-07 15:00:00  8.0   b   p 2025-03-07 16:24:00
35 2025-03-07 15:06:00  8.0   b   p 2025-03-07 16:30:00
36 2025-03-07 15:24:00  8.0   b   p 2025-03-07 16:48:00
37 2025-03-07 15:30:00  8.0   b   p 2025-03-07 16:54:00
38 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
39 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
40 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
41 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
42 2025-03-07 15:34:00  8.0   b   d 2025-03-07 17:38:00
43 2025-03-07 15:48:00  8.0   b   p 2025-03-07 17:12:00
44 2025-03-07 15:54:00  8.0   b   p 2025-03-07 17:18:00
45 2025-03-07 16:12:00  8.0   b   p 2025-03-07 17:36:00
46 2025-03-07 16:18:00  4.0   b   p 2025-03-07 17:30:00
47 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
48 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
49 2025-03-07 16:38:00  8.0   b   d 2025-03-07 18:42:00
50 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00
51 2025-03-07 17:42:00  8.0   b   d 2025-03-07 19:46:00

In [36]:
df_driver_list =DataFrame(df_driver)

In [37]:
if df_driver_list.empty:
    driver_dict = {}
    free_exict_list =  [f'kerowec_{i}' for i in range(1, 26)]
else:
    date_as_datetime = pd.to_datetime(date_of_request, format='%d.%m.%Y')
    df_driver_list.loc[:,'time'] = df_driver_list.loc[:,'time'].apply(lambda t: datetime.combine(date_as_datetime.date(), t))
    driver_dict = df_driver_list.set_index('person')['time'].to_dict()
    free_exict_list = []

In [38]:
driver_dict

{'MAN WJ2931G   Rusłan Skubi': Timestamp('2025-03-07 06:00:00'),
 'Marcin Zapora WD4163T': Timestamp('2025-03-07 06:10:00'),
 'WZ3193X - Kobiałka Zenon': Timestamp('2025-03-07 09:20:00'),
 'Piotr  Świeczka WZ568JA': Timestamp('2025-03-07 09:30:00'),
 'Tadeusz Malinowski WT5728E 719': Timestamp('2025-03-07 09:40:00'),
 'WG3122L Roman Gołędowski': Timestamp('2025-03-07 09:50:00'),
 'Tadeusz Podłog WT86086': Timestamp('2025-03-07 10:00:00'),
 'Oleksii Storchak WR835GX': Timestamp('2025-03-07 10:10:00'),
 'WG4986J kierowca Igor Isak': Timestamp('2025-03-07 10:20:00'),
 'ES TRANS Olek Przeniczny WPI 4444F': Timestamp('2025-03-07 10:30:00'),
 'Konrad Chomiuk WG4625L': Timestamp('2025-03-07 10:40:00'),
 'Erwin Pilarski WJ1281H': Timestamp('2025-03-07 10:50:00'),
 'Wojtek Rosiński   Man WGM 8XF3': Timestamp('2025-03-07 11:00:00'),
 'Olech Ivasenko     WG6635L': Timestamp('2025-03-07 11:10:00'),
 'Ilin Maksim Mercedes WD 1727U': Timestamp('2025-03-07 11:20:00'),
 'Mibet WWL 2800P Rusłan Hlotov': Timestamp('2025-03-07 11:30:00'),
 'Robert Henczel Mercedes WD4163T': Timestamp('2025-03-07 11:40:00'),
 'Mateusz Kobierski MAN TGS 35.260 WG1824L': Timestamp('2025-03-07 11:50:00'),
 'Vitalii Ushakou MAN CWL00829': Timestamp('2025-03-07 12:00:00'),
 'Grzegorz Skowron WU8890H': Timestamp('2025-03-07 12:10:00'),
 'Igor Hovorukha MAN TGS 32.400 WG8255K': Timestamp('2025-03-07 12:20:00'),
 'Kosior': Timestamp('2025-03-07 12:30:00')}

In [39]:
# list(df_driver_list['person'])

In [40]:
df=df_full_day.copy()

In [41]:
# executor_availability = {executor str: timestep d.Timedelta, ...}
executor_availability = driver_dict
# executor_availability = {}
# Добавление столбцов для исполнителей
df['Executors'] = None
df['Free Executors'] = None
df['Missing Executors'] = None

# Отслеживание свободных исполнителей
free_executors = free_exict_list
# free_executors = []
# free_executors = list(df_driver_list['person'])

# Текущие назначения исполнителей к заказам в виде словаря {order: (executor, order)}
current_assignments = {}

# Словарь для отслеживания периодов работы BRAK исполнителей
brak_intervals = {}

# Счетчик для недостатка исполнителей
brak_counter = 1

used_executors=[]
df['First'] = ''

In [42]:
# Для каждого временного шага
for current_time in df.index:
    start_executers = []
    # Обновляем список доступных исполнителей, учитывая начальное время готовности
    for executor, available_time in executor_availability.items():
        if available_time <= current_time and executor not in free_executors:
            if all(executor != assigned_exec for assigned_exec, _ in current_assignments.values()):
                    start_executers.append(executor)

        
    # Сначала освобождаем исполнителей от завершенных заданий
    completed_orders = [order for order, (executor, _) in current_assignments.items() if df[order].loc[current_time] == 0]
    for order in completed_orders:
        free_executor, _ = current_assignments.pop(order)
        if not free_executor.startswith('BRAK_KIEROWCA'):
            if df[order].shift(1).loc[current_time] == 'z':
                free_executors.insert(0, free_executor)
                while free_executor in used_executors:
                    used_executors.remove(free_executor)
            else:
                free_executors.append(free_executor)
        else:
            # Заканчиваем интервал работы текущего BRAK исполнителя
            brak_intervals[free_executor]['end'] = current_time

    # сортировка исполнителей 
    inserted = False

    if free_executors:
        for i, execu in enumerate(free_executors):
            if execu in used_executors:
                free_executors = free_executors[:i]+ start_executers + free_executors[i:]
                inserted = True
                break
        if not inserted:
            free_executors = free_executors + start_executers
    else:             
        free_executors = start_executers + free_executors        
    
    # Обрабатываем существующие заказы с исполнителями BRAKx
    for order, (executor, assigned_order) in current_assignments.items():
        if executor.startswith('BRAK_KIEROWCA') and free_executors:
            new_executor = free_executors.pop(0)
            current_assignments[order] = (new_executor, assigned_order)
            df.at[current_time, 'First'] = new_executor + f"::{str(df.at[current_time, 'First'])}"
            # Заканчиваем интервал работы текущего BRAK исполнителя
            brak_intervals[executor]['end'] = current_time
    
    # Назначение исполнителей на начинающиеся заказы
    missing_executors = []
    for order in df.columns[:-4]:  # исключаем столбцы 'Executors', 'Free Executors' и 'Missing Executors'
        if df[order].loc[current_time] != 0 and order not in current_assignments:
            if free_executors:
                current_executor = free_executors.pop(0)
            else:
                # Если нет свободных исполнителей, создаем нового с именем BRAKx
                current_executor = f'BRAK_KIEROWCA{brak_counter}'
                brak_counter += 1
                missing_executors.append((current_executor, order))
                # Начинаем интервал работы нового BRAK_KEROWCA исполнителя
                brak_intervals[current_executor] = {'start': current_time, 'end': None}

            if current_executor not in used_executors:
                df.at[current_time, 'First'] = current_executor + f"::{str(df.at[current_time, 'First'])}"
            used_executors.append(current_executor)
            
            current_assignments[order] = (current_executor, order)

    # Обновляем недостающих исполнителей в столбце Missing Executors
    missing_executors = [
        (executor, order) for order, (executor, _) in current_assignments.items()
        if executor.startswith('BRAK_KIEROWCA')
    ]
    
    # Запись исполнителей и выполняемых заказов в формате (Executor, Order)
    # executor_assignments = ', '.join(f"({executor}, {assigned_order})" for assigned_order, (executor, order) in current_assignments.items())
    str_current_assignment = str([(executor, assigned_order) for assigned_order, (executor, order) in current_assignments.items()])
    df.at[current_time, 'Executors'] = str_current_assignment

    # Запись списка свободных исполнителей
    str_free_executors = str(free_executors)
    df.at[current_time, 'Free Executors'] = str_free_executors
    
    # Запись списка недостающих исполнителей в новый столбец
    # missing_assignments = ', '.join(f"({executor}, {assigned_order})" for executor, assigned_order in missing_executors)
    missing_executors = str(missing_executors)
    df.at[current_time, 'Missing Executors'] = missing_executors

# Завершаем все интервалы, где end остался None
for brak_key, interval in brak_intervals.items():
    if interval['end'] is None:
        brak_intervals[brak_key]['end'] = df.index[-1]
        
# Просмотр результата
print("Intervалы недостающих исполнителей:")
for brak, interval in brak_intervals.items():
    print(f"{brak}: {interval['start']} - {interval['end']}")

Intervалы недостающих исполнителей:
BRAK_KIEROWCA1: 2025-03-07 08:18:00 - 2025-03-07 08:55:00
BRAK_KIEROWCA2: 2025-03-07 08:42:00 - 2025-03-07 09:19:00
BRAK_KIEROWCA3: 2025-03-07 09:06:00 - 2025-03-07 09:20:00

In [43]:
df[df[1]!=0]

,1,2,3,4,5,6,7,8,9,10,...,46,47,48,49,50,51,Executors,Free Executors,Missing Executors,First
2025-03-07 07:30:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1)]",['Marcin Zapora WD4163T'],[],MAN WJ2931G Rusłan Skubi::
2025-03-07 07:31:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1)]",['Marcin Zapora WD4163T'],[],
2025-03-07 07:32:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1)]",['Marcin Zapora WD4163T'],[],
2025-03-07 07:33:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1)]",['Marcin Zapora WD4163T'],[],
2025-03-07 07:34:00,b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1)]",['Marcin Zapora WD4163T'],[],
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-07 08:50:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1), ('Marcin Z...",[],"[('BRAK_KIEROWCA1', 3), ('BRAK_KIEROWCA2', 4)]",
2025-03-07 08:51:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1), ('Marcin Z...",[],"[('BRAK_KIEROWCA1', 3), ('BRAK_KIEROWCA2', 4)]",
2025-03-07 08:52:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1), ('Marcin Z...",[],"[('BRAK_KIEROWCA1', 3), ('BRAK_KIEROWCA2', 4)]",
2025-03-07 08:53:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1), ('Marcin Z...",[],"[('BRAK_KIEROWCA1', 3), ('BRAK_KIEROWCA2', 4)]",
2025-03-07 08:54:00,b,b,b,b,0,0,0,0,0,0,...,0,0,0,0,0,0,"[('MAN WJ2931G Rusłan Skubi', 1), ('Marcin Z...",[],"[('BRAK_KIEROWCA1', 3), ('BRAK_KIEROWCA2', 4)]",

In [44]:
df.iloc[150:200]

,1,2,3,4,5,6,7,8,9,10,...,46,47,48,49,50,51,Executors,Free Executors,Missing Executors,First
2025-03-07 06:30:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:31:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:32:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:33:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:34:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:35:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:36:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:37:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:38:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:39:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:40:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:41:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:42:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:43:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:44:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:45:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:46:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:47:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:48:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:49:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:50:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:51:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:52:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:53:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:54:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:55:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:01:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:02:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:03:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:04:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:05:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:06:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:07:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:08:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:09:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:10:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:11:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:12:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:13:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:14:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:16:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:17:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:18:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 07:19:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],

In [45]:
df.iloc[100:150]

,1,2,3,4,5,6,7,8,9,10,...,46,47,48,49,50,51,Executors,Free Executors,Missing Executors,First
2025-03-07 05:40:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:41:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:42:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:43:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:44:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:45:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:46:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:47:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:48:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:49:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:50:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:51:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:52:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:53:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:54:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:55:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 05:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],[],[],
2025-03-07 06:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:01:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:02:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:03:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:04:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:05:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:06:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:07:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:08:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:09:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],['MAN WJ2931G Rusłan Skubi'],[],
2025-03-07 06:10:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:11:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:12:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:13:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:14:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:16:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:17:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:18:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:19:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:20:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:21:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:22:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:23:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:24:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:25:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:26:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:27:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:28:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],
2025-03-07 06:29:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,[],"['MAN WJ2931G Rusłan Skubi', 'Marcin Zapora ...",[],

In [46]:
df.replace('[]',np.nan, inplace=True)

In [47]:
df.replace('',np.nan, inplace=True)

In [48]:
list_starts = df["First"][df["First"].notna()]
list_starts

2025-03-07 07:30:00                         MAN WJ2931G   Rusłan Skubi::
2025-03-07 07:54:00                              Marcin Zapora WD4163T::
2025-03-07 08:18:00                                     BRAK_KIEROWCA1::
2025-03-07 08:42:00                                     BRAK_KIEROWCA2::
2025-03-07 08:55:00                         MAN WJ2931G   Rusłan Skubi::
2025-03-07 09:06:00                                     BRAK_KIEROWCA3::
2025-03-07 09:19:00                              Marcin Zapora WD4163T::
2025-03-07 09:20:00                           WZ3193X - Kobiałka Zenon::
2025-03-07 09:30:00                            Piotr  Świeczka WZ568JA::
2025-03-07 09:54:00                     Tadeusz Malinowski WT5728E 719::
2025-03-07 10:18:00                           WG3122L Roman Gołędowski::
2025-03-07 10:42:00                             Tadeusz Podłog WT86086::
2025-03-07 11:06:00                           Oleksii Storchak WR835GX::
2025-03-07 11:30:00    ES TRANS Olek Przeniczny WPI 4444F::WG4986J ki...
2025-03-07 11:54:00     Erwin Pilarski WJ1281H::Konrad Chomiuk WG4625L::
2025-03-07 12:18:00    Olech Ivasenko     WG6635L::Wojtek Rosiński   ...
2025-03-07 12:42:00    Mibet WWL 2800P Rusłan Hlotov::Ilin Maksim Mer...
2025-03-07 13:00:00                    Robert Henczel Mercedes WD4163T::
2025-03-07 13:06:00           Mateusz Kobierski MAN TGS 35.260 WG1824L::
2025-03-07 13:24:00                       Vitalii Ushakou MAN CWL00829::
2025-03-07 13:30:00                           Grzegorz Skowron WU8890H::
2025-03-07 13:48:00              Igor Hovorukha MAN TGS 32.400 WG8255K::
2025-03-07 13:54:00                                             Kosior::
2025-03-07 14:30:00                           WZ3193X - Kobiałka Zenon::
Name: First, dtype: object

In [49]:
list_starts = list_starts.str.split("::")

In [50]:
list_starts

2025-03-07 07:30:00                       [MAN WJ2931G   Rusłan Skubi, ]
2025-03-07 07:54:00                            [Marcin Zapora WD4163T, ]
2025-03-07 08:18:00                                   [BRAK_KIEROWCA1, ]
2025-03-07 08:42:00                                   [BRAK_KIEROWCA2, ]
2025-03-07 08:55:00                       [MAN WJ2931G   Rusłan Skubi, ]
2025-03-07 09:06:00                                   [BRAK_KIEROWCA3, ]
2025-03-07 09:19:00                            [Marcin Zapora WD4163T, ]
2025-03-07 09:20:00                         [WZ3193X - Kobiałka Zenon, ]
2025-03-07 09:30:00                          [Piotr  Świeczka WZ568JA, ]
2025-03-07 09:54:00                   [Tadeusz Malinowski WT5728E 719, ]
2025-03-07 10:18:00                         [WG3122L Roman Gołędowski, ]
2025-03-07 10:42:00                           [Tadeusz Podłog WT86086, ]
2025-03-07 11:06:00                         [Oleksii Storchak WR835GX, ]
2025-03-07 11:30:00    [ES TRANS Olek Przeniczny WPI 4444F, WG4986J k...
2025-03-07 11:54:00    [Erwin Pilarski WJ1281H, Konrad Chomiuk WG4625...
2025-03-07 12:18:00    [Olech Ivasenko     WG6635L, Wojtek Rosiński  ...
2025-03-07 12:42:00    [Mibet WWL 2800P Rusłan Hlotov, Ilin Maksim Me...
2025-03-07 13:00:00                  [Robert Henczel Mercedes WD4163T, ]
2025-03-07 13:06:00         [Mateusz Kobierski MAN TGS 35.260 WG1824L, ]
2025-03-07 13:24:00                     [Vitalii Ushakou MAN CWL00829, ]
2025-03-07 13:30:00                         [Grzegorz Skowron WU8890H, ]
2025-03-07 13:48:00            [Igor Hovorukha MAN TGS 32.400 WG8255K, ]
2025-03-07 13:54:00                                           [Kosior, ]
2025-03-07 14:30:00                         [WZ3193X - Kobiałka Zenon, ]
Name: First, dtype: object

In [51]:
list_starts = list_starts.explode()

In [52]:
list_starts

2025-03-07 07:30:00                  MAN WJ2931G   Rusłan Skubi
2025-03-07 07:30:00
2025-03-07 07:54:00                       Marcin Zapora WD4163T
2025-03-07 07:54:00
2025-03-07 08:18:00                              BRAK_KIEROWCA1
2025-03-07 08:18:00
2025-03-07 08:42:00                              BRAK_KIEROWCA2
2025-03-07 08:42:00
2025-03-07 08:55:00                  MAN WJ2931G   Rusłan Skubi
2025-03-07 08:55:00
2025-03-07 09:06:00                              BRAK_KIEROWCA3
2025-03-07 09:06:00
2025-03-07 09:19:00                       Marcin Zapora WD4163T
2025-03-07 09:19:00
2025-03-07 09:20:00                    WZ3193X - Kobiałka Zenon
2025-03-07 09:20:00
2025-03-07 09:30:00                     Piotr  Świeczka WZ568JA
2025-03-07 09:30:00
2025-03-07 09:54:00              Tadeusz Malinowski WT5728E 719
2025-03-07 09:54:00
2025-03-07 10:18:00                    WG3122L Roman Gołędowski
2025-03-07 10:18:00
2025-03-07 10:42:00                      Tadeusz Podłog WT86086
2025-03-07 10:42:00
2025-03-07 11:06:00                    Oleksii Storchak WR835GX
2025-03-07 11:06:00
2025-03-07 11:30:00          ES TRANS Olek Przeniczny WPI 4444F
2025-03-07 11:30:00                  WG4986J kierowca Igor Isak
2025-03-07 11:30:00
2025-03-07 11:54:00                      Erwin Pilarski WJ1281H
2025-03-07 11:54:00                      Konrad Chomiuk WG4625L
2025-03-07 11:54:00
2025-03-07 12:18:00                  Olech Ivasenko     WG6635L
2025-03-07 12:18:00              Wojtek Rosiński   Man WGM 8XF3
2025-03-07 12:18:00
2025-03-07 12:42:00               Mibet WWL 2800P Rusłan Hlotov
2025-03-07 12:42:00               Ilin Maksim Mercedes WD 1727U
2025-03-07 12:42:00
2025-03-07 13:00:00             Robert Henczel Mercedes WD4163T
2025-03-07 13:00:00
2025-03-07 13:06:00    Mateusz Kobierski MAN TGS 35.260 WG1824L
2025-03-07 13:06:00
2025-03-07 13:24:00                Vitalii Ushakou MAN CWL00829
2025-03-07 13:24:00
2025-03-07 13:30:00                    Grzegorz Skowron WU8890H
2025-03-07 13:30:00
2025-03-07 13:48:00       Igor Hovorukha MAN TGS 32.400 WG8255K
2025-03-07 13:48:00
2025-03-07 13:54:00                                      Kosior
2025-03-07 13:54:00
2025-03-07 14:30:00                    WZ3193X - Kobiałka Zenon
2025-03-07 14:30:00
Name: First, dtype: object

In [53]:
list_starts.replace('',np.nan, inplace=True)

In [54]:
list_starts = list_starts.dropna()

In [55]:
list_starts

2025-03-07 07:30:00                  MAN WJ2931G   Rusłan Skubi
2025-03-07 07:54:00                       Marcin Zapora WD4163T
2025-03-07 08:18:00                              BRAK_KIEROWCA1
2025-03-07 08:42:00                              BRAK_KIEROWCA2
2025-03-07 08:55:00                  MAN WJ2931G   Rusłan Skubi
2025-03-07 09:06:00                              BRAK_KIEROWCA3
2025-03-07 09:19:00                       Marcin Zapora WD4163T
2025-03-07 09:20:00                    WZ3193X - Kobiałka Zenon
2025-03-07 09:30:00                     Piotr  Świeczka WZ568JA
2025-03-07 09:54:00              Tadeusz Malinowski WT5728E 719
2025-03-07 10:18:00                    WG3122L Roman Gołędowski
2025-03-07 10:42:00                      Tadeusz Podłog WT86086
2025-03-07 11:06:00                    Oleksii Storchak WR835GX
2025-03-07 11:30:00          ES TRANS Olek Przeniczny WPI 4444F
2025-03-07 11:30:00                  WG4986J kierowca Igor Isak
2025-03-07 11:54:00                      Erwin Pilarski WJ1281H
2025-03-07 11:54:00                      Konrad Chomiuk WG4625L
2025-03-07 12:18:00                  Olech Ivasenko     WG6635L
2025-03-07 12:18:00              Wojtek Rosiński   Man WGM 8XF3
2025-03-07 12:42:00               Mibet WWL 2800P Rusłan Hlotov
2025-03-07 12:42:00               Ilin Maksim Mercedes WD 1727U
2025-03-07 13:00:00             Robert Henczel Mercedes WD4163T
2025-03-07 13:06:00    Mateusz Kobierski MAN TGS 35.260 WG1824L
2025-03-07 13:24:00                Vitalii Ushakou MAN CWL00829
2025-03-07 13:30:00                    Grzegorz Skowron WU8890H
2025-03-07 13:48:00       Igor Hovorukha MAN TGS 32.400 WG8255K
2025-03-07 13:54:00                                      Kosior
2025-03-07 14:30:00                    WZ3193X - Kobiałka Zenon
Name: First, dtype: object

In [56]:
list_starts= list_starts.reset_index()

In [57]:
list_starts

                 index                                     First
0  2025-03-07 07:30:00                MAN WJ2931G   Rusłan Skubi
1  2025-03-07 07:54:00                     Marcin Zapora WD4163T
2  2025-03-07 08:18:00                            BRAK_KIEROWCA1
3  2025-03-07 08:42:00                            BRAK_KIEROWCA2
4  2025-03-07 08:55:00                MAN WJ2931G   Rusłan Skubi
5  2025-03-07 09:06:00                            BRAK_KIEROWCA3
6  2025-03-07 09:19:00                     Marcin Zapora WD4163T
7  2025-03-07 09:20:00                  WZ3193X - Kobiałka Zenon
8  2025-03-07 09:30:00                   Piotr  Świeczka WZ568JA
9  2025-03-07 09:54:00            Tadeusz Malinowski WT5728E 719
10 2025-03-07 10:18:00                  WG3122L Roman Gołędowski
11 2025-03-07 10:42:00                    Tadeusz Podłog WT86086
12 2025-03-07 11:06:00                  Oleksii Storchak WR835GX
13 2025-03-07 11:30:00        ES TRANS Olek Przeniczny WPI 4444F
14 2025-03-07 11:30:00                WG4986J kierowca Igor Isak
15 2025-03-07 11:54:00                    Erwin Pilarski WJ1281H
16 2025-03-07 11:54:00                    Konrad Chomiuk WG4625L
17 2025-03-07 12:18:00                Olech Ivasenko     WG6635L
18 2025-03-07 12:18:00            Wojtek Rosiński   Man WGM 8XF3
19 2025-03-07 12:42:00             Mibet WWL 2800P Rusłan Hlotov
20 2025-03-07 12:42:00             Ilin Maksim Mercedes WD 1727U
21 2025-03-07 13:00:00           Robert Henczel Mercedes WD4163T
22 2025-03-07 13:06:00  Mateusz Kobierski MAN TGS 35.260 WG1824L
23 2025-03-07 13:24:00              Vitalii Ushakou MAN CWL00829
24 2025-03-07 13:30:00                  Grzegorz Skowron WU8890H
25 2025-03-07 13:48:00     Igor Hovorukha MAN TGS 32.400 WG8255K
26 2025-03-07 13:54:00                                    Kosior
27 2025-03-07 14:30:00                  WZ3193X - Kobiałka Zenon

In [58]:
list_starts.rename(columns={'index':'time', 'First':'person'}, inplace=True)

In [59]:
list_starts

                  time                                    person
0  2025-03-07 07:30:00                MAN WJ2931G   Rusłan Skubi
1  2025-03-07 07:54:00                     Marcin Zapora WD4163T
2  2025-03-07 08:18:00                            BRAK_KIEROWCA1
3  2025-03-07 08:42:00                            BRAK_KIEROWCA2
4  2025-03-07 08:55:00                MAN WJ2931G   Rusłan Skubi
5  2025-03-07 09:06:00                            BRAK_KIEROWCA3
6  2025-03-07 09:19:00                     Marcin Zapora WD4163T
7  2025-03-07 09:20:00                  WZ3193X - Kobiałka Zenon
8  2025-03-07 09:30:00                   Piotr  Świeczka WZ568JA
9  2025-03-07 09:54:00            Tadeusz Malinowski WT5728E 719
10 2025-03-07 10:18:00                  WG3122L Roman Gołędowski
11 2025-03-07 10:42:00                    Tadeusz Podłog WT86086
12 2025-03-07 11:06:00                  Oleksii Storchak WR835GX
13 2025-03-07 11:30:00        ES TRANS Olek Przeniczny WPI 4444F
14 2025-03-07 11:30:00                WG4986J kierowca Igor Isak
15 2025-03-07 11:54:00                    Erwin Pilarski WJ1281H
16 2025-03-07 11:54:00                    Konrad Chomiuk WG4625L
17 2025-03-07 12:18:00                Olech Ivasenko     WG6635L
18 2025-03-07 12:18:00            Wojtek Rosiński   Man WGM 8XF3
19 2025-03-07 12:42:00             Mibet WWL 2800P Rusłan Hlotov
20 2025-03-07 12:42:00             Ilin Maksim Mercedes WD 1727U
21 2025-03-07 13:00:00           Robert Henczel Mercedes WD4163T
22 2025-03-07 13:06:00  Mateusz Kobierski MAN TGS 35.260 WG1824L
23 2025-03-07 13:24:00              Vitalii Ushakou MAN CWL00829
24 2025-03-07 13:30:00                  Grzegorz Skowron WU8890H
25 2025-03-07 13:48:00     Igor Hovorukha MAN TGS 32.400 WG8255K
26 2025-03-07 13:54:00                                    Kosior
27 2025-03-07 14:30:00                  WZ3193X - Kobiałka Zenon

In [60]:
def str_to_list(s):
    return eval(s)

In [61]:
df_executors =  df['Executors'].dropna()

In [62]:
df_executors  = df_executors.apply(str_to_list)

In [63]:
expanded_rows = df_executors.explode()

In [64]:
expanded_rows = expanded_rows.drop_duplicates()

In [65]:
expanded_df = pd.DataFrame(expanded_rows.tolist(), columns=['person', 'N% kursów'])

In [66]:
expanded_df

                                      person  N% kursów
0                 MAN WJ2931G   Rusłan Skubi          1
1                      Marcin Zapora WD4163T          2
2                             BRAK_KIEROWCA1          3
3                             BRAK_KIEROWCA2          4
4                 MAN WJ2931G   Rusłan Skubi          3
5                             BRAK_KIEROWCA3          5
6                      Marcin Zapora WD4163T          4
7                   WZ3193X - Kobiałka Zenon          5
8                    Piotr  Świeczka WZ568JA          6
9             Tadeusz Malinowski WT5728E 719          7
10                  WG3122L Roman Gołędowski          8
11                    Tadeusz Podłog WT86086          9
12                  Oleksii Storchak WR835GX         10
13                WG4986J kierowca Igor Isak         11
14        ES TRANS Olek Przeniczny WPI 4444F         12
15                    Konrad Chomiuk WG4625L         13
16                    Erwin Pilarski WJ1281H         14
17            Wojtek Rosiński   Man WGM 8XF3         15
18                Olech Ivasenko     WG6635L         16
19             Ilin Maksim Mercedes WD 1727U         17
20             Mibet WWL 2800P Rusłan Hlotov         18
21           Robert Henczel Mercedes WD4163T         19
22  Mateusz Kobierski MAN TGS 35.260 WG1824L         20
23              Vitalii Ushakou MAN CWL00829         21
24                  Grzegorz Skowron WU8890H         22
25     Igor Hovorukha MAN TGS 32.400 WG8255K         23
26                                    Kosior         24
27                MAN WJ2931G   Rusłan Skubi         25
28                     Marcin Zapora WD4163T         26
29                  WZ3193X - Kobiałka Zenon         27
30                   Piotr  Świeczka WZ568JA         28
31            Tadeusz Malinowski WT5728E 719         29
32                  WG3122L Roman Gołędowski         30
33                    Tadeusz Podłog WT86086         31
34                  Oleksii Storchak WR835GX         32
35                WG4986J kierowca Igor Isak         33
36        ES TRANS Olek Przeniczny WPI 4444F         34
37                    Konrad Chomiuk WG4625L         35
38                    Erwin Pilarski WJ1281H         36
39            Wojtek Rosiński   Man WGM 8XF3         37
40                Olech Ivasenko     WG6635L         38
41             Mibet WWL 2800P Rusłan Hlotov         39
42             Ilin Maksim Mercedes WD 1727U         40
43           Robert Henczel Mercedes WD4163T         41
44  Mateusz Kobierski MAN TGS 35.260 WG1824L         42
45              Vitalii Ushakou MAN CWL00829         43
46                  Grzegorz Skowron WU8890H         44
47     Igor Hovorukha MAN TGS 32.400 WG8255K         45
48                                    Kosior         46
49                MAN WJ2931G   Rusłan Skubi         47
50                     Marcin Zapora WD4163T         48
51                  Oleksii Storchak WR835GX         49
52                WG4986J kierowca Igor Isak         50
53        ES TRANS Olek Przeniczny WPI 4444F         51

In [67]:
expanded_df_rezult = expanded_df.groupby('person')['N% kursów'].apply(list).reset_index()

In [68]:
expanded_df_rezult

                                      person       N% kursów
0                             BRAK_KIEROWCA1             [3]
1                             BRAK_KIEROWCA2             [4]
2                             BRAK_KIEROWCA3             [5]
3         ES TRANS Olek Przeniczny WPI 4444F    [12, 34, 51]
4                     Erwin Pilarski WJ1281H        [14, 36]
5                   Grzegorz Skowron WU8890H        [22, 44]
6      Igor Hovorukha MAN TGS 32.400 WG8255K        [23, 45]
7              Ilin Maksim Mercedes WD 1727U        [17, 40]
8                     Konrad Chomiuk WG4625L        [13, 35]
9                                     Kosior        [24, 46]
10                MAN WJ2931G   Rusłan Skubi  [1, 3, 25, 47]
11                     Marcin Zapora WD4163T  [2, 4, 26, 48]
12  Mateusz Kobierski MAN TGS 35.260 WG1824L        [20, 42]
13             Mibet WWL 2800P Rusłan Hlotov        [18, 39]
14                Olech Ivasenko     WG6635L        [16, 38]
15                  Oleksii Storchak WR835GX    [10, 32, 49]
16                   Piotr  Świeczka WZ568JA         [6, 28]
17           Robert Henczel Mercedes WD4163T        [19, 41]
18            Tadeusz Malinowski WT5728E 719         [7, 29]
19                    Tadeusz Podłog WT86086         [9, 31]
20              Vitalii Ushakou MAN CWL00829        [21, 43]
21                  WG3122L Roman Gołędowski         [8, 30]
22                WG4986J kierowca Igor Isak    [11, 33, 50]
23                  WZ3193X - Kobiałka Zenon         [5, 27]
24            Wojtek Rosiński   Man WGM 8XF3        [15, 37]

In [69]:
result_df_end = pd.merge(list_starts, expanded_df_rezult, on='person', how='left')

In [70]:
result_df_end = result_df_end.drop_duplicates(subset='person')

In [71]:
result_df_end

,time,person,N% kursów
0,2025-03-07 07:30:00,MAN WJ2931G Rusłan Skubi,"[1, 3, 25, 47]"
1,2025-03-07 07:54:00,Marcin Zapora WD4163T,"[2, 4, 26, 48]"
2,2025-03-07 08:18:00,BRAK_KIEROWCA1,[3]
3,2025-03-07 08:42:00,BRAK_KIEROWCA2,[4]
5,2025-03-07 09:06:00,BRAK_KIEROWCA3,[5]
7,2025-03-07 09:20:00,WZ3193X - Kobiałka Zenon,"[5, 27]"
8,2025-03-07 09:30:00,Piotr Świeczka WZ568JA,"[6, 28]"
9,2025-03-07 09:54:00,Tadeusz Malinowski WT5728E 719,"[7, 29]"
10,2025-03-07 10:18:00,WG3122L Roman Gołędowski,"[8, 30]"
11,2025-03-07 10:42:00,Tadeusz Podłog WT86086,"[9, 31]"
12,2025-03-07 11:06:00,Oleksii Storchak WR835GX,"[10, 32, 49]"
13,2025-03-07 11:30:00,ES TRANS Olek Przeniczny WPI 4444F,"[12, 34, 51]"
14,2025-03-07 11:30:00,WG4986J kierowca Igor Isak,"[11, 33, 50]"
15,2025-03-07 11:54:00,Erwin Pilarski WJ1281H,"[14, 36]"
16,2025-03-07 11:54:00,Konrad Chomiuk WG4625L,"[13, 35]"
17,2025-03-07 12:18:00,Olech Ivasenko WG6635L,"[16, 38]"
18,2025-03-07 12:18:00,Wojtek Rosiński Man WGM 8XF3,"[15, 37]"
19,2025-03-07 12:42:00,Mibet WWL 2800P Rusłan Hlotov,"[18, 39]"
20,2025-03-07 12:42:00,Ilin Maksim Mercedes WD 1727U,"[17, 40]"
21,2025-03-07 13:00:00,Robert Henczel Mercedes WD4163T,"[19, 41]"
22,2025-03-07 13:06:00,Mateusz Kobierski MAN TGS 35.260 WG1824L,"[20, 42]"
23,2025-03-07 13:24:00,Vitalii Ushakou MAN CWL00829,"[21, 43]"
24,2025-03-07 13:30:00,Grzegorz Skowron WU8890H,"[22, 44]"
25,2025-03-07 13:48:00,Igor Hovorukha MAN TGS 32.400 WG8255K,"[23, 45]"
26,2025-03-07 13:54:00,Kosior,"[24, 46]"

In [72]:
result_df_end['N% kursów_first'] = result_df_end["N% kursów"].apply(lambda x: x[0])

In [73]:
# Сортировка
result_df_end.sort_values(by=["time", "N% kursów_first"], inplace=True)

In [74]:
result_df_end.drop(columns='N% kursów_first', inplace=True)

In [75]:
result_df_end

,time,person,N% kursów
0,2025-03-07 07:30:00,MAN WJ2931G Rusłan Skubi,"[1, 3, 25, 47]"
1,2025-03-07 07:54:00,Marcin Zapora WD4163T,"[2, 4, 26, 48]"
2,2025-03-07 08:18:00,BRAK_KIEROWCA1,[3]
3,2025-03-07 08:42:00,BRAK_KIEROWCA2,[4]
5,2025-03-07 09:06:00,BRAK_KIEROWCA3,[5]
7,2025-03-07 09:20:00,WZ3193X - Kobiałka Zenon,"[5, 27]"
8,2025-03-07 09:30:00,Piotr Świeczka WZ568JA,"[6, 28]"
9,2025-03-07 09:54:00,Tadeusz Malinowski WT5728E 719,"[7, 29]"
10,2025-03-07 10:18:00,WG3122L Roman Gołędowski,"[8, 30]"
11,2025-03-07 10:42:00,Tadeusz Podłog WT86086,"[9, 31]"
12,2025-03-07 11:06:00,Oleksii Storchak WR835GX,"[10, 32, 49]"
14,2025-03-07 11:30:00,WG4986J kierowca Igor Isak,"[11, 33, 50]"
13,2025-03-07 11:30:00,ES TRANS Olek Przeniczny WPI 4444F,"[12, 34, 51]"
16,2025-03-07 11:54:00,Konrad Chomiuk WG4625L,"[13, 35]"
15,2025-03-07 11:54:00,Erwin Pilarski WJ1281H,"[14, 36]"
18,2025-03-07 12:18:00,Wojtek Rosiński Man WGM 8XF3,"[15, 37]"
17,2025-03-07 12:18:00,Olech Ivasenko WG6635L,"[16, 38]"
20,2025-03-07 12:42:00,Ilin Maksim Mercedes WD 1727U,"[17, 40]"
19,2025-03-07 12:42:00,Mibet WWL 2800P Rusłan Hlotov,"[18, 39]"
21,2025-03-07 13:00:00,Robert Henczel Mercedes WD4163T,"[19, 41]"
22,2025-03-07 13:06:00,Mateusz Kobierski MAN TGS 35.260 WG1824L,"[20, 42]"
23,2025-03-07 13:24:00,Vitalii Ushakou MAN CWL00829,"[21, 43]"
24,2025-03-07 13:30:00,Grzegorz Skowron WU8890H,"[22, 44]"
25,2025-03-07 13:48:00,Igor Hovorukha MAN TGS 32.400 WG8255K,"[23, 45]"
26,2025-03-07 13:54:00,Kosior,"[24, 46]"

In [76]:
result_df_end['time'] = result_df_end['time'].apply(lambda x: x.strftime('%H:%M'))

In [77]:
result_df_end.rename({'person':'Kerowca','N% kursów':'kursy'}, axis=1, inplace=True)

In [78]:
result_df_end.reset_index(drop=True, inplace=True)

In [79]:
result_df_end.index=result_df_end.index+1

In [80]:
result_df_end

     time                                   Kerowca           kursy
1   07:30                MAN WJ2931G   Rusłan Skubi  [1, 3, 25, 47]
2   07:54                     Marcin Zapora WD4163T  [2, 4, 26, 48]
3   08:18                            BRAK_KIEROWCA1             [3]
4   08:42                            BRAK_KIEROWCA2             [4]
5   09:06                            BRAK_KIEROWCA3             [5]
6   09:20                  WZ3193X - Kobiałka Zenon         [5, 27]
7   09:30                   Piotr  Świeczka WZ568JA         [6, 28]
8   09:54            Tadeusz Malinowski WT5728E 719         [7, 29]
9   10:18                  WG3122L Roman Gołędowski         [8, 30]
10  10:42                    Tadeusz Podłog WT86086         [9, 31]
11  11:06                  Oleksii Storchak WR835GX    [10, 32, 49]
12  11:30                WG4986J kierowca Igor Isak    [11, 33, 50]
13  11:30        ES TRANS Olek Przeniczny WPI 4444F    [12, 34, 51]
14  11:54                    Konrad Chomiuk WG4625L        [13, 35]
15  11:54                    Erwin Pilarski WJ1281H        [14, 36]
16  12:18            Wojtek Rosiński   Man WGM 8XF3        [15, 37]
17  12:18                Olech Ivasenko     WG6635L        [16, 38]
18  12:42             Ilin Maksim Mercedes WD 1727U        [17, 40]
19  12:42             Mibet WWL 2800P Rusłan Hlotov        [18, 39]
20  13:00           Robert Henczel Mercedes WD4163T        [19, 41]
21  13:06  Mateusz Kobierski MAN TGS 35.260 WG1824L        [20, 42]
22  13:24              Vitalii Ushakou MAN CWL00829        [21, 43]
23  13:30                  Grzegorz Skowron WU8890H        [22, 44]
24  13:48     Igor Hovorukha MAN TGS 32.400 WG8255K        [23, 45]
25  13:54                                    Kosior        [24, 46]

In [81]:
result_df_end['Kerowca'] = result_df_end['Kerowca'].apply(lambda x: f'<span style="font-weight: bold; color:rgb(255, 0, 0);">{str(x)}</span>' if x.startswith('BRAK_KIEROWCA') else x)

In [82]:
result_df_end

     time                                            Kerowca           kursy
1   07:30                         MAN WJ2931G   Rusłan Skubi  [1, 3, 25, 47]
2   07:54                              Marcin Zapora WD4163T  [2, 4, 26, 48]
3   08:18  <span style="font-weight: bold; color:rgb(255,...             [3]
4   08:42  <span style="font-weight: bold; color:rgb(255,...             [4]
5   09:06  <span style="font-weight: bold; color:rgb(255,...             [5]
6   09:20                           WZ3193X - Kobiałka Zenon         [5, 27]
7   09:30                            Piotr  Świeczka WZ568JA         [6, 28]
8   09:54                     Tadeusz Malinowski WT5728E 719         [7, 29]
9   10:18                           WG3122L Roman Gołędowski         [8, 30]
10  10:42                             Tadeusz Podłog WT86086         [9, 31]
11  11:06                           Oleksii Storchak WR835GX    [10, 32, 49]
12  11:30                         WG4986J kierowca Igor Isak    [11, 33, 50]
13  11:30                 ES TRANS Olek Przeniczny WPI 4444F    [12, 34, 51]
14  11:54                             Konrad Chomiuk WG4625L        [13, 35]
15  11:54                             Erwin Pilarski WJ1281H        [14, 36]
16  12:18                     Wojtek Rosiński   Man WGM 8XF3        [15, 37]
17  12:18                         Olech Ivasenko     WG6635L        [16, 38]
18  12:42                      Ilin Maksim Mercedes WD 1727U        [17, 40]
19  12:42                      Mibet WWL 2800P Rusłan Hlotov        [18, 39]
20  13:00                    Robert Henczel Mercedes WD4163T        [19, 41]
21  13:06           Mateusz Kobierski MAN TGS 35.260 WG1824L        [20, 42]
22  13:24                       Vitalii Ushakou MAN CWL00829        [21, 43]
23  13:30                           Grzegorz Skowron WU8890H        [22, 44]
24  13:48              Igor Hovorukha MAN TGS 32.400 WG8255K        [23, 45]
25  13:54                                             Kosior        [24, 46]

In [82]:
html_table = result_df_end.to_html(index=True,table_id="rozklad_kerowca",classes='rozklad_kerowca_tab', border=0, justify='center')

In [84]:
html_table

'<table class="dataframe rozklad_kerowca_tab" id="rozklad_kerowca">\n  <thead>\n    <tr style="text-align: center;">\n      <th></th>\n      <th>time</th>\n      <th>person</th>\n      <th>N% kursów</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>06:30</td>\n      <td>Kosior</td>\n      <td>[2, 3, 26]</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>06:30</td>\n      <td>MAN WJ2931G   Rusłan Skubi</td>\n      <td>[1, 4, 27]</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>07:00</td>\n      <td>BRAK1</td>\n      <td>[3]</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>07:24</td>\n      <td>BRAK2</td>\n      <td>[4]</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>10:30</td>\n      <td>Marcin Zapora WD4163T</td>\n      <td>[5, 28]</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>10:54</td>\n      <td>Piotr  Świeczka WZ568JA</td>\n      <td>[6, 29]</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>11:18</td>\n      <td>WG3122L Roman Gołędowski</td>\n      <td>[7, 30]</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>11:30</td>\n      <td>Tadeusz Malinowski WT5728E 719</td>\n      <td>[10, 32]</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>11:30</td>\n      <td>Tadeusz Podłog WT86086</td>\n      <td>[9, 36]</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>11:30</td>\n      <td>Oleksii Storchak WR835GX</td>\n      <td>[8, 31]</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>11:42</td>\n      <td>WG4986J kierowca Igor Isak</td>\n      <td>[11, 33]</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>11:54</td>\n      <td>Tomasz Kryszak WT1926G do godz. 16:00</td>\n      <td>[12, 34]</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>12:06</td>\n      <td>ES TRANS Olek Przeniczny WPI 4444F</td>\n      <td>[13, 35]</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>12:30</td>\n      <td>Konrad Chomiuk WG4625L</td>\n      <td>[16]</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>12:30</td>\n      <td>Erwin Pilarski WJ1281H</td>\n      <td>[15]</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>12:30</td>\n      <td>Wojtek Rosiński   Man WGM 8XF3</td>\n      <td>[14, 37]</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>12:54</td>\n      <td>Olech Ivasenko     WG6635L</td>\n      <td>[18]</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>12:54</td>\n      <td>Ilin Maksim Mercedes WD 1727U</td>\n      <td>[17]</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>13:00</td>\n      <td>Mibet WWL 2800P Rusłan Hlotov</td>\n      <td>[19]</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>13:34</td>\n      <td>Vitalii Ushakou MAN CWL00829</td>\n      <td>[20]</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>14:30</td>\n      <td>WZ3193X - Kobiałka Zenon</td>\n      <td>[25]</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>14:30</td>\n      <td>Robert Henczel Mercedes WD4163T</td>\n      <td>[24]</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>14:30</td>\n      <td>Mateusz Kobierski MAN TGS 35.260 WG1824L</td>\n      <td>[23]</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>14:30</td>\n      <td>Grzegorz Skowron WU8890H</td>\n      <td>[22]</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>14:30</td>\n      <td>Igor Hovorukha MAN TGS 32.400 WG8255K</td>\n      <td>[21]</td>\n    </tr>\n  </tbody>\n</table>'

In [76]:
# free_executors = []
free_executors = list(df_driver_list['person'])
current_assignments = {}
used_executors=[]
brak_counter = 1
df['First'] = ''

In [77]:
for current_time in df.index:
    # Сначала освобождаем исполнителей от завершенных заданий
    completed_orders = [order for order, (executor, assigned_order) in current_assignments.items() if df[order].loc[current_time] == 0]
    for order in completed_orders:
        free_executor, _ = current_assignments.pop(order)
        if df[order].shift(1).loc[current_time] == 'z':
            free_executors.insert(0, free_executor)
        else:
            free_executors.append(free_executor)
    
    # Назначение исполнителей на начинающиеся заказы
    missing_executors = []
    for order in df.columns[:-4]:  # исключаем столбцы 'Executors', 'Free Executors' и 'Missing Executors'
        if df[order].loc[current_time] != 0 and order not in current_assignments:
            if free_executors:
                current_executor = free_executors.pop(0)
            else:
                # Если нет свободных исполнителей, создаем нового с именем BRAKx
                current_executor = f'BRAK{brak_counter}'
                brak_counter += 1
                missing_executors.append((current_executor, order))
                
            if current_executor not in used_executors:
                df.at[current_time, 'First'] = current_executor + f":: {str(df.at[current_time, 'First'])}"
            used_executors.append(current_executor)

            current_assignments[order] = (current_executor, order)
    
    # Запись исполнителей и выполняемых заказов в формате (Executor, Order)
    # executor_assignments = ', '.join(f"({executor}, {assigned_order})" for assigned_order, (executor, order) in current_assignments.items())
    str_current_assignment = str([(executor, assigned_order) for assigned_order, (executor, order) in current_assignments.items()])
    df.at[current_time, 'Executors'] = str_current_assignment

    # Запись списка свободных исполнителей
    str_free_executors = str(free_executors)
    df.at[current_time, 'Free Executors'] = str_free_executors
    
    # Запись списка недостающих исполнителей в новый столбец
    # missing_assignments = ', '.join(f"({executor}, {assigned_order})" for executor, assigned_order in missing_executors)
    missing_executors = str(missing_executors)
    df.at[current_time, 'Missing Executors'] = missing_executors

In [78]:
used_executors

['Kosior',
 'MAN WJ2931G   Rusłan Skubi',
 'Marcin Zapora WD4163T',
 'WZ3193X - Kobiałka Zenon',
 'Kosior',
 'MAN WJ2931G   Rusłan Skubi',
 'Piotr  Świeczka WZ568JA',
 'Tadeusz Malinowski WT5728E 719',
 'WG3122L Roman Gołędowski',
 'Tadeusz Podłog WT86086',
 'Oleksii Storchak WR835GX',
 'WG4986J kierowca Igor Isak',
 'Tomasz Kryszak WT1926G do godz. 16:00',
 'ES TRANS Olek Przeniczny WPI 4444F',
 'Konrad Chomiuk WG4625L',
 'Erwin Pilarski WJ1281H',
 'Wojtek Rosiński   Man WGM 8XF3',
 'Olech Ivasenko     WG6635L',
 'Ilin Maksim Mercedes WD 1727U',
 'Mibet WWL 2800P Rusłan Hlotov',
 'Robert Henczel Mercedes WD4163T',
 'Mateusz Kobierski MAN TGS 35.260 WG1824L',
 'Vitalii Ushakou MAN CWL00829',
 'Grzegorz Skowron WU8890H',
 'Igor Hovorukha MAN TGS 32.400 WG8255K',
 'Marcin Zapora WD4163T',
 'WZ3193X - Kobiałka Zenon',
 'Kosior',
 'MAN WJ2931G   Rusłan Skubi',
 'Piotr  Świeczka WZ568JA',
 'Tadeusz Malinowski WT5728E 719',
 'Tadeusz Podłog WT86086',
 'Oleksii Storchak WR835GX',
 'WG4986J kierowca Igor Isak',
 'Tomasz Kryszak WT1926G do godz. 16:00',
 'WG3122L Roman Gołędowski',
 'ES TRANS Olek Przeniczny WPI 4444F']

In [79]:
df.replace('[]',np.nan, inplace=True)

/tmp/ipykernel_26418/3044711181.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('[]',np.nan, inplace=True)

In [80]:
# df['Executors'] = df['Executors'].drop_duplicates()

In [81]:
df.replace('',np.nan, inplace=True)

In [82]:
df

,1,2,3,4,5,6,7,8,9,10,...,32,33,34,35,36,37,Executors,Free Executors,Missing Executors,First
2025-03-04 04:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:01:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:02:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:03:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
2025-03-04 04:04:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Kosior', 'MAN WJ2931G Rusłan Skubi', 'Marc...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-04 22:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 22:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 22:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 22:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN
2025-03-04 23:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,NaN,"['Konrad Chomiuk WG4625L', 'Wojtek Rosiński ...",NaN,NaN

In [83]:
list_starts = df["First"][df["First"].notna()]
list_starts

2025-03-04 06:30:00               MAN WJ2931G   Rusłan Skubi:: Kosior::
2025-03-04 07:00:00                             Marcin Zapora WD4163T::
2025-03-04 07:24:00                          WZ3193X - Kobiałka Zenon::
2025-03-04 11:18:00                           Piotr  Świeczka WZ568JA::
2025-03-04 11:30:00    Tadeusz Podłog WT86086:: WG3122L Roman Gołędow...
2025-03-04 11:42:00                          Oleksii Storchak WR835GX::
2025-03-04 11:54:00                        WG4986J kierowca Igor Isak::
2025-03-04 12:06:00             Tomasz Kryszak WT1926G do godz. 16:00::
2025-03-04 12:30:00    Erwin Pilarski WJ1281H:: Konrad Chomiuk WG4625...
2025-03-04 12:54:00    Olech Ivasenko     WG6635L:: Wojtek Rosiński  ...
2025-03-04 13:00:00                     Ilin Maksim Mercedes WD 1727U::
2025-03-04 13:34:00                     Mibet WWL 2800P Rusłan Hlotov::
2025-03-04 14:30:00    Igor Hovorukha MAN TGS 32.400 WG8255K:: Grzego...
Name: First, dtype: object

In [84]:
list_starts = list_starts.str.split("::")

In [85]:
list_starts = list_starts.explode()

In [86]:
list_starts.replace(' ',np.nan, inplace=True)

In [87]:
list_starts = list_starts.dropna()

In [88]:
list_starts

2025-03-04 06:30:00                   MAN WJ2931G   Rusłan Skubi
2025-03-04 06:30:00                                       Kosior
2025-03-04 07:00:00                        Marcin Zapora WD4163T
2025-03-04 07:24:00                     WZ3193X - Kobiałka Zenon
2025-03-04 11:18:00                      Piotr  Świeczka WZ568JA
2025-03-04 11:30:00                       Tadeusz Podłog WT86086
2025-03-04 11:30:00                     WG3122L Roman Gołędowski
2025-03-04 11:30:00               Tadeusz Malinowski WT5728E 719
2025-03-04 11:42:00                     Oleksii Storchak WR835GX
2025-03-04 11:54:00                   WG4986J kierowca Igor Isak
2025-03-04 12:06:00        Tomasz Kryszak WT1926G do godz. 16:00
2025-03-04 12:30:00                       Erwin Pilarski WJ1281H
2025-03-04 12:30:00                       Konrad Chomiuk WG4625L
2025-03-04 12:30:00           ES TRANS Olek Przeniczny WPI 4444F
2025-03-04 12:54:00                   Olech Ivasenko     WG6635L
2025-03-04 12:54:00               Wojtek Rosiński   Man WGM 8XF3
2025-03-04 13:00:00                Ilin Maksim Mercedes WD 1727U
2025-03-04 13:34:00                Mibet WWL 2800P Rusłan Hlotov
2025-03-04 14:30:00        Igor Hovorukha MAN TGS 32.400 WG8255K
2025-03-04 14:30:00                     Grzegorz Skowron WU8890H
2025-03-04 14:30:00                 Vitalii Ushakou MAN CWL00829
2025-03-04 14:30:00     Mateusz Kobierski MAN TGS 35.260 WG1824L
2025-03-04 14:30:00              Robert Henczel Mercedes WD4163T
Name: First, dtype: object